import type Stripe from "stripe";

/**
 * Field accessors for `Stripe.Invoice` under API `2026-01-28.clover` (stripe
 * v20). Several fields subscription code needs moved or were reshaped in
 * this version compared to older Stripe integrations — see the plan's "v20
 * shape traps":
 *
 *  - `invoice.subscription` is gone; the subscription id now lives at
 *    `invoice.parent.subscription_details.subscription`, and only when
 *    `invoice.parent.type === "subscription_details"`.
 *  - `invoice.parent.subscription_details.metadata` is an immutable snapshot
 *    of the *subscription's* metadata taken at invoice finalization — this
 *    is how webhook handlers recover `businessId`/`subscriptionId` from an
 *    `invoice.*` event without a second Stripe call.
 *  - `invoice.payment_intent` is gone; the PaymentIntent id is reached via
 *    `invoice.payments.data[].payment.payment_intent`, and `payments` is
 *    only present when the invoice was retrieved with `expand: ["payments"]`.
 *  - Taxes are `invoice.total_taxes[]`, not a single `tax` field.
 *
 * Pure field readers only — no Stripe API calls, no DB.
 */

function idOf(
  value: string | { id: string } | null | undefined,
): string | null {
  if (value == null) return null;
  return typeof value === "string" ? value : value.id;
}

/**
 * The subscription id this invoice was generated for, or `null` when the
 * invoice isn't a subscription invoice (e.g. `parent.type ===
 * "quote_details"`) or `parent` itself is null.
 */
export function getInvoiceSubscriptionId(
  invoice: Stripe.Invoice,
): string | null {
  if (invoice.parent?.type !== "subscription_details") {
    return null;
  }
  return idOf(invoice.parent.subscription_details?.subscription ?? null);
}

/**
 * The subscription's metadata snapshot on this invoice
 * (`parent.subscription_details.metadata`), or `null` when unavailable —
 * either because this isn't a subscription invoice, or the snapshot itself
 * is null (invoices finalized before metadata snapshotting existed).
 */
export function getInvoiceMetadata(
  invoice: Stripe.Invoice,
): Stripe.Metadata | null {
  if (invoice.parent?.type !== "subscription_details") {
    return null;
  }
  return invoice.parent.subscription_details?.metadata ?? null;
}

/**
 * The PaymentIntent id that paid this invoice, read from the expanded
 * `payments` list (`invoices.retrieve(id, { expand: ["payments"] })`).
 * Returns `null` when `payments` wasn't expanded, the list is empty, or the
 * first payment's `payment.type` isn't `"payment_intent"` (e.g. a `charge`).
 */
export function getInvoicePaymentIntentId(
  invoice: Stripe.Invoice,
): string | null {
  const payment = invoice.payments?.data[0]?.payment;
  if (payment?.type !== "payment_intent") return null;
  return idOf(payment.payment_intent ?? null);
}

/** Sum of `invoice.total_taxes[].amount`, in cents. `0` when there are no taxes. */
export function invoiceTaxCents(invoice: Stripe.Invoice): number {
  return (invoice.total_taxes ?? []).reduce((sum, tax) => sum + tax.amount, 0);
}

/** True when this invoice was generated by a subscription (vs. a quote or a one-off invoice). */
export function isSubscriptionInvoice(invoice: Stripe.Invoice): boolean {
  return invoice.parent?.type === "subscription_details";
}
