import type Stripe from "stripe";

/**
 * Field accessors for `Stripe.Invoice` under API `2026-01-28.clover` (stripe
 * v20). Several fields subscription code needs moved or were reshaped in
 * this version compared to older Stripe integrations — see the plan's "v20
 * shape traps":
 *
 *  - `invoice.subscription` is gone; the subscription id now lives at
 *    `invoice.parent.subscription_details.subscription`, and only when
 *    `invoice.parent.type === "subscription_details"`.
 *  - `invoice.parent.subscription_details.metadata` is an immutable snapshot
 *    of the *subscription's* metadata taken at invoice finalization — this
 *    is how webhook handlers recover `businessId`/`subscriptionId` from an
 *    `invoice.*` event without having to load the subscription too.
 *  - `invoice.payment_intent` is gone; the PaymentIntent id is reached via
 *    `invoice.payments.data[].payment.payment_intent`, and `payments` is
 *    only present when the invoice was retrieved with `expand: ["payments"]`.
 *  - Taxes are `invoice.total_taxes[]`, not a single `tax` field.
 *
 * ⚠️ **These readers assume an SDK-RETRIEVED invoice. Never feed them a raw
 * webhook payload.** Stripe renders `event.data.object` at the *receiving
 * webhook endpoint's* pinned API version, which is independent of the version
 * `stripeClient` is pinned to. On any endpoint older than `2025-03-31.basil`
 * an invoice has no `parent` key at all: the subscription id is at
 * `invoice.subscription` (string or expanded object) and the metadata snapshot
 * at `invoice.subscription_details.metadata`. Every accessor here would then
 * read `undefined` and answer `null`/`false` — `isSubscriptionInvoice` says
 * "not ours", the handler returns, and the store takes subscription payments
 * that never become orders, with no error anywhere. That is not hypothetical:
 * it is exactly what `invoice.paid` did on staging while the cron reconciler
 * (which goes through the SDK) created the same orders fine.
 *
 * Deliberately NOT papered over with a shape fallback here. A reader that
 * silently accepts either shape hides which objects came from where, and the
 * pre-`basil` payload is missing more than these four fields. The fix lives one
 * level up: `webhook.ts` re-retrieves every invoice through `stripeClient`
 * before the first gate ("retrieve first, gate second"), so everything reaching
 * this module is clover-shaped by construction.
 *
 * Pure field readers only — no Stripe API calls, no DB.
 */

function idOf(
  value: string | { id: string } | null | undefined,
): string | null {
  if (value == null) return null;
  return typeof value === "string" ? value : value.id;
}

/**
 * The subscription id this invoice was generated for, or `null` when the
 * invoice isn't a subscription invoice (e.g. `parent.type ===
 * "quote_details"`) or `parent` itself is null.
 */
export function getInvoiceSubscriptionId(
  invoice: Stripe.Invoice,
): string | null {
  if (invoice.parent?.type !== "subscription_details") {
    return null;
  }
  return idOf(invoice.parent.subscription_details?.subscription ?? null);
}

/**
 * The subscription's metadata snapshot on this invoice
 * (`parent.subscription_details.metadata`), or `null` when unavailable —
 * either because this isn't a subscription invoice, or the snapshot itself
 * is null (invoices finalized before metadata snapshotting existed).
 */
export function getInvoiceMetadata(
  invoice: Stripe.Invoice,
): Stripe.Metadata | null {
  if (invoice.parent?.type !== "subscription_details") {
    return null;
  }
  return invoice.parent.subscription_details?.metadata ?? null;
}

/**
 * The PaymentIntent id that paid this invoice, read from the expanded
 * `payments` list (`invoices.retrieve(id, { expand: ["payments"] })`).
 * Returns `null` when `payments` wasn't expanded, the list is empty, or the
 * first payment's `payment.type` isn't `"payment_intent"` (e.g. a `charge`).
 */
export function getInvoicePaymentIntentId(
  invoice: Stripe.Invoice,
): string | null {
  const payment = invoice.payments?.data[0]?.payment;
  if (payment?.type !== "payment_intent") return null;
  return idOf(payment.payment_intent ?? null);
}

/** Sum of `invoice.total_taxes[].amount`, in cents. `0` when there are no taxes. */
export function invoiceTaxCents(invoice: Stripe.Invoice): number {
  return (invoice.total_taxes ?? []).reduce((sum, tax) => sum + tax.amount, 0);
}

/**
 * True when this invoice was generated by a subscription (vs. a quote or a
 * one-off invoice).
 *
 * The gate every `invoice.*` handler opens with — and therefore the one place
 * where feeding in a raw webhook payload is silently catastrophic rather than
 * merely wrong. See the module doc comment: pass it an SDK-retrieved invoice.
 */
export function isSubscriptionInvoice(invoice: Stripe.Invoice): boolean {
  return invoice.parent?.type === "subscription_details";
}
