import type { TemplateField, TemplateFieldGroup } from "~/lib/template-fields";

const homepageHeroData: TemplateField[] = [
  {
    key: "happy-bamboo.homepage.hero-image",
    label: "Homepage Hero Image",
    description:
      "This image is used as the main focal point of the hero section.",
    type: "image",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
  },
  {
    key: "happy-bamboo.homepage.hero-welcome",
    label: "Homepage Hero Welcome",
    description: "Welcome text for the hero section",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Welcome to",
  },
  {
    key: "happy-bamboo.homepage.hero-title",
    label: "Homepage Hero Title",
    description: "Title for the hero section",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Elevate Your Everyday",
  },
  {
    key: "happy-bamboo.homepage.hero-tagline",
    label: "Homepage Hero Tagline",
    description: "Tagline for the hero section, above the title.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
  },
  {
    key: "happy-bamboo.homepage.hero-description",
    label: "Homepage Hero Description",
    description: "Description for the hero section",
    type: "textarea",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
    defaultValue:
      "Luxuriously soft, tree-free happy-bamboo paper products crafted in Detroit. Because what you bring into your home should be as thoughtful as the life you build in it.",
  },
  {
    key: "happy-bamboo.homepage.hero-primary-button-text",
    label: "Hero Primary Button Text",
    description: "Primary CTA button text (e.g. Shop Now)",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Shop Now",
  },
  {
    key: "happy-bamboo.homepage.hero-primary-button-link",
    label: "Hero Primary Button Link",
    description: "Primary CTA button URL",
    type: "url",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "/shop",
  },
];

const homepageAboutTeaserData: TemplateField[] = [
  {
    key: "happy-bamboo.homepage-about-heading",
    label: "About Section Heading",
    description: "Heading for the about block",
    type: "text",
    page: "homepage",
    group: "homepage.aboutTeaser",
    defaultValue: "From Detroit, With Purpose",
  },
  {
    key: "happy-bamboo.homepage-about-body",
    label: "About Teaser Body",
    description: "Body text for the about teaser",
    type: "richtext",
    page: "homepage",
    group: "homepage.aboutTeaser",
  },
  {
    key: "happy-bamboo.homepage-about-video",
    label: "About Section Video",
    description: "Video shown in the homepage about section",
    type: "video",
    page: "homepage",
    group: "homepage.aboutTeaser",
  },
  {
    key: "happy-bamboo.homepage-about-video-poster",
    label: "About Section Video Poster",
    description: "Poster image for the about section video",
    type: "image",
    page: "homepage",
    group: "homepage.aboutTeaser",
  },
  {
    key: "happy-bamboo.homepage-about-button-text",
    label: "About Button Text",
    description: "Learn More button text",
    type: "text",
    page: "homepage",
    group: "homepage.aboutTeaser",
    defaultValue: "Learn More",
  },
  {
    key: "happy-bamboo.homepage-about-button-link",
    label: "About Button Link",
    description: "Link for the about button",
    type: "url",
    page: "homepage",
    group: "homepage.aboutTeaser",
    defaultValue: "/about",
  },
];

const homepageFeaturedData: TemplateField[] = [
  {
    key: "happy-bamboo.homepage-featured-title",
    label: "Featured Section Title",
    description: "Title for the featured products section",
    type: "text",
    page: "homepage",
    group: "homepage.featured",
    defaultValue: "Our Curated Collection",
  },
  {
    key: "happy-bamboo.homepage-featured-description",
    label: "Featured Section Description",
    description: "Description below the featured section title",
    type: "textarea",
    page: "homepage",
    group: "homepage.featured",
    defaultValue:
      "Every product is 100% happy-bamboo, tree-free, and crafted to the highest standard. No compromises.",
  },
  {
    key: "happy-bamboo.homepage-featured-button-text",
    label: "View All Button Text",
    description: "Text for the View All Products button",
    type: "text",
    page: "homepage",
    group: "homepage.featured",
    defaultValue: "View All Products",
  },
  {
    key: "happy-bamboo.homepage-featured-button-link",
    label: "View All Button Link",
    description: "Link for the View All Products button",
    type: "url",
    page: "homepage",
    group: "homepage.featured",
    defaultValue: "/shop",
  },
];

const homepageBenefitsData: TemplateField[] = [
  {
    key: "happy-bamboo.homepage-benefits-list",
    label: "Benefits cards",
    description:
      "Cards for the Why Choose Bamboo Products section (icon, title, and description per item).",
    type: "list",
    page: "homepage",
    group: "homepage.benefits",
    gridColumn: "col-span-full",
    itemSchema: [
      {
        key: "icon",
        label: "Icon",
        type: "icon",
        description: "Icon shown on the card",
      },
      {
        key: "title",
        label: "Title",
        type: "text",
        description: "Card heading",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        description: "Supporting text",
      },
    ],
    minItems: 0,
    maxItems: 24,
  },
];

// const homepageSustainabilityData: TemplateField[] = [
//   {
//     key: "happy-bamboo.homepage.sustainability-1-label",
//     label: "Sustainability Feature 1 Label",
//     description: "First feature label (e.g. Premium Quality)",
//     type: "text",
//     page: "homepage",
//     group: "homepage.sustainability",
//     defaultValue: "Premium Quality",
//   },
//   {
//     key: "happy-bamboo.homepage.sustainability-1-description",
//     label: "Sustainability Feature 1 Description",
//     description: "First feature description",
//     type: "textarea",
//     page: "homepage",
//     group: "homepage.sustainability",
//     defaultValue:
//       "Experience top-quality household paper products, crafted for comfort and reliability.",
//   },
//   {
//     key: "happy-bamboo.homepage.sustainability-2-label",
//     label: "Sustainability Feature 2 Label",
//     description: "Second feature label",
//     type: "text",
//     page: "homepage",
//     group: "homepage.sustainability",
//     defaultValue: "Competitive Prices",
//   },
//   {
//     key: "happy-bamboo.homepage.sustainability-2-description",
//     label: "Sustainability Feature 2 Description",
//     description: "Second feature description",
//     type: "textarea",
//     page: "homepage",
//     group: "homepage.sustainability",
//     defaultValue: "Affordable prices without compromising quality.",
//   },
//   {
//     key: "happy-bamboo.homepage.sustainability-3-label",
//     label: "Sustainability Feature 3 Label",
//     description: "Third feature label",
//     type: "text",
//     page: "homepage",
//     group: "homepage.sustainability",
//     defaultValue: "Customer-Centric Approach",
//   },
//   {
//     key: "happy-bamboo.homepage.sustainability-3-description",
//     label: "Sustainability Feature 3 Description",
//     description: "Third feature description",
//     type: "textarea",
//     page: "homepage",
//     group: "homepage.sustainability",
//     defaultValue: "Your satisfaction comes first in everything we do.",
//   },
// ];

// const homepageLocationData: TemplateField[] = [
//   {
//     key: "happy-bamboo.homepage.location-heading",
//     label: "Location Section Heading",
//     description: "Heading for the location section on homepage",
//     type: "text",
//     page: "homepage",
//     group: "homepage.location",
//     defaultValue: "Our Location",
//   },
// ];

// const homepageTestimonialsData: TemplateField[] = [
//   {
//     key: "happy-bamboo.homepage.testimonial-1-name",
//     label: "Testimonial 1 Name",
//     description: "First testimonial author name",
//     type: "text",
//     page: "homepage",
//     group: "homepage.testimonials",
//     defaultValue: "Sarah M.",
//   },
//   {
//     key: "happy-bamboo.homepage.testimonial-1-location",
//     label: "Testimonial 1 Location",
//     description: "First testimonial location",
//     type: "text",
//     page: "homepage",
//     group: "homepage.testimonials",
//     defaultValue: "Ann Arbor, MI",
//   },
//   {
//     key: "happy-bamboo.homepage.testimonial-1-quote",
//     label: "Testimonial 1 Quote",
//     description: "First testimonial quote",
//     type: "textarea",
//     page: "homepage",
//     group: "homepage.testimonials",
//     defaultValue:
//       "I never thought I would care this much about toilet paper, but the softness and quality are genuinely impressive. Knowing it is eco-friendly makes it even better.",
//   },
//   {
//     key: "happy-bamboo.homepage.testimonial-2-name",
//     label: "Testimonial 2 Name",
//     description: "Second testimonial author name",
//     type: "text",
//     page: "homepage",
//     group: "homepage.testimonials",
//     defaultValue: "James T.",
//   },
//   {
//     key: "happy-bamboo.homepage.testimonial-2-location",
//     label: "Testimonial 2 Location",
//     description: "Second testimonial location",
//     type: "text",
//     page: "homepage",
//     group: "homepage.testimonials",
//     defaultValue: "Chicago, IL",
//   },
//   {
//     key: "happy-bamboo.homepage.testimonial-2-quote",
//     label: "Testimonial 2 Quote",
//     description: "Second testimonial quote",
//     type: "textarea",
//     page: "homepage",
//     group: "homepage.testimonials",
//     defaultValue:
//       "We switched our entire household to Finally Results and have not looked back. The starter kit is the perfect way to try everything. Our septic system thanks us too.",
//   },
//   {
//     key: "happy-bamboo.homepage.testimonial-3-name",
//     label: "Testimonial 3 Name",
//     description: "Third testimonial author name",
//     type: "text",
//     page: "homepage",
//     group: "homepage.testimonials",
//     defaultValue: "Angela R.",
//   },
//   {
//     key: "happy-bamboo.homepage.testimonial-3-location",
//     label: "Testimonial 3 Location",
//     description: "Third testimonial location",
//     type: "text",
//     page: "homepage",
//     group: "homepage.testimonials",
//     defaultValue: "Detroit, MI",
//   },
//   {
//     key: "happy-bamboo.homepage.testimonial-3-quote",
//     label: "Testimonial 3 Quote",
//     description: "Third testimonial quote",
//     type: "textarea",
//     page: "homepage",
//     group: "homepage.testimonials",
//     defaultValue:
//       "Supporting a local Detroit business that actually cares about sustainability? That is a win-win. The product quality is on par with luxury brands at a fraction of the environmental cost.",
//   },
// ];

const aboutHeroData: TemplateField[] = [
  // {
  //   key: "happy-bamboo.about-hero-heading",
  //   label: "About Hero Heading",
  //   description: "Main heading for the about page",
  //   type: "text",
  //   page: "about",
  //   group: "about.hero",
  //   defaultValue: "Our Story",
  // },
  {
    key: "happy-bamboo.about-hero-mission",
    label: "About Hero Mission",
    description: "Mission statement for the about page",
    type: "textarea",
    page: "about",
    group: "about.hero",
    placeholder: "To offer eco-friendly, chemical and hypoallergenic free...",
  },
  {
    key: "happy-bamboo.about-hero-vision",
    label: "About Hero Vision",
    description: "Vision statement for the about page",
    type: "textarea",
    page: "about",
    group: "about.hero",
    placeholder: "A world where everyday personal care choices protect...",
  },

  {
    key: "happy-bamboo.about-hero-bamboo",
    label: "About Hero Bamboo",
    description: "Bamboo statement for the about page",
    type: "textarea",
    page: "about",
    group: "about.hero",
    placeholder: "By choosing Happy Bamboo...",
  },
  {
    key: "happy-bamboo.about-hero-image",
    label: "About Hero Image",
    description: "Image for the about page",
    type: "image",
    page: "about",
    group: "about.hero",
    gridColumn: "col-span-full",
  },
];

// const aboutMissionData: TemplateField[] = [
//   {
//     key: "happy-bamboo.about-mission-banner",
//     label: "Mission Banner",
//     description: "Mission banner for the about page",
//     type: "textarea",
//     page: "about",
//     group: "about.mission",
//     placeholder: "Join us in our mission to make everyday moments...",
//   },
// ];

const aboutServicesData: TemplateField[] = [
  {
    key: "happy-bamboo.about-services-heading",
    label: "Services Heading",
    description: "Services heading for the about page",
    type: "text",
    page: "about",
    group: "about.services",
    defaultValue: "Our Services",
  },
  {
    key: "happy-bamboo.about-services-banner",
    label: "Services Banner",
    description: "Mission banner for the about page",
    type: "textarea",
    page: "about",
    group: "about.mission",
    placeholder: "Join us in our mission to make everyday moments...",
  },
  {
    key: "happy-bamboo.about-services-list",
    label: "Services List",
    description: "Services list for the about page",
    type: "list",
    page: "about",
    group: "about.services",
    itemSchema: [
      {
        key: "icon",
        label: "Icon",
        type: "icon",
        description: "Icon shown on the card",
      },
      {
        key: "title",
        label: "Title",
        type: "text",
        description: "Card heading",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        description: "Supporting text",
      },
    ],
    minItems: 0,
    maxItems: 8,
  },
];

const aboutBambooData: TemplateField[] = [
  {
    key: "happy-bamboo.about-bamboo-heading",
    label: "Bamboo Heading",
    description: "Bamboo heading for the about page",
    type: "text",
    page: "about",
    group: "about.bamboo",
    defaultValue: "Why Bamboo?",
  },
  {
    key: "happy-bamboo.about-bamboo-description",
    label: "Bamboo Intro",
    description: "Intro line for Bamboo section",
    type: "textarea",
    page: "about",
    group: "about.bamboo",
    placeholder: "Bamboo is nature's most remarkable...",
  },
  {
    key: "happy-bamboo.about-bamboo-list",
    label: "Bamboo Facts List",
    description: "Bamboo list for the about page",
    type: "list",
    page: "about",
    group: "about.bamboo",
    itemSchema: [
      {
        key: "icon",
        label: "Icon",
        type: "icon",
        description: "Icon shown on the card",
      },
      {
        key: "title",
        label: "Title",
        type: "text",
        description: "Card heading",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        description: "Supporting text",
      },
    ],
    minItems: 0,
    maxItems: 24,
  },
  {
    key: "happy-bamboo.about-bamboo-image-1",
    label: "Bamboo Image 1",
    description: "Bamboo image 1 for the about page",
    type: "image",
    page: "about",
    group: "about.bamboo",
    gridColumn: "col-span-1",
  },
  {
    key: "happy-bamboo.about-bamboo-image-2",
    label: "Bamboo Image 2",
    description: "Bamboo image 2 for the about page",
    type: "image",
    page: "about",
    group: "about.bamboo",
    gridColumn: "col-span-1",
  },
  {
    key: "happy-bamboo.about-bamboo-image-3",
    label: "Bamboo Image 3",
    description: "Bamboo image 3 for the about page",
    type: "image",
    page: "about",
    group: "about.bamboo",
    gridColumn: "col-span-1",
  },
];

const aboutCTAData: TemplateField[] = [
  {
    key: "happy-bamboo.about-cta-image",
    label: "CTA Image",
    description: "CTA image for the about page",
    type: "image",
    page: "about",
    group: "about.cta",
    gridColumn: "col-span-1",
  },
];

const contactPageData: TemplateField[] = [
  {
    key: "happy-bamboo.contact.header",
    label: "Contact Page Header",
    description: "Main heading for the contact page",
    type: "text",
    page: "contact",
    group: "contact.info",
    defaultValue: "Get in Touch",
  },
  {
    key: "happy-bamboo.contact.subheader",
    label: "Contact Page Subheader",
    description: "Subheader or intro below the heading",
    type: "textarea",
    page: "contact",
    group: "contact.info",
    defaultValue:
      "Have a question, want to partner with us, or just want to say hello? We would love to hear from you.",
  },
  {
    key: "happy-bamboo.contact.email",
    label: "Contact Email",
    description: "Email address displayed on contact page",
    type: "text",
    page: "contact",
    group: "contact.info",
    defaultValue: "happybamboo25@gmail.com",
  },
  {
    key: "happy-bamboo.contact.location",
    label: "Contact Location",
    description: "Location text (e.g. city, state)",
    type: "text",
    page: "contact",
    group: "contact.info",
    defaultValue: "Detroit, Michigan",
  },
  {
    key: "happy-bamboo.contact.phone",
    label: "Contact Phone",
    description: "Phone number",
    type: "text",
    page: "contact",
    group: "contact.info",
    defaultValue: "(313) 555-0199",
  },
  {
    key: "happy-bamboo.contact.hours",
    label: "Business Hours",
    description: "Business hours text",
    type: "text",
    page: "contact",
    group: "contact.info",
    defaultValue: "Mon - Fri, 9am - 5pm EST",
  },
  {
    key: "happy-bamboo.contact-image",
    label: "Contact Image",
    description: "Contact image for the contact page",
    type: "image",
    page: "contact",
    group: "contact.info",
    gridColumn: "col-span-1",
  },
  {
    key: "happy-bamboo.contact-frequently-asked-questions",
    label: "Contact Frequently Asked Questions",
    description: "Contact frequently asked questions for the contact page",
    type: "list",
    page: "contact",
    group: "contact.info",
    itemSchema: [
      {
        key: "question",
        label: "Question",
        type: "text",
        description: "Question",
      },
      {
        key: "answer",
        label: "Answer",
        type: "textarea",
        description: "Answer",
      },
    ],
    minItems: 0,
    maxItems: 10,
  },
];

// const globalLocationData: TemplateField[] = [
//   {
//     key: "happy-bamboo.global.location-address",
//     label: "Global Location Address",
//     description: "Address for the global location section (used for map link)",
//     type: "text",
//     page: "global",
//     group: "global.location",
//     gridColumn: "col-span-full",
//     defaultValue: "18058, Detroit, MI 48234",
//   },
//   {
//     key: "happy-bamboo.global.location-map",
//     label: "Global Location Map",
//     description: "Map image for the global location section",
//     type: "image",
//     page: "global",
//     group: "global.location",
//     gridColumn: "col-span-full",
//   },
// ];

const fieldGroups: TemplateFieldGroup[] = [
  {
    id: "homepage.hero",
    title: "Hero Section",
    description: "Main banner area at the top of homepage",
    icon: "🎯",
    columns: 2,
  },
  {
    id: "homepage.featured",
    title: "Featured Products",
    description: "Featured products section title and description",
    icon: "📦",
    columns: 2,
  },
  {
    id: "homepage.benefits",
    title: "Benefits",
    description: "Why choose bamboo — icon cards on the homepage",
    icon: "✨",
    columns: 1,
  },
  {
    id: "homepage.aboutTeaser",
    title: "About Teaser",
    description: "About teaser block on homepage",
    icon: "📄",
    columns: 2,
  },
  // {
  //   id: "homepage.sustainability",
  //   title: "Sustainability Banner",
  //   description:
  //     "Three feature highlights (e.g. Premium Quality, Competitive Prices)",
  //   icon: "🌿",
  //   columns: 2,
  // },
  // {
  //   id: "homepage.location",
  //   title: "Location Section",
  //   description: "Location heading on homepage",
  //   icon: "📍",
  //   columns: 2,
  // },
  // {
  //   id: "homepage.testimonials",
  //   title: "Testimonials",
  //   description: "Customer testimonials (name, location, quote)",
  //   icon: "💬",
  //   columns: 2,
  // },
  {
    id: "about.hero",
    title: "About Hero",
    description: "About page hero heading and intro",
    icon: "📖",
    columns: 2,
  },
  // {
  //   id: "about.mission",
  //   title: "Our Mission",
  //   description: "Mission section heading and paragraphs",
  //   icon: "🎯",
  //   columns: 2,
  // },
  // {
  //   id: "about.values",
  //   title: "What We Stand For",
  //   description: "Values section with three value cards",
  //   icon: "❤️",
  //   columns: 2,
  // },
  // {
  //   id: "about.supplier",
  //   title: "Supplier",
  //   description: "Supplier section heading and text",
  //   icon: "🏪",
  //   columns: 2,
  // },

  {
    id: "about.bamboo",
    title: "Why Bamboo",
    description: "Bamboo section and bamboo facts",
    icon: "🎋",
    columns: 2,
  },
  {
    id: "about.services",
    title: "Services",
    description: "Services section heading and paragraphs",
    icon: "�",
    columns: 2,
  },
  {
    id: "about.cta",
    title: "About CTA",
    description: "About CTA section",
    icon: "💬",
    columns: 2,
  },
  // {
  //   id: "contact.info",
  //   title: "Contact Info",
  //   description: "Contact page header and contact details",
  //   icon: "📧",
  //   columns: 2,
  // },
  // {
  //   id: "global.location",
  //   title: "Global Location Section",
  //   description: "Global location section on the homepage",
  //   icon: "🗺️",
  //   columns: 2,
  // },
];

export const happyBambooData = {
  "happy-bamboo": [
    ...homepageHeroData,
    ...homepageFeaturedData,
    ...homepageBenefitsData,
    ...homepageAboutTeaserData,
    // ...homepageSustainabilityData,
    // ...homepageLocationData,
    // ...homepageTestimonialsData,
    ...aboutHeroData,
    // ...aboutMissionData,
    ...aboutServicesData,
    ...aboutBambooData,
    ...aboutCTAData,
    // ...contactPageData,
    // ...globalLocationData,
  ],
};

export const happyBambooFieldGroups = {
  "happy-bamboo": fieldGroups,
};
