import type { TemplateField, TemplateFieldGroup } from "~/lib/template-fields";
import type { TemplateSection } from "~/lib/template-sections";
import { SECTION_LINKS } from "~/lib/section-links";

/**
 * Collections fields for the `pink` template — index AND detail pages,
 * both `page: "collections"` (design.md → "Per-page section concepts →
 * Collections"). Per-collection content (name, description, image, product
 * list) always comes from the `Collection` record; fields here cover
 * chrome/microcopy and the two owner-configured image layouts.
 */
export const pinkCollectionsData: TemplateField[] = [
  // ── collections.header (index) ──────────────────────────────────────────
  {
    key: "pink.collections.header-heading",
    label: "Heading",
    description: "The page's main heading, on the collections index.",
    type: "text",
    page: "collections",
    group: "collections.header",
    gridColumn: "col-span-1",
    defaultValue: "Every series, gathered.",
  },
  {
    key: "pink.collections.header-intro",
    label: "Intro text",
    description: "Shown in the right column of the header, beside the heading.",
    type: "textarea",
    page: "collections",
    group: "collections.header",
    gridColumn: "col-span-full",
    defaultValue:
      "Pieces get grouped by what they're for and when they were made. Every one is one of a kind. Some series are still open, some are closed for good.",
  },

  // ── collections.featured (index) ────────────────────────────────────────
  {
    key: "pink.collections.featured-badge",
    label: "Badge text",
    description: "Corner badge on the featured collection card.",
    type: "text",
    page: "collections",
    group: "collections.featured",
    gridColumn: "col-span-1",
    defaultValue: "Featured",
  },
  {
    key: "pink.collections.featured-cta-label",
    label: "Link text",
    description: "Link to the featured collection.",
    type: "text",
    page: "collections",
    group: "collections.featured",
    gridColumn: "col-span-1",
    defaultValue: "See the series →",
  },

  // ── collections.grid (index) ────────────────────────────────────────────
  {
    key: "pink.collections.grid-badge-open",
    label: "Badge text — open",
    description: "Status badge on cards for collections still being added to.",
    type: "text",
    page: "collections",
    group: "collections.grid",
    gridColumn: "col-span-1",
    defaultValue: "Open",
  },
  {
    key: "pink.collections.grid-badge-closed",
    label: "Badge text — closed",
    description:
      "Status badge on cards for unpublished-going-forward collections.",
    type: "text",
    page: "collections",
    group: "collections.grid",
    gridColumn: "col-span-1",
    defaultValue: "Closed",
  },

  // ── collections.next (index) ────────────────────────────────────────────
  {
    key: "pink.collections.next-heading",
    label: "Heading",
    type: "text",
    page: "collections",
    group: "collections.next",
    gridColumn: "col-span-1",
    description: "Heading in the closing band at the bottom of the page.",
    defaultValue: "The next series starts soon.",
  },
  {
    key: "pink.collections.next-body",
    label: "Body text",
    type: "textarea",
    page: "collections",
    group: "collections.next",
    gridColumn: "col-span-full",
    description: "One or two sentences under the heading above.",
    defaultValue:
      "Get in touch to hear when new work goes up, or to ask about a piece of your own.",
  },
  {
    key: "pink.collections.next-cta-primary-label",
    label: "Button text",
    type: "text",
    page: "collections",
    group: "collections.next",
    gridColumn: "col-span-1",
    description: "Leave blank to hide the button.",
    defaultValue: "Get in touch",
  },
  {
    key: "pink.collections.next-cta-primary-href",
    label: "Button link",
    type: "url",
    page: "collections",
    group: "collections.next",
    gridColumn: "col-span-1",
    description: "Where the button goes.",
    defaultValue: "/contact",
  },
  {
    key: "pink.collections.next-cta-secondary-label",
    label: "Button text — second button",
    type: "text",
    page: "collections",
    group: "collections.next",
    gridColumn: "col-span-1",
    description: "Leave blank to hide the button.",
    defaultValue: "See the shop",
  },
  {
    key: "pink.collections.next-cta-secondary-href",
    label: "Button link — second button",
    type: "url",
    page: "collections",
    group: "collections.next",
    gridColumn: "col-span-1",
    description: "Where the second button goes.",
    defaultValue: "/shop",
  },
  {
    key: "pink.collections.next-image-1",
    label: "Image 1",
    type: "image",
    page: "collections",
    group: "collections.next",
    gridColumn: "col-span-1",
    description: "Left image of the pair in the closing band.",
    // Empty on purpose — the pair sits on a dark band.
    defaultValue: "",
  },
  {
    key: "pink.collections.next-image-2",
    label: "Image 2",
    type: "image",
    page: "collections",
    group: "collections.next",
    gridColumn: "col-span-1",
    description: "Right image of the pair in the closing band.",
    // Empty on purpose — the pair sits on a dark band.
    defaultValue: "",
  },

  // ── collections.detail-hero (detail) ────────────────────────────────────
  {
    key: "pink.collections.detail-hero-fact-pieces-label",
    label: "Label — piece count",
    type: "text",
    page: "collections",
    group: "collections.detail-hero",
    gridColumn: "col-span-1",
    description: "Label for the piece-count fact row.",
    defaultValue: "Pieces",
  },
  {
    key: "pink.collections.detail-hero-fact-available-label",
    label: "Label — available count",
    type: "text",
    page: "collections",
    group: "collections.detail-hero",
    gridColumn: "col-span-1",
    description: "Label for the available-count fact row.",
    defaultValue: "Available",
  },
  {
    key: "pink.collections.detail-hero-fact-price-label",
    label: "Label — starting price",
    type: "text",
    page: "collections",
    group: "collections.detail-hero",
    gridColumn: "col-span-1",
    description: "Label for the starting-price fact row.",
    defaultValue: "From",
  },

  // ── collections.detail-intro (detail) ───────────────────────────────────
  {
    key: "pink.collections.detail-intro-heading",
    label: "Heading",
    type: "text",
    page: "collections",
    group: "collections.detail-intro",
    gridColumn: "col-span-1",
    description: "Heading beside the collection's own description.",
    defaultValue: "What holds it together.",
  },

  // ── collections.detail-gallery (detail) ─────────────────────────────────
  {
    key: "pink.collections.detail-gallery-images",
    label: "Gallery images",
    description:
      "Up to 6 photos in a layout shown on every collection detail page. Leave blank to hide this section until you add photos.",
    type: "list",
    page: "collections",
    group: "collections.detail-gallery",
    gridColumn: "col-span-full",
    maxItems: 6,
    itemLabel: "photo",
    itemSchema: [
      {
        key: "image",
        label: "Image",
        type: "image",
        description: "One photo for the layout.",
      },
      {
        key: "colSpan",
        label: "Column span",
        type: "text",
        description: "How many columns this photo fills — 1 to 4. Leave blank for 1.",
        placeholder: "1",
        optional: true,
      },
      {
        key: "rowSpan",
        label: "Row span",
        type: "text",
        description: "How many rows this photo fills — 1 or 2. Leave blank for 1.",
        placeholder: "1",
        optional: true,
      },
    ],
  },

  // ── collections.detail-grid (detail) ────────────────────────────────────
  {
    key: "pink.collections.detail-grid-heading-prefix",
    label: "Heading prefix",
    description: "Prefix word before the piece count, e.g. 'The' → 'The 12'.",
    type: "text",
    page: "collections",
    group: "collections.detail-grid",
    gridColumn: "col-span-1",
    defaultValue: "The",
  },
  {
    key: "pink.collections.detail-grid-filter-all",
    label: "Filter chip — all",
    type: "text",
    page: "collections",
    group: "collections.detail-grid",
    gridColumn: "col-span-1",
    description: "Filter chip label for showing every piece in the collection.",
    defaultValue: "All",
  },
  {
    key: "pink.collections.detail-grid-filter-available",
    label: "Filter chip — available",
    type: "text",
    page: "collections",
    group: "collections.detail-grid",
    gridColumn: "col-span-1",
    description: "Filter chip label for showing only in-stock pieces.",
    defaultValue: "Available",
  },
  {
    key: "pink.collections.detail-grid-filter-archive",
    label: "Filter chip — archive",
    type: "text",
    page: "collections",
    group: "collections.detail-grid",
    gridColumn: "col-span-1",
    description: "Filter chip label for showing only sold pieces.",
    defaultValue: "Archive",
  },
  {
    key: "pink.collections.detail-grid-sold-label",
    label: "Sold price label",
    description: "Shown in place of a price on sold-out pieces.",
    type: "text",
    page: "collections",
    group: "collections.detail-grid",
    gridColumn: "col-span-1",
    defaultValue: "Sold",
  },
  {
    key: "pink.collections.detail-grid-sold-badge",
    label: "Sold badge text",
    description: "Corner badge on sold-out pieces.",
    type: "text",
    page: "collections",
    group: "collections.detail-grid",
    gridColumn: "col-span-1",
    defaultValue: "Rehomed",
  },
  {
    key: "pink.collections.detail-grid-sold-cta",
    label: "Sold piece button text",
    description: "Disabled button shown on sold-out pieces.",
    type: "text",
    page: "collections",
    group: "collections.detail-grid",
    gridColumn: "col-span-1",
    defaultValue: "Ask about a custom order",
  },

  // ── collections.detail-nav (detail) ─────────────────────────────────────
  {
    key: "pink.collections.detail-nav-prev-label",
    label: "Label — previous",
    type: "text",
    page: "collections",
    group: "collections.detail-nav",
    gridColumn: "col-span-1",
    description: "Label on the previous-collection card.",
    defaultValue: "Previous series",
  },
  {
    key: "pink.collections.detail-nav-next-label",
    label: "Label — next",
    type: "text",
    page: "collections",
    group: "collections.detail-nav",
    gridColumn: "col-span-1",
    description: "Label on the next-collection card.",
    defaultValue: "Next series",
  },
];

export const pinkCollectionsFieldGroups: TemplateFieldGroup[] = [
  {
    id: "collections.header",
    title: "Header",
    description: "Heading and intro at the top of the collections index.",
    icon: "🗂️",
    columns: 2,
  } satisfies TemplateFieldGroup,
  {
    id: "collections.featured",
    title: "Featured card",
    description: "Badge and link text on the featured collection card.",
    icon: "⭐",
    columns: 2,
  } satisfies TemplateFieldGroup,
  {
    id: "collections.grid",
    title: "Grid badges",
    description: "Open/closed status badge text.",
    icon: "🧩",
    columns: 2,
  } satisfies TemplateFieldGroup,
  {
    id: "collections.next",
    title: "Closing band",
    description: "The band at the bottom of the collections index.",
    icon: "🔮",
    columns: 2,
  } satisfies TemplateFieldGroup,
  {
    id: "collections.detail-hero",
    title: "Hero",
    description: "Fact-row labels on every collection detail page.",
    icon: "🖼️",
    columns: 2,
  } satisfies TemplateFieldGroup,
  {
    id: "collections.detail-intro",
    title: "Intro",
    description: "Heading beside the collection's own description.",
    icon: "📝",
    columns: 2,
  } satisfies TemplateFieldGroup,
  {
    id: "collections.detail-gallery",
    title: "Gallery",
    description:
      "The shared image layout shown on every collection detail page.",
    icon: "🧵",
    columns: 1,
  } satisfies TemplateFieldGroup,
  {
    id: "collections.detail-grid",
    title: "Piece grid",
    description: "Heading prefix, filter chips and sold-piece microcopy.",
    icon: "🧺",
    columns: 2,
  } satisfies TemplateFieldGroup,
  {
    id: "collections.detail-nav",
    title: "Prev/next",
    description: "Labels on the previous/next series band.",
    icon: "↔️",
    columns: 2,
  } satisfies TemplateFieldGroup,
];

export const pinkCollectionsSections: TemplateSection[] = [
  {
    id: "collections.header",
    page: "collections",
    title: "Header",
    description: "Heading and intro at the top of the collections index",
    groupIds: ["collections.header"],
    order: 0,
    hideable: false,
  },
  {
    id: "collections.featured",
    page: "collections",
    title: "Featured card",
    description: "Featured collection card, sourced from the first collection",
    groupIds: ["collections.featured"],
    order: 1,
    hideable: true,
    links: [SECTION_LINKS.collections],
  },
  {
    id: "collections.grid",
    page: "collections",
    title: "Grid badges",
    description: "The full collections grid",
    groupIds: ["collections.grid"],
    order: 2,
    hideable: false,
    links: [SECTION_LINKS.collections],
  },
  {
    id: "collections.next",
    page: "collections",
    title: "Closing band",
    description: "Band at the bottom of the collections index",
    groupIds: ["collections.next"],
    order: 3,
    hideable: true,
  },
  {
    id: "collections.detail-hero",
    page: "collections",
    title: "Hero",
    description: "Photo hero with derived fact rows",
    groupIds: ["collections.detail-hero"],
    order: 4,
    hideable: false,
    links: [SECTION_LINKS.collections],
  },
  {
    id: "collections.detail-intro",
    page: "collections",
    title: "Intro",
    description: "Heading and the collection's own description",
    groupIds: ["collections.detail-intro"],
    order: 5,
    hideable: true,
    links: [SECTION_LINKS.collections],
  },
  {
    id: "collections.detail-gallery",
    page: "collections",
    title: "Gallery",
    description: "Image layout band",
    groupIds: ["collections.detail-gallery"],
    order: 6,
    hideable: true,
  },
  {
    id: "collections.detail-grid",
    page: "collections",
    title: "Piece grid",
    description: "The collection's products, with filter chips",
    groupIds: ["collections.detail-grid"],
    order: 7,
    hideable: false,
    links: [SECTION_LINKS.products, SECTION_LINKS.collections],
  },
  {
    id: "collections.detail-nav",
    page: "collections",
    title: "Prev/next",
    description: "Band linking to neighbouring series",
    groupIds: ["collections.detail-nav"],
    order: 8,
    hideable: true,
  },
];
