import type { TemplateField, TemplateFieldGroup } from "~/lib/template-fields";
import type { TemplateSection } from "~/lib/template-sections";

/**
 * Collections fields for the `pink` template — index AND detail pages,
 * both `page: "collections"` (design.md → "Per-page section concepts →
 * Collections"). Per-collection content (name, description, image, product
 * list) always comes from the `Collection` record; fields here cover
 * chrome/microcopy and the two owner-configured mosaics.
 */
export const pinkCollectionsData: TemplateField[] = [
  // ── collections.header (index) ──────────────────────────────────────────
  {
    key: "pink.collections.header-eyebrow",
    label: "Header Eyebrow",
    description: "Small label above the collections heading.",
    type: "text",
    page: "collections",
    group: "collections.header",
    gridColumn: "col-span-1",
    defaultValue: "Bodies of work",
  },
  {
    key: "pink.collections.header-heading",
    label: "Header Heading",
    description: "The main H1 on the collections index.",
    type: "text",
    page: "collections",
    group: "collections.header",
    gridColumn: "col-span-1",
    defaultValue: "Every series, gathered.",
  },
  {
    key: "pink.collections.header-intro",
    label: "Header Intro",
    description: "Shown in the right column of the header, beside the heading.",
    type: "textarea",
    page: "collections",
    group: "collections.header",
    gridColumn: "col-span-full",
    defaultValue:
      "Pieces get grouped by what they're for and when they were made. Some are still open. Some are closed for good.",
  },

  // ── collections.featured (index) ────────────────────────────────────────
  {
    key: "pink.collections.featured-badge",
    label: "Featured Card Badge",
    description: "Corner badge on the featured collection card.",
    type: "text",
    page: "collections",
    group: "collections.featured",
    gridColumn: "col-span-1",
    defaultValue: "Featured",
  },
  {
    key: "pink.collections.featured-cta-label",
    label: "Featured Card Link Text",
    description: "Link to the featured collection.",
    type: "text",
    page: "collections",
    group: "collections.featured",
    gridColumn: "col-span-1",
    defaultValue: "See the series →",
  },

  // ── collections.grid (index) ────────────────────────────────────────────
  {
    key: "pink.collections.grid-badge-open",
    label: "Grid Badge — Open",
    description: "Status badge on cards for collections still being added to.",
    type: "text",
    page: "collections",
    group: "collections.grid",
    gridColumn: "col-span-1",
    defaultValue: "Open",
  },
  {
    key: "pink.collections.grid-badge-closed",
    label: "Grid Badge — Closed",
    description: "Status badge on cards for unpublished-going-forward collections.",
    type: "text",
    page: "collections",
    group: "collections.grid",
    gridColumn: "col-span-1",
    defaultValue: "Closed",
  },

  // ── collections.next (index) ────────────────────────────────────────────
  {
    key: "pink.collections.next-eyebrow",
    label: "Next Series Eyebrow",
    type: "text",
    page: "collections",
    group: "collections.next",
    gridColumn: "col-span-1",
    description: "Small label above the closing-band heading.",
    defaultValue: "What's coming",
  },
  {
    key: "pink.collections.next-heading",
    label: "Next Series Heading",
    type: "text",
    page: "collections",
    group: "collections.next",
    gridColumn: "col-span-1",
    description: "Heading in the closing ink band.",
    defaultValue: "The next series starts soon.",
  },
  {
    key: "pink.collections.next-body",
    label: "Next Series Body",
    type: "textarea",
    page: "collections",
    group: "collections.next",
    gridColumn: "col-span-full",
    description: "One or two sentences under the closing-band heading.",
    defaultValue:
      "Sign up to hear when new work goes up, or get in touch about a custom piece.",
  },
  {
    key: "pink.collections.next-cta-primary-label",
    label: "Primary Button Text",
    type: "text",
    page: "collections",
    group: "collections.next",
    gridColumn: "col-span-1",
    description: "Leave blank to hide the button.",
    defaultValue: "Get in touch",
  },
  {
    key: "pink.collections.next-cta-primary-href",
    label: "Primary Button Link",
    type: "url",
    page: "collections",
    group: "collections.next",
    gridColumn: "col-span-1",
    description: "Where the primary button goes.",
    defaultValue: "/contact",
  },
  {
    key: "pink.collections.next-cta-secondary-label",
    label: "Secondary Button Text",
    type: "text",
    page: "collections",
    group: "collections.next",
    gridColumn: "col-span-1",
    description: "Leave blank to hide the button.",
    defaultValue: "See the shop",
  },
  {
    key: "pink.collections.next-cta-secondary-href",
    label: "Secondary Button Link",
    type: "url",
    page: "collections",
    group: "collections.next",
    gridColumn: "col-span-1",
    description: "Where the secondary button goes.",
    defaultValue: "/shop",
  },
  {
    key: "pink.collections.next-image-1",
    label: "Closing Band Image 1",
    type: "image",
    page: "collections",
    group: "collections.next",
    gridColumn: "col-span-1",
    description: "Left image of the 2-up pair.",
    // Empty on purpose — the pair sits on a dark band.
    defaultValue: "",
  },
  {
    key: "pink.collections.next-image-2",
    label: "Closing Band Image 2",
    type: "image",
    page: "collections",
    group: "collections.next",
    gridColumn: "col-span-1",
    description: "Right image of the 2-up pair.",
    // Empty on purpose — the pair sits on a dark band.
    defaultValue: "",
  },

  // ── collections.detail-hero (detail) ────────────────────────────────────
  {
    key: "pink.collections.detail-hero-eyebrow-prefix",
    label: "Detail Hero Eyebrow Prefix",
    type: "text",
    page: "collections",
    group: "collections.detail-hero",
    gridColumn: "col-span-1",
    description: "Prefix word before the series number and year, e.g. 'Series'.",
    defaultValue: "Series",
  },
  {
    key: "pink.collections.detail-hero-fact-pieces-label",
    label: "Fact Row — Pieces Label",
    type: "text",
    page: "collections",
    group: "collections.detail-hero",
    gridColumn: "col-span-1",
    description: "Label for the piece-count fact row.",
    defaultValue: "Pieces",
  },
  {
    key: "pink.collections.detail-hero-fact-available-label",
    label: "Fact Row — Available Label",
    type: "text",
    page: "collections",
    group: "collections.detail-hero",
    gridColumn: "col-span-1",
    description: "Label for the available-count fact row.",
    defaultValue: "Available",
  },
  {
    key: "pink.collections.detail-hero-fact-price-label",
    label: "Fact Row — From-Price Label",
    type: "text",
    page: "collections",
    group: "collections.detail-hero",
    gridColumn: "col-span-1",
    description: "Label for the starting-price fact row.",
    defaultValue: "From",
  },

  // ── collections.detail-intro (detail) ───────────────────────────────────
  {
    key: "pink.collections.detail-intro-eyebrow",
    label: "Detail Intro Eyebrow",
    type: "text",
    page: "collections",
    group: "collections.detail-intro",
    gridColumn: "col-span-1",
    description: "Small label above the intro heading.",
    defaultValue: "About this series",
  },
  {
    key: "pink.collections.detail-intro-heading",
    label: "Detail Intro Heading",
    type: "text",
    page: "collections",
    group: "collections.detail-intro",
    gridColumn: "col-span-1",
    description: "Heading beside the collection's description.",
    defaultValue: "What holds it together.",
  },

  // ── collections.detail-gallery (detail) ─────────────────────────────────
  {
    key: "pink.collections.detail-gallery-images",
    label: "Detail Gallery Mosaic",
    description:
      "Up to 6 images in the mosaic band on every collection detail page. Leave empty to use the built-in example mosaic.",
    type: "list",
    page: "collections",
    group: "collections.detail-gallery",
    gridColumn: "col-span-full",
    maxItems: 6,
    itemSchema: [
      { key: "image", label: "Image", type: "image" },
      { key: "colSpan", label: "Column Span (1–4)", type: "text", placeholder: "1" },
      { key: "rowSpan", label: "Row Span (1–2)", type: "text", placeholder: "1" },
    ],
  },

  // ── collections.detail-grid (detail) ────────────────────────────────────
  {
    key: "pink.collections.detail-grid-heading-prefix",
    label: "Detail Grid Heading Prefix",
    description: "Prefix word before the piece count, e.g. 'The' → 'The 12'.",
    type: "text",
    page: "collections",
    group: "collections.detail-grid",
    gridColumn: "col-span-1",
    defaultValue: "The",
  },
  {
    key: "pink.collections.detail-grid-filter-all",
    label: "Filter Chip — All",
    type: "text",
    page: "collections",
    group: "collections.detail-grid",
    gridColumn: "col-span-1",
    description: "Filter chip label for showing every piece in the collection.",
    defaultValue: "All",
  },
  {
    key: "pink.collections.detail-grid-filter-available",
    label: "Filter Chip — Available",
    type: "text",
    page: "collections",
    group: "collections.detail-grid",
    gridColumn: "col-span-1",
    description: "Filter chip label for showing only in-stock pieces.",
    defaultValue: "Available",
  },
  {
    key: "pink.collections.detail-grid-filter-archive",
    label: "Filter Chip — Archive",
    type: "text",
    page: "collections",
    group: "collections.detail-grid",
    gridColumn: "col-span-1",
    description: "Filter chip label for showing only sold pieces.",
    defaultValue: "Archive",
  },
  {
    key: "pink.collections.detail-grid-sold-label",
    label: "Sold Price Label",
    description: "Shown in place of a price on sold-out pieces.",
    type: "text",
    page: "collections",
    group: "collections.detail-grid",
    gridColumn: "col-span-1",
    defaultValue: "Sold",
  },
  {
    key: "pink.collections.detail-grid-sold-badge",
    label: "Sold Badge Text",
    description: "Corner badge on sold-out pieces.",
    type: "text",
    page: "collections",
    group: "collections.detail-grid",
    gridColumn: "col-span-1",
    defaultValue: "Rehomed",
  },
  {
    key: "pink.collections.detail-grid-sold-cta",
    label: "Sold Piece Button Text",
    description: "Disabled button shown on sold-out pieces.",
    type: "text",
    page: "collections",
    group: "collections.detail-grid",
    gridColumn: "col-span-1",
    defaultValue: "Ask for a commission",
  },

  // ── collections.detail-nav (detail) ─────────────────────────────────────
  {
    key: "pink.collections.detail-nav-prev-label",
    label: "Previous Series Label",
    type: "text",
    page: "collections",
    group: "collections.detail-nav",
    gridColumn: "col-span-1",
    description: "Label on the previous-collection card.",
    defaultValue: "Previous series",
  },
  {
    key: "pink.collections.detail-nav-next-label",
    label: "Next Series Label",
    type: "text",
    page: "collections",
    group: "collections.detail-nav",
    gridColumn: "col-span-1",
    description: "Label on the next-collection card.",
    defaultValue: "Next series",
  },
];

export const pinkCollectionsFieldGroups: TemplateFieldGroup[] = [
  {
    id: "collections.header",
    title: "Collections — Header",
    description: "Eyebrow, heading and intro at the top of the collections index",
    icon: "🗂️",
    columns: 2,
  } satisfies TemplateFieldGroup,
  {
    id: "collections.featured",
    title: "Collections — Featured Card",
    description: "Badge and link text on the featured collection card",
    icon: "⭐",
    columns: 2,
  } satisfies TemplateFieldGroup,
  {
    id: "collections.grid",
    title: "Collections — Grid Badges",
    description: "Open/closed status badge text",
    icon: "🧩",
    columns: 2,
  } satisfies TemplateFieldGroup,
  {
    id: "collections.next",
    title: "Collections — Closing Band",
    description: "The ink band at the bottom of the collections index",
    icon: "🔮",
    columns: 2,
  } satisfies TemplateFieldGroup,
  {
    id: "collections.detail-hero",
    title: "Collection Detail — Hero",
    description: "Eyebrow prefix and fact-row labels on every collection detail page",
    icon: "🖼️",
    columns: 2,
  } satisfies TemplateFieldGroup,
  {
    id: "collections.detail-intro",
    title: "Collection Detail — Intro",
    description: "Eyebrow and heading beside the collection's description",
    icon: "📝",
    columns: 2,
  } satisfies TemplateFieldGroup,
  {
    id: "collections.detail-gallery",
    title: "Collection Detail — Gallery Mosaic",
    description: "The shared image mosaic shown on every collection detail page",
    icon: "🧵",
    columns: 1,
  } satisfies TemplateFieldGroup,
  {
    id: "collections.detail-grid",
    title: "Collection Detail — Piece Grid",
    description: "Heading prefix, filter chips and sold-piece microcopy",
    icon: "🧺",
    columns: 2,
  } satisfies TemplateFieldGroup,
  {
    id: "collections.detail-nav",
    title: "Collection Detail — Prev/Next",
    description: "Labels on the previous/next series band",
    icon: "↔️",
    columns: 2,
  } satisfies TemplateFieldGroup,
];

export const pinkCollectionsSections: TemplateSection[] = [
  {
    id: "collections.header",
    page: "collections",
    title: "Collections — Header",
    description: "Eyebrow, heading and intro at the top of the collections index",
    groupIds: ["collections.header"],
    order: 0,
    hideable: false,
  },
  {
    id: "collections.featured",
    page: "collections",
    title: "Collections — Featured Card",
    description: "Featured collection card, sourced from the first collection",
    groupIds: ["collections.featured"],
    order: 1,
    hideable: true,
  },
  {
    id: "collections.grid",
    page: "collections",
    title: "Collections — Grid",
    description: "The full collections grid",
    groupIds: ["collections.grid"],
    order: 2,
    hideable: false,
  },
  {
    id: "collections.next",
    page: "collections",
    title: "Collections — Closing Band",
    description: "Ink band at the bottom of the collections index",
    groupIds: ["collections.next"],
    order: 3,
    hideable: true,
  },
  {
    id: "collections.detail-hero",
    page: "collections",
    title: "Collection Detail — Hero",
    description: "Photo hero with derived fact rows",
    groupIds: ["collections.detail-hero"],
    order: 4,
    hideable: false,
  },
  {
    id: "collections.detail-intro",
    page: "collections",
    title: "Collection Detail — Intro",
    description: "Eyebrow, heading and the collection's own description",
    groupIds: ["collections.detail-intro"],
    order: 5,
    hideable: true,
  },
  {
    id: "collections.detail-gallery",
    page: "collections",
    title: "Collection Detail — Gallery Mosaic",
    description: "Image mosaic band",
    groupIds: ["collections.detail-gallery"],
    order: 6,
    hideable: true,
  },
  {
    id: "collections.detail-grid",
    page: "collections",
    title: "Collection Detail — Piece Grid",
    description: "The collection's products, with filter chips",
    groupIds: ["collections.detail-grid"],
    order: 7,
    hideable: false,
  },
  {
    id: "collections.detail-nav",
    page: "collections",
    title: "Collection Detail — Prev/Next",
    description: "Ink band linking to neighbouring series",
    groupIds: ["collections.detail-nav"],
    order: 8,
    hideable: true,
  },
];
