import type { TemplateField, TemplateFieldGroup } from "~/lib/template-fields";

const aboutHeroData: TemplateField[] = [
  {
    key: "default.about.eyebrow",
    label: "Small label",
    description:
      "Short text above the page heading on the About page. Leave blank to hide.",
    type: "text",
    page: "about",
    group: "about.hero",
    defaultValue: "My story",
    placeholder: "My story",
  },
  {
    key: "default.about.heading",
    label: "Heading",
    description: "Main heading at the top of the About page.",
    type: "text",
    page: "about",
    group: "about.hero",
    gridColumn: "col-span-full",
    defaultValue: "Hi — I'm the one making this.",
    placeholder: "Hi — I'm the one making this.",
  },
  {
    key: "default.about.hero-tagline",
    label: "Intro text",
    description: "Short line below the heading. Leave blank to hide.",
    type: "text",
    page: "about",
    group: "about.hero",
    gridColumn: "col-span-full",
    defaultValue: "A little shop, run by me, from a home studio.",
    placeholder: "One short sentence",
  },
  {
    key: "default.about.hero-image",
    label: "Photo",
    description: "Wide studio or workspace photo shown below the heading.",
    type: "image",
    page: "about",
    group: "about.hero",
    gridColumn: "col-span-full",
    defaultValue: "/placeholder.svg",
  },
];

const aboutBioData: TemplateField[] = [
  {
    key: "default.about.portrait-image",
    label: "Portrait",
    description: "Photo of yourself or your workspace, beside the bio text.",
    type: "image",
    page: "about",
    group: "about.bio",
    gridColumn: "col-span-full",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "default.about.bio-eyebrow",
    label: "Small label",
    description: "Short text above the bio heading. Leave blank to hide.",
    type: "text",
    page: "about",
    group: "about.bio",
    defaultValue: "Nice to meet you",
    placeholder: "Nice to meet you",
  },
  {
    key: "default.about.bio-heading",
    label: "Heading",
    description: "Heading above the bio text.",
    type: "text",
    page: "about",
    group: "about.bio",
    gridColumn: "col-span-full",
    defaultValue: "A few words about me.",
    placeholder: "A few words about me.",
  },
  {
    key: "default.about.story-body",
    label: "Story",
    description:
      "Main bio copy, with formatting. Used instead of the plain paragraphs below when set.",
    type: "richtext",
    page: "about",
    group: "about.bio",
    gridColumn: "col-span-full",
  },
  {
    key: "default.about.paragraph-1",
    label: "First paragraph",
    description: "First paragraph of the bio, used when Story above is empty.",
    type: "textarea",
    page: "about",
    group: "about.bio",
    gridColumn: "col-span-full",
    defaultValue:
      "I started this shop because I wanted to share the things I make. Replace this with your own story — keep it short and honest.",
    placeholder: "Tell your story...",
  },
  {
    key: "default.about.paragraph-2",
    label: "Second paragraph",
    description: "Second paragraph of the bio.",
    type: "textarea",
    page: "about",
    group: "about.bio",
    gridColumn: "col-span-full",
    defaultValue:
      "Mention what you make, what you make it from, and why you started. A paragraph or two is plenty.",
    placeholder: "Continue your story...",
  },
  {
    key: "default.about.paragraph-3",
    label: "Third paragraph",
    description: "Optional third paragraph of the bio. Leave blank to hide.",
    type: "textarea",
    page: "about",
    group: "about.bio",
    gridColumn: "col-span-full",
    defaultValue: "",
    placeholder: "Anything else to add...",
  },
  {
    key: "default.about.signature",
    label: "Signature",
    description: "Signed name shown below the bio. Leave blank to hide.",
    type: "text",
    page: "about",
    group: "about.bio",
    defaultValue: "— Your name",
    placeholder: "— Jane",
  },
];

const aboutPillarsData: TemplateField[] = [
  {
    key: "default.about.pillars-eyebrow",
    label: "Small label",
    description:
      "Short text above the values heading, shown above the three value cards.",
    type: "text",
    page: "about",
    group: "about.pillars",
    defaultValue: "What I care about",
    placeholder: "What I care about",
  },
  {
    key: "default.about.pillars-heading",
    label: "Heading",
    description: "Heading above the three value cards.",
    type: "text",
    page: "about",
    group: "about.pillars",
    gridColumn: "col-span-full",
    defaultValue: "Three things, in order.",
    placeholder: "Three things, in order.",
  },
  {
    key: "default.about.pull-quote",
    label: "Pull quote",
    description:
      "A short, meaningful sentence shown in large type above the value cards. Leave blank to hide.",
    type: "textarea",
    page: "about",
    group: "about.pillars",
    gridColumn: "col-span-full",
    defaultValue:
      "I'm not trying to make a lot of things. I'm trying to make a few good ones, and to send them somewhere they'll be used.",
    placeholder: "A meaningful quote...",
  },
  {
    key: "default.about.pillar-1-title",
    label: "First value heading",
    description: "Heading for the first value card.",
    type: "text",
    page: "about",
    group: "about.pillars",
    gridColumn: "col-span-1",
    defaultValue: "Make it well.",
    placeholder: "Make it well.",
  },
  {
    key: "default.about.pillar-1-desc",
    label: "First value description",
    description: "Short supporting line for the first value card.",
    type: "text",
    page: "about",
    group: "about.pillars",
    gridColumn: "col-span-1",
    defaultValue: "Better materials, fewer shortcuts.",
    placeholder: "Better materials, fewer shortcuts.",
  },
  {
    key: "default.about.pillar-2-title",
    label: "Second value heading",
    description: "Heading for the second value card.",
    type: "text",
    page: "about",
    group: "about.pillars",
    gridColumn: "col-span-1",
    defaultValue: "Price it fairly.",
    placeholder: "Price it fairly.",
  },
  {
    key: "default.about.pillar-2-desc",
    label: "Second value description",
    description: "Short supporting line for the second value card.",
    type: "text",
    page: "about",
    group: "about.pillars",
    gridColumn: "col-span-1",
    defaultValue: "No hidden costs. You can see where the money goes.",
    placeholder: "No hidden costs.",
  },
  {
    key: "default.about.pillar-3-title",
    label: "Third value heading",
    description: "Heading for the third value card.",
    type: "text",
    page: "about",
    group: "about.pillars",
    gridColumn: "col-span-1",
    defaultValue: "Stand behind it.",
    placeholder: "Stand behind it.",
  },
  {
    key: "default.about.pillar-3-desc",
    label: "Third value description",
    description: "Short supporting line for the third value card.",
    type: "text",
    page: "about",
    group: "about.pillars",
    gridColumn: "col-span-1",
    defaultValue: "If something's wrong, write me. I'll make it right.",
    placeholder: "If something's wrong, write me.",
  },
];

const aboutCtaData: TemplateField[] = [
  {
    key: "default.about.cta-eyebrow",
    label: "Small label",
    description:
      "Short text above the heading in the bottom call-to-action strip. Leave blank to hide.",
    type: "text",
    page: "about",
    group: "about.cta",
    defaultValue: "Come say hi",
    placeholder: "Come say hi",
  },
  {
    key: "default.about.cta-heading",
    label: "Heading",
    description: "Heading for the bottom call-to-action strip.",
    type: "text",
    page: "about",
    group: "about.cta",
    gridColumn: "col-span-full",
    defaultValue: "I'd love to hear from you.",
    placeholder: "I'd love to hear from you.",
  },
  {
    key: "default.about.cta-button-text",
    label: "Button text",
    description: "Label on the bottom call-to-action button.",
    type: "text",
    page: "about",
    group: "about.cta",
    defaultValue: "Get in touch",
    placeholder: "Get in touch",
  },
  {
    key: "default.about.cta-button-link",
    label: "Button link",
    description: "Where the bottom button goes, e.g. /contact.",
    type: "url",
    page: "about",
    group: "about.cta",
    defaultValue: "/contact",
    placeholder: "/contact",
  },
];

export const defaultAboutData: TemplateField[] = [
  ...aboutHeroData,
  ...aboutBioData,
  ...aboutPillarsData,
  ...aboutCtaData,
];

export const defaultAboutFieldGroups: TemplateFieldGroup[] = [
  {
    id: "about.hero",
    title: "Hero",
    description: "Page heading, intro text, and wide photo.",
    icon: "📖",
    columns: 2,
  },
  {
    id: "about.bio",
    title: "Bio",
    description: "Portrait, bio text, and signature.",
    icon: "🙋",
    columns: 1,
  },
  {
    id: "about.pillars",
    title: "Values",
    description: "Pull quote and three value cards.",
    icon: "✦",
    columns: 2,
  },
  {
    id: "about.cta",
    title: "Closing banner",
    description: "Bottom banner inviting visitors to get in touch.",
    icon: "💌",
    columns: 2,
  },
];
