import type { TemplateField, TemplateFieldGroup } from "~/lib/template-fields";

const aboutHeroData: TemplateField[] = [
  {
    key: "default.about.eyebrow",
    label: "Page Eyebrow",
    description: "Small label above the page heading",
    type: "text",
    page: "about",
    group: "about.hero",
    defaultValue: "My story",
    placeholder: "My story",
  },
  {
    key: "default.about.heading",
    label: "Page Heading",
    description: "Main heading for the About page",
    type: "text",
    page: "about",
    group: "about.hero",
    gridColumn: "col-span-full",
    defaultValue: "Hi — I'm the one making this.",
    placeholder: "Hi — I'm the one making this.",
  },
  {
    key: "default.about.hero-tagline",
    label: "Hero Tagline",
    description: "Short line below the heading",
    type: "text",
    page: "about",
    group: "about.hero",
    gridColumn: "col-span-full",
    defaultValue: "A little shop, run by me, from a home studio.",
    placeholder: "A little shop, run by me, from a home studio.",
  },
  {
    key: "default.about.hero-image",
    label: "Hero Image",
    description: "Wide studio or workspace photo shown below the heading",
    type: "image",
    page: "about",
    group: "about.hero",
    gridColumn: "col-span-full",
    defaultValue: "/placeholder.svg",
  },
];

const aboutBioData: TemplateField[] = [
  {
    key: "default.about.portrait-image",
    label: "Portrait Image",
    description: "Photo of yourself or your workspace",
    type: "image",
    page: "about",
    group: "about.bio",
    gridColumn: "col-span-full",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "default.about.bio-eyebrow",
    label: "Bio Eyebrow",
    description: "Small label above the bio heading",
    type: "text",
    page: "about",
    group: "about.bio",
    defaultValue: "Nice to meet you",
    placeholder: "Nice to meet you",
  },
  {
    key: "default.about.bio-heading",
    label: "Bio Heading",
    description: "Heading for the maker bio section",
    type: "text",
    page: "about",
    group: "about.bio",
    gridColumn: "col-span-full",
    defaultValue: "A few words about me.",
    placeholder: "A few words about me.",
  },
  {
    key: "default.about.story-body",
    label: "Story (rich text)",
    description: "Main body copy — supports formatting. Used when set.",
    type: "richtext",
    page: "about",
    group: "about.bio",
    gridColumn: "col-span-full",
  },
  {
    key: "default.about.paragraph-1",
    label: "Bio Paragraph 1",
    description: "First paragraph (used when rich text is empty)",
    type: "textarea",
    page: "about",
    group: "about.bio",
    gridColumn: "col-span-full",
    defaultValue:
      "I started this shop because I wanted to share the things I make. Replace this with your own story — keep it short and honest.",
    placeholder: "Tell your story...",
  },
  {
    key: "default.about.paragraph-2",
    label: "Bio Paragraph 2",
    description: "Second paragraph",
    type: "textarea",
    page: "about",
    group: "about.bio",
    gridColumn: "col-span-full",
    defaultValue:
      "Mention what you make, what you make it from, and why you started. A paragraph or two is plenty.",
    placeholder: "Continue your story...",
  },
  {
    key: "default.about.paragraph-3",
    label: "Bio Paragraph 3",
    description: "Third paragraph (optional)",
    type: "textarea",
    page: "about",
    group: "about.bio",
    gridColumn: "col-span-full",
    defaultValue: "",
    placeholder: "Anything else to add...",
  },
  {
    key: "default.about.signature",
    label: "Signature",
    description: "Signed name shown below the bio",
    type: "text",
    page: "about",
    group: "about.bio",
    defaultValue: "— Your name",
    placeholder: "— Jane",
  },
];

const aboutPillarsData: TemplateField[] = [
  {
    key: "default.about.pull-quote",
    label: "Pull Quote",
    description: "A short, meaningful sentence displayed in large type",
    type: "textarea",
    page: "about",
    group: "about.pillars",
    gridColumn: "col-span-full",
    defaultValue:
      "I'm not trying to make a lot of things. I'm trying to make a few good ones, and to send them somewhere they'll be used.",
    placeholder: "A meaningful quote...",
  },
  {
    key: "default.about.pillar-1-title",
    label: "Pillar 1 — Title",
    description: "First value / pillar heading",
    type: "text",
    page: "about",
    group: "about.pillars",
    gridColumn: "col-span-1",
    defaultValue: "Make it well.",
    placeholder: "Make it well.",
  },
  {
    key: "default.about.pillar-1-desc",
    label: "Pillar 1 — Description",
    description: "Short supporting sentence for the first pillar",
    type: "text",
    page: "about",
    group: "about.pillars",
    gridColumn: "col-span-1",
    defaultValue: "Better materials, fewer shortcuts.",
    placeholder: "Better materials, fewer shortcuts.",
  },
  {
    key: "default.about.pillar-2-title",
    label: "Pillar 2 — Title",
    description: "Second value / pillar heading",
    type: "text",
    page: "about",
    group: "about.pillars",
    gridColumn: "col-span-1",
    defaultValue: "Price it fairly.",
    placeholder: "Price it fairly.",
  },
  {
    key: "default.about.pillar-2-desc",
    label: "Pillar 2 — Description",
    description: "Short supporting sentence for the second pillar",
    type: "text",
    page: "about",
    group: "about.pillars",
    gridColumn: "col-span-1",
    defaultValue: "No hidden costs. You can see where the money goes.",
    placeholder: "No hidden costs.",
  },
  {
    key: "default.about.pillar-3-title",
    label: "Pillar 3 — Title",
    description: "Third value / pillar heading",
    type: "text",
    page: "about",
    group: "about.pillars",
    gridColumn: "col-span-1",
    defaultValue: "Stand behind it.",
    placeholder: "Stand behind it.",
  },
  {
    key: "default.about.pillar-3-desc",
    label: "Pillar 3 — Description",
    description: "Short supporting sentence for the third pillar",
    type: "text",
    page: "about",
    group: "about.pillars",
    gridColumn: "col-span-1",
    defaultValue: "If something's wrong, write me. I'll make it right.",
    placeholder: "If something's wrong, write me.",
  },
];

const aboutCtaData: TemplateField[] = [
  {
    key: "default.about.cta-eyebrow",
    label: "CTA Eyebrow",
    description: "Small label above the CTA heading",
    type: "text",
    page: "about",
    group: "about.cta",
    defaultValue: "Come say hi",
    placeholder: "Come say hi",
  },
  {
    key: "default.about.cta-heading",
    label: "CTA Heading",
    description: "Heading for the bottom call-to-action strip",
    type: "text",
    page: "about",
    group: "about.cta",
    gridColumn: "col-span-full",
    defaultValue: "I'd love to hear from you.",
    placeholder: "I'd love to hear from you.",
  },
  {
    key: "default.about.cta-button-text",
    label: "CTA Button Text",
    description: "Label for the CTA button",
    type: "text",
    page: "about",
    group: "about.cta",
    defaultValue: "Get in touch",
    placeholder: "Get in touch",
  },
  {
    key: "default.about.cta-button-link",
    label: "CTA Button Link",
    description: "Where the CTA button points",
    type: "url",
    page: "about",
    group: "about.cta",
    defaultValue: "/contact",
    placeholder: "/contact",
  },
];

export const defaultAboutData: TemplateField[] = [
  ...aboutHeroData,
  ...aboutBioData,
  ...aboutPillarsData,
  ...aboutCtaData,
];

export const defaultAboutFieldGroups: TemplateFieldGroup[] = [
  {
    id: "about.hero",
    title: "About — Hero",
    description: "Page heading, tagline, and wide hero image",
    icon: "📖",
    columns: 2,
  },
  {
    id: "about.bio",
    title: "About — Bio",
    description: "Maker portrait, bio text, and signature",
    icon: "🙋",
    columns: 1,
  },
  {
    id: "about.pillars",
    title: "About — Values",
    description: "Pull quote and three value pillars",
    icon: "✦",
    columns: 2,
  },
  {
    id: "about.cta",
    title: "About — CTA",
    description: "Bottom call-to-action strip",
    icon: "💌",
    columns: 2,
  },
];
