import type { TemplateField, TemplateFieldGroup } from "~/lib/template-fields";

export const elegantAboutFieldGroups: TemplateFieldGroup[] = [
  {
    id: "about.hero",
    title: "Hero",
    description:
      "Heading, subtitle, and full-width image at the top of the about page",
    icon: "🌿",
    columns: 2,
  },
  {
    id: "about.story",
    title: "Story",
    description: "Main story text and image",
    icon: "📖",
    columns: 2,
  },
  {
    id: "about.values",
    title: "Mission & Vision",
    description: "Mission and vision statements",
    icon: "🎯",
    columns: 1,
  },
];

export const elegantAboutData: TemplateField[] = [
  {
    key: "elegant.about.hero-image",
    label: "Image",
    description: "Full-width image at the top of the about page.",
    type: "image",
    page: "about",
    group: "about.hero",
    gridColumn: "col-span-full",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "elegant.about.hero-title",
    label: "Heading",
    description: "Large heading at the top of the about page.",
    type: "text",
    page: "about",
    group: "about.hero",
    defaultValue: "Our Story",
    placeholder: "Our Story",
  },
  {
    key: "elegant.about.hero-subtitle",
    label: "Second line",
    description:
      "Italic line shown under the heading, in the same large type. Leave blank to hide.",
    type: "text",
    page: "about",
    group: "about.hero",
    defaultValue: "",
    placeholder: "Where it all began",
  },
  {
    key: "elegant.about.hero-label",
    label: "Small label",
    description: "Small label above the hero heading. Leave blank to hide.",
    type: "text",
    page: "about",
    group: "about.hero",
    defaultValue: "Our story",
    placeholder: "e.g. Our story",
  },
  {
    key: "elegant.about.story-label",
    label: "Small label",
    description: "Small label above the story heading. Leave blank to hide.",
    type: "text",
    page: "about",
    group: "about.story",
    defaultValue: "The studio",
    placeholder: "e.g. The studio",
  },
  {
    key: "elegant.about.story-heading",
    label: "Heading",
    description: "Heading for the main story section.",
    type: "text",
    page: "about",
    group: "about.story",
    defaultValue: "About Us",
    placeholder: "About Us",
  },
  {
    key: "elegant.about.story-body",
    label: "Body text",
    description: "Main paragraph in the story section. Leave blank to hide.",
    type: "textarea",
    page: "about",
    group: "about.story",
    defaultValue: "",
    placeholder: "Tell your brand's story here...",
  },
  {
    key: "elegant.about.story-image",
    label: "Image",
    description: "Image shown beside the story text.",
    type: "image",
    page: "about",
    group: "about.story",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "elegant.about.story-button-text",
    label: "Button text",
    description: "Button below the story text. Leave blank to hide.",
    type: "text",
    page: "about",
    group: "about.story",
    defaultValue: "Come say hello",
    placeholder: "e.g. Come say hello",
  },
  {
    key: "elegant.about.story-button-link",
    label: "Button link",
    description: "Where the story button sends visitors.",
    type: "url",
    page: "about",
    group: "about.story",
    defaultValue: "/contact",
    placeholder: "/contact",
  },
  {
    key: "elegant.about.mission",
    label: "Mission statement",
    description:
      "Your mission statement, shown in the Mission & Vision section. Leave blank to hide this block.",
    type: "textarea",
    page: "about",
    group: "about.values",
    defaultValue: "",
    placeholder: "Our mission is to...",
  },
  {
    key: "elegant.about.mission-heading",
    label: "Mission label",
    description: "Small label above the mission statement.",
    type: "text",
    page: "about",
    group: "about.values",
    defaultValue: "Mission",
    placeholder: "Mission",
  },
  {
    key: "elegant.about.vision",
    label: "Vision statement",
    description:
      "Your vision statement, shown in the Mission & Vision section. Leave blank to hide this block.",
    type: "textarea",
    page: "about",
    group: "about.values",
    defaultValue: "",
    placeholder: "We envision a world where...",
  },
  {
    key: "elegant.about.vision-heading",
    label: "Vision label",
    description: "Small label above the vision statement.",
    type: "text",
    page: "about",
    group: "about.values",
    defaultValue: "Vision",
    placeholder: "Vision",
  },
];
