import type { TemplateField, TemplateFieldGroup } from "~/lib/template-fields";

export const elegantTestimonialsData: TemplateField[] = [
  {
    key: "elegant.testimonials-page.label",
    label: "Small Label",
    description: "Small label above the page heading.",
    type: "text",
    page: "testimonials",
    group: "testimonials.page",
    gridColumn: "col-span-full",
    defaultValue: "Kind words",
    placeholder: "e.g. Kind words",
  },
  {
    key: "elegant.testimonials-page.heading",
    label: "Heading",
    description: "The plain part of the page heading (e.g. 'In their').",
    type: "text",
    page: "testimonials",
    group: "testimonials.page",
    gridColumn: "col-span-1",
    defaultValue: "In their",
    placeholder: "e.g. In their",
  },
  {
    key: "elegant.testimonials-page.heading-accent",
    label: "Heading, highlighted words",
    description: "Shown in italics after the heading.",
    type: "text",
    page: "testimonials",
    group: "testimonials.page",
    gridColumn: "col-span-1",
    defaultValue: "own words.",
    placeholder: "e.g. own words.",
  },
  {
    key: "elegant.testimonials-page.empty-text",
    label: "Empty State Text",
    description:
      "Shown instead of the review grid when there are no reviews yet.",
    type: "text",
    page: "testimonials",
    group: "testimonials.page",
    gridColumn: "col-span-full",
    defaultValue: "No testimonials yet — check back soon.",
  },
  {
    key: "elegant.testimonials-page.closing-heading",
    label: "Closing Heading",
    description:
      "The plain part of the closing band heading (e.g. 'Want to see for').",
    type: "text",
    page: "testimonials",
    group: "testimonials.page",
    gridColumn: "col-span-1",
    defaultValue: "Want to see for",
    placeholder: "e.g. Want to see for",
  },
  {
    key: "elegant.testimonials-page.closing-heading-accent",
    label: "Closing Heading, highlighted words",
    description: "Shown in italics after the closing heading.",
    type: "text",
    page: "testimonials",
    group: "testimonials.page",
    gridColumn: "col-span-1",
    defaultValue: "yourself?",
    placeholder: "e.g. yourself?",
  },
  {
    key: "elegant.testimonials-page.closing-button",
    label: "Closing Button Text",
    description: "Text for the closing band's shop button.",
    type: "text",
    page: "testimonials",
    group: "testimonials.page",
    gridColumn: "col-span-1",
    defaultValue: "Shop the collection",
    placeholder: "e.g. Shop the collection",
  },
  {
    key: "elegant.testimonials-page.write-review-label",
    label: "Write A Review Link Text",
    description: "Text for the link to the testimonial submission form.",
    type: "text",
    page: "testimonials",
    group: "testimonials.page",
    gridColumn: "col-span-1",
    defaultValue: "Write a review",
    placeholder: "e.g. Write a review",
  },
];

export const elegantTestimonialsFieldGroups: TemplateFieldGroup[] = [
  {
    id: "testimonials.page",
    title: "Testimonials page",
    description: "Heading and closing band copy on the testimonials page.",
    icon: "💬",
    columns: 2,
  },
];
