import type { TemplateField } from "~/lib/template-fields";

const aboutPageData: TemplateField[] = [
  {
    key: "pollen.about.title",
    label: "About Title",
    description: "Title for the about page",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.about.subtitle",
    label: "About Subtitle",
    description: "Subtitle for the about page",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.about.text",
    label: "About Text",
    description: "Text for the about page",
    type: "textarea",
    page: "about",
  },
  {
    key: "pollen.about.image",
    label: "About Image",
    description: "Image for the about page",
    type: "url",
    page: "about",
  },
  {
    key: "pollen.about.team-member-1-name",
    label: "Team Member 1",
    description: "Team member 1 for the about page",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.about.team-member-1-role",
    label: "Team Member 1 Role",
    description: "Role for team member 1",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.about.team-member-1-image",
    label: "Team Member 1 Image",
    description: "Image for team member 1",
    type: "url",
    page: "about",
  },
  {
    key: "pollen.about.team-member-2-name",
    label: "Team Member 2",
    description: "Team member 2 for the about page",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.about.team-member-2-role",
    label: "Team Member 2 Role",
    description: "Role for team member 2",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.about.team-member-2-image",
    label: "Team Member 2 Image",
    description: "Image for team member 2",
    type: "url",
    page: "about",
  },
  {
    key: "pollen.about.team-member-3-name",
    label: "Team Member 3",
    description: "Team member 3 for the about page",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.about.team-member-3-role",
    label: "Team Member 3 Role",
    description: "Role for team member 3",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.about.team-member-3-image",
    label: "Team Member 3 Image",
    description: "Image for team member 3",
    type: "url",
    page: "about",
  },
  {
    key: "pollen.about.cta-header",
    label: "CTA Header",
    description: "Header for the CTA section",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.about.cta-subtitle",
    label: "CTA Subtitle",
    description: "Subtitle for the CTA section",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.about.cta-text",
    label: "CTA Text",
    description: "Text for the CTA section",
    type: "textarea",
    page: "about",
  },
  {
    key: "pollen.about.cta-button-text",
    label: "CTA Button Text",
    description: "Button text for the CTA section",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.about.cta-button-link",
    label: "CTA Button Link",
    description: "Button link for the CTA section",
    type: "url",
    page: "about",
  },
  {
    key: "pollen.about.cta-image",
    label: "CTA Image",
    description: "Image for the CTA section",
    type: "url",
    page: "about",
  },
];

const contactPageData: TemplateField[] = [
  {
    key: "pollen.contact.cta-header",
    label: "CTA Header",
    description: "Header for the CTA section",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.contact.cta-subtitle",
    label: "CTA Subtitle",
    description: "Subtitle for the CTA section",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.contact.cta-text",
    label: "CTA Text",
    description: "Text for the CTA section",
    type: "textarea",
    page: "about",
  },
  {
    key: "pollen.contact.cta-button-text",
    label: "CTA Button Text",
    description: "Button text for the CTA section",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.contact.cta-button-link",
    label: "CTA Button Link",
    description: "Button link for the CTA section",
    type: "url",
    page: "about",
  },
  {
    key: "pollen.contact.cta-image",
    label: "CTA Image",
    description: "Image for the CTA section",
    type: "url",
    page: "about",
  },
];
