import { resolveTemplateFields } from "~/lib/resolve-template-fields";
import type { TemplateField, TemplateFieldGroup } from "~/lib/template-fields";

const globalData: TemplateField[] = [
  {
    key: "pollen.global.cta-image",
    label: "CTA Image",
    description: "Image for the CTA section",
    type: "image",
    page: "global",
    group: "global.cta",
    gridColumn: "col-span-full",
  },
  {
    key: "pollen.global.cta-title",
    label: "CTA Title",
    description: "Title for the CTA section",
    type: "textarea",
    page: "global",
    group: "global.cta",
    gridColumn: "col-span-full",
    defaultValue: "Ready to Get Started?",
    placeholder: "e.g. Ready to Get Started?",
  },
  {
    key: "pollen.global.cta-subtitle",
    label: "CTA Subtitle",
    description: "Subtitle for the CTA section",
    type: "text",
    page: "global",
    group: "global.cta",
    gridColumn: "col-span-full",
    defaultValue: "Let's work together",
    placeholder: "Let's work together",
  },
  {
    key: "pollen.global.cta-text",
    label: "CTA Text",
    description: "Text for the CTA section",
    type: "textarea",
    page: "global",
    group: "global.cta",
    gridColumn: "col-span-full",
    defaultValue: "Reach out and let us know how we can help.",
    placeholder: "A short invitation to get in touch...",
  },
  {
    key: "pollen.global.cta-button-text",
    label: "CTA Button Text",
    description: "Button text for the CTA section",
    type: "text",
    page: "global",
    group: "global.cta",
    gridColumn: "col-span-1",
    defaultValue: "Get in Touch",
    placeholder: "Get in Touch",
  },
  {
    key: "pollen.global.cta-button-link",
    label: "CTA Button Link",
    description: "Button link for the CTA section",
    type: "url",
    page: "global",
    group: "global.cta",
    gridColumn: "col-span-1",
    defaultValue: "/contact",
    placeholder: "/contact",
  },
];

const aboutPageData: TemplateField[] = [
  {
    key: "pollen.about.title",
    label: "About Heading",
    description: "Heading for your top about section",
    type: "text",
    page: "about",
    group: "about.main",
    gridColumn: "col-span-full",
    defaultValue: "Heya!",
    placeholder: "Heya!",
  },
  {
    key: "pollen.about.text",
    label: "About Text",
    description: "Text for the about page",
    type: "textarea",
    page: "about",
    group: "about.main",
    gridColumn: "col-span-full",
    defaultValue:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    placeholder: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
  },
  {
    key: "pollen.about.image",
    label: "About Image",
    description: "Image for the about page",
    type: "image",
    group: "about.main",
    gridColumn: "col-span-full",
    page: "about",
  },
];

const aboutOwnerData: TemplateField[] = [
  {
    key: "pollen.about.owner-subheader",
    label: "Owner Section Subheader",
    description:
      "Small label above the owner section (e.g. The Face Behind [Business])",
    type: "text",
    page: "about",
    group: "about.owner",
    gridColumn: "col-span-full",
    defaultValue: "The Face Behind the Business",
    placeholder: "The Face Behind [Business]",
  },
  {
    key: "pollen.about.owner-heading",
    label: "Owner Section Heading",
    description: "Heading for the owner section (e.g. Meet [Name])",
    type: "text",
    page: "about",
    group: "about.owner",
    gridColumn: "col-span-full",
    defaultValue: "Meet the Owner",
    placeholder: "Meet the Owner",
  },
  {
    key: "pollen.about.owner-name",
    label: "Owner Name",
    description: "Name of the featured owner",
    type: "text",
    page: "about",
    group: "about.owner",
    gridColumn: "col-span-1",
    defaultValue: "Jane Smith",
    placeholder: "Jane Smith",
  },
  {
    key: "pollen.about.owner-role",
    label: "Owner Role",
    description: "Title or role (e.g. Owner, Founder)",
    type: "text",
    page: "about",
    group: "about.owner",
    gridColumn: "col-span-1",
    defaultValue: "Owner",
    placeholder: "Owner",
  },
  {
    key: "pollen.about.owner-image",
    label: "Owner Image",
    description: "Photo of the owner",
    type: "image",
    page: "about",
    group: "about.owner",
    gridColumn: "col-span-full",
  },
  {
    key: "pollen.about.owner-blurb",
    label: "Owner Bio",
    description: "Short bio or blurb about who they are",
    type: "textarea",
    page: "about",
    group: "about.owner",
    gridColumn: "col-span-full",
    defaultValue: "A few sentences about the owner and their story.",
    placeholder: "A few sentences about the owner and their story.",
  },
];

const contactPageData: TemplateField[] = [
  {
    key: "pollen.contact.form-title",
    label: "Form Title",
    description: "Title for the contact form",
    type: "text",
    page: "contact",
    group: "contact.main",
    gridColumn: "col-span-full",
    defaultValue: "Send us a message",
    placeholder: "Send Us a Message",
  },
  {
    key: "pollen.contact.form-description",
    label: "Form Description",
    description: "Description for the contact form",
    type: "textarea",
    page: "contact",
    group: "contact.main",
    gridColumn: "col-span-full",
    defaultValue: "We'd love to hear from you!",
    placeholder: "We'll get back to you as soon as possible.",
  },
  {
    key: "pollen.contact.form-image",
    label: "Form Image",
    description: "Image for the contact form",
    type: "image",
    page: "contact",
    group: "contact.main",
    gridColumn: "col-span-full",
  },
];

const homepageData: TemplateField[] = [
  {
    key: "pollen.homepage.hero-image",
    label: "Hero Image",
    description: "Image for the hero section",
    type: "image",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
  },
  {
    key: "pollen.homepage.hero-title",
    label: "Hero Title",
    description: "Title for the hero section",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Welcome to Our Store",
    placeholder: "Welcome to Our Store",
  },
  {
    key: "pollen.homepage.hero-subtitle",
    label: "Hero Subtitle",
    description: "Subtitle for the hero section",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Discover our amazing products",
    placeholder: "Discover our amazing products...",
  },
  {
    key: "pollen.homepage.hero-description-text",
    label: "Hero Description Text",
    description: "Description text for the hero section",
    type: "textarea",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
    defaultValue:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    placeholder:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    key: "pollen.homepage.hero-button-text",
    label: "Hero Button Text",
    description: "Button text for the hero section",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Get in Touch",
    placeholder: "Call to Action",
  },
  {
    key: "pollen.homepage.hero-button-link",
    label: "Hero Button Link",
    description: "Button link for the hero section",
    type: "url",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "/contact",
    placeholder: "/contact",
  },
];

const homepageServicesData: TemplateField[] = [
  {
    key: "pollen.homepage.about-service-title",
    label: "Service Section Heading",
    description: "Heading for the service section",
    type: "text",
    page: "homepage",
    group: "homepage.services",
    gridColumn: "col-span-1",
    defaultValue: "About Our Services",
    placeholder: "About Our Services",
  },
  {
    key: "pollen.homepage.about-service-description",
    label: "Service Section Description",
    description: "Description for the service section",
    type: "textarea",
    page: "homepage",
    group: "homepage.services",
    gridColumn: "col-span-1",
    defaultValue: "We offer a range of services tailored to your needs.",
    placeholder: "Our services are ...",
  },
  {
    key: "pollen.homepage.about-service-title-1",
    label: "Service 1 Title",
    description: "",
    type: "text",
    page: "homepage",
    group: "homepage.services",
    defaultValue: "Service One",
    placeholder: "e.g. Landscaping",
  },
  {
    key: "pollen.homepage.about-service-description-1",
    label: "Service 1 Description",
    description: "",
    type: "textarea",
    page: "homepage",
    group: "homepage.services",
    defaultValue: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    placeholder: "Brief description of this service...",
  },
  {
    key: "pollen.homepage.about-service-title-2",
    label: "Service 2 Title",
    description: "",
    type: "text",
    page: "homepage",
    group: "homepage.services",
    defaultValue: "Service Two",
    placeholder: "e.g. Pest Control",
  },
  {
    key: "pollen.homepage.about-service-description-2",
    label: "Service 2 Description",
    description: "",
    type: "textarea",
    page: "homepage",
    group: "homepage.services",
    defaultValue: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    placeholder: "Brief description of this service...",
  },
  {
    key: "pollen.homepage.about-service-title-3",
    label: "Service 3 Title",
    description: "",
    type: "text",
    page: "homepage",
    group: "homepage.services",
    defaultValue: "Service Three",
    placeholder: "e.g. Irrigation",
  },
  {
    key: "pollen.homepage.about-service-description-3",
    label: "Service 3 Description",
    description: "",
    type: "textarea",
    page: "homepage",
    group: "homepage.services",
    defaultValue: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    placeholder: "Brief description of this service...",
  },
  {
    key: "pollen.homepage.about-service-title-4",
    label: "Service 4 Title",
    description: "",
    type: "text",
    page: "homepage",
    group: "homepage.services",
    defaultValue: "Service Four",
    placeholder: "e.g. Consulting",
  },
  {
    key: "pollen.homepage.about-service-description-4",
    label: "Service 4 Description",
    description: "",
    type: "textarea",
    page: "homepage",
    group: "homepage.services",
    defaultValue: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    placeholder: "Brief description of this service...",
  },
];
const servicesPageData: TemplateField[] = [
  {
    key: "pollen.services.title",
    label: "Services Title",
    description: "Title for the services page",
    type: "text",
    page: "products",
    group: "products.main",
    gridColumn: "col-span-1",
    defaultValue: "About Our Services",
    placeholder: "Our Services",
  },
  {
    key: "pollen.services.subtitle",
    label: "Services Subtitle",
    description: "Subtitle for the services page",
    type: "text",
    page: "products",
    group: "products.main",
    gridColumn: "col-span-1",
    defaultValue: "What We Do",
    placeholder: "What We Do",
  },
  {
    key: "pollen.services.text",
    label: "Services Text",
    description: "Text for the services page",
    type: "textarea",
    page: "products",
    group: "products.main",
    gridColumn: "col-span-full",
    defaultValue:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    placeholder:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
];

const servicesExpandedPageData: TemplateField[] = [
  {
    key: "pollen.services.service-1-name",
    label: "Business Service 1 Name",
    description: "",
    type: "text",
    page: "products",
    group: "products.services-expanded",
    gridColumn: "col-span-full",
    defaultValue: "Service One",
    placeholder: "e.g. Landscaping",
  },
  {
    key: "pollen.services.service-1-description",
    label: "Business Service 1 Description",
    description: "",
    type: "textarea",
    page: "products",
    group: "products.services-expanded",
    gridColumn: "col-span-full",
    defaultValue:
      "We offer a wide range of services to meet your needs. Contact us to learn more.",
    placeholder:
      "e.g. We offer a wide range of gardening services to meet your needs.",
  },
  {
    key: "pollen.services.service-2-name",
    label: "Business Service 2 Name",
    description: "",
    type: "text",
    page: "products",
    group: "products.services-expanded",
    gridColumn: "col-span-full",
    defaultValue: "Service Two",
    placeholder: "e.g. Pest Control",
  },
  {
    key: "pollen.services.service-2-description",
    label: "Business Service 2 Description",
    description: "",
    type: "textarea",
    page: "products",
    group: "products.services-expanded",
    gridColumn: "col-span-full",
    defaultValue:
      "We offer a wide range of services to meet your needs. Contact us to learn more.",
    placeholder:
      "e.g. We offer a wide range of pest control services to meet your needs.",
  },
  {
    key: "pollen.services.service-3-name",
    label: "Business Service 3 Name",
    description: "",
    type: "text",
    page: "products",
    group: "products.services-expanded",
    gridColumn: "col-span-full",
    defaultValue: "Service Three",
    placeholder: "e.g. Irrigation",
  },
  {
    key: "pollen.services.service-3-description",
    label: "Business Service 3 Description",
    description: "",
    type: "textarea",
    page: "products",
    group: "products.services-expanded",
    gridColumn: "col-span-full",
    defaultValue:
      "We offer a wide range of services to meet your needs. Contact us to learn more.",
    placeholder:
      "e.g. We offer a wide range of irrigation services to meet your needs.",
  },
  {
    key: "pollen.services.service-4-name",
    label: "Business Service 4 Name",
    description: "",
    type: "text",
    page: "products",
    group: "products.services-expanded",
    gridColumn: "col-span-full",
    defaultValue: "Service Four",
    placeholder: "e.g. Consulting",
  },
  {
    key: "pollen.services.service-4-description",
    label: "Business Service 4 Description",
    description: "",
    type: "textarea",
    page: "products",
    group: "products.services-expanded",
    gridColumn: "col-span-full",
    defaultValue:
      "We offer a wide range of services to meet your needs. Contact us to learn more.",
    placeholder:
      "e.g. We offer a wide range of consulting services to meet your needs.",
  },
];

const servicesQuestionsData: TemplateField[] = [
  {
    key: "pollen.services.faq-description",
    label: "FAQ Section Description",
    description: "Quick little blurb explaining the importance of the FAQs",
    type: "textarea",
    page: "products",
    group: "products.faq",
    gridColumn: "col-span-full",
    defaultValue:
      "Have questions? We have answers. Browse our most frequently asked questions below.",
    placeholder:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    key: "pollen.services.faq-image",
    label: "FAQ Section Image",
    description: "Image for the FAQ section",
    type: "image",
    page: "products",
    group: "products.faq",
    gridColumn: "col-span-full",
  },
  {
    key: "pollen.services.faq-question-1",
    label: "Question 1",
    description: "",
    type: "text",
    page: "products",
    group: "products.faq",
    gridColumn: "col-span-1",
    defaultValue: "How do I get started?",
    placeholder: "What is your return policy?",
  },
  {
    key: "pollen.services.faq-answer-1",
    label: "Answer 1",
    description: "",
    type: "textarea",
    page: "products",
    group: "products.faq",
    gridColumn: "col-span-full",
    defaultValue:
      "Simply reach out through our contact form and we'll get back to you within one business day.",
    placeholder: "We offer a 30-day return policy...",
  },
  {
    key: "pollen.services.faq-question-2",
    label: "Question 2",
    description: "",
    type: "text",
    page: "products",
    group: "products.faq",
    gridColumn: "col-span-1",
    defaultValue: "What areas do you serve?",
    placeholder: "How long does shipping take?",
  },
  {
    key: "pollen.services.faq-answer-2",
    label: "Answer 2",
    description: "",
    type: "textarea",
    page: "products",
    group: "products.faq",
    gridColumn: "col-span-full",
    defaultValue:
      "We serve clients locally and remotely. Contact us to confirm availability in your area.",
    placeholder: "Standard shipping takes 5-7 business days...",
  },
  {
    key: "pollen.services.faq-question-3",
    label: "Question 3",
    description: "",
    type: "text",
    page: "products",
    group: "products.faq",
    gridColumn: "col-span-1",
    defaultValue: "Do you offer free consultations?",
    placeholder: "What is your refund policy?",
  },
  {
    key: "pollen.services.faq-answer-3",
    label: "Answer 3",
    description: "",
    type: "textarea",
    page: "products",
    group: "products.faq",
    gridColumn: "col-span-full",
    defaultValue:
      "Yes! We offer a free 30-minute consultation to discuss your needs and how we can help.",
    placeholder: "We offer a 30-day refund policy...",
  },
];

const servicesResourcesData: TemplateField[] = [
  {
    key: "pollen.services.resources-title",
    label: "Section Heading",
    description:
      "Heading for the helpful resources section (e.g. Helpful Resources)",
    type: "text",
    page: "products",
    group: "products.resources",
    gridColumn: "col-span-full",
    defaultValue: "Helpful Resources",
    placeholder: "Helpful Resources",
  },
  {
    key: "pollen.services.resource-name-1",
    label: "Resource 1 Name",
    description: "Display name for the first resource",
    type: "text",
    page: "products",
    group: "products.resources",
    gridColumn: "col-span-1",
    placeholder: "Resource name",
  },
  {
    key: "pollen.services.resource-link-1",
    label: "Resource 1 Link",
    description: "URL for the first resource",
    type: "url",
    page: "products",
    group: "products.resources",
    gridColumn: "col-span-1",
    placeholder: "https://...",
  },
  {
    key: "pollen.services.resource-name-2",
    label: "Resource 2 Name",
    description: "Display name for the second resource",
    type: "text",
    page: "products",
    group: "products.resources",
    gridColumn: "col-span-1",
    placeholder: "Resource name",
  },
  {
    key: "pollen.services.resource-link-2",
    label: "Resource 2 Link",
    description: "URL for the second resource",
    type: "url",
    page: "products",
    group: "products.resources",
    gridColumn: "col-span-1",
    placeholder: "https://...",
  },
  {
    key: "pollen.services.resource-name-3",
    label: "Resource 3 Name",
    description: "Display name for the third resource",
    type: "text",
    page: "products",
    group: "products.resources",
    gridColumn: "col-span-1",
    placeholder: "Resource name",
  },
  {
    key: "pollen.services.resource-link-3",
    label: "Resource 3 Link",
    description: "URL for the third resource",
    type: "url",
    page: "products",
    group: "products.resources",
    gridColumn: "col-span-1",
    placeholder: "https://...",
  },
  {
    key: "pollen.services.resource-name-4",
    label: "Resource 4 Name",
    description: "Display name for the fourth resource",
    type: "text",
    page: "products",
    group: "products.resources",
    gridColumn: "col-span-1",
    placeholder: "Resource name",
  },
  {
    key: "pollen.services.resource-link-4",
    label: "Resource 4 Link",
    description: "URL for the fourth resource",
    type: "url",
    page: "products",
    group: "products.resources",
    gridColumn: "col-span-1",
    placeholder: "https://...",
  },
  {
    key: "pollen.services.resource-name-5",
    label: "Resource 5 Name",
    description: "Display name for the fifth resource",
    type: "text",
    page: "products",
    group: "products.resources",
    gridColumn: "col-span-1",
    placeholder: "Resource name",
  },
  {
    key: "pollen.services.resource-link-5",
    label: "Resource 5 Link",
    description: "URL for the fifth resource",
    type: "url",
    page: "products",
    group: "products.resources",
    gridColumn: "col-span-1",
    placeholder: "https://...",
  },
];

const blogPageData: TemplateField[] = [
  {
    key: "pollen.blog.listing-title",
    label: "Blog listing title",
    description: "Heading shown at the top of the blog index",
    type: "text",
    page: "blog",
    group: "blog.header",
    gridColumn: "col-span-full",
    defaultValue: "Blog",
    placeholder: "Blog",
  },
  {
    key: "pollen.blog.listing-intro",
    label: "Blog listing intro",
    description: "Short text below the blog hero (optional)",
    type: "textarea",
    page: "blog",
    group: "blog.header",
    gridColumn: "col-span-full",
    defaultValue:
      "News, tips, and updates from our team. Use the search box to find a topic.",
    placeholder: "Intro paragraph for your blog...",
  },
  {
    key: "pollen.blog.listing-hero-image",
    label: "Blog listing hero image",
    description:
      "Optional background image for the blog index hero. If empty, the site header background or default image is used.",
    type: "image",
    page: "blog",
    group: "blog.header",
    gridColumn: "col-span-full",
  },
];

const fieldGroups: TemplateFieldGroup[] = [
  {
    id: "homepage.hero",
    title: "Hero Section",
    description: "Main banner area at the top of homepage",
    icon: "🎯",
    columns: 2,
  },
  {
    id: "homepage.services",
    title: "Services Section",
    description: "Services section after the hero section",
    icon: "🎯",
    columns: 1,
  },
  {
    id: "global.contact",
    title: "Contact",
    description:
      "Contact information for your business, displayed throughout the site",
    icon: "🎯",
    columns: 2,
  },
  {
    id: "global.services",
    title: "Services",
    description: "Services for your business, set as 4 services max",
    icon: "🎯",
    columns: 2,
  },
  {
    id: "global.cta",
    title: "Call to Action",
    description:
      "CTA section for your business, displayed at the bottom of the page",
    icon: "🎯",
    columns: 2,
  },

  {
    id: "global.header",
    title: "Header",
    description: "Header displayed on the top of most every page",
    icon: "🎯",
    columns: 2,
  },
  {
    id: "about.main",
    title: "About Us",
    description: "Flush out your about page",
    icon: "📖",
    columns: 2,
  },
  {
    id: "about.owner",
    title: "Owner",
    description: "Featured owner section on the about page (image and bio)",
    icon: "👤",
    columns: 2,
  },
  {
    id: "products.main",
    title: "Services Main",
    description: "Main section for the services page",
    icon: "🎯",
    columns: 2,
  },
  {
    id: "products.faq",
    title: "Frequently Asked Questions",
    description: "FAQs section for the services page",
    icon: "💬",
    columns: 2,
  },
  {
    id: "products.resources",
    title: "Helpful Resources",
    description:
      "Up to 5 free resources (name + link) for clients. Leave name and link blank to hide a slot.",
    icon: "🔗",
    columns: 2,
  },
  {
    id: "products.services-expanded",
    title: "Services Expanded",
    description: "Expanded services section for the services page",
    icon: "🌿",
    columns: 1,
  },
  {
    id: "products.testimonials",
    title: "Services Testimonials",
    description: "Testimonials section for the services page",
    icon: "🎯",
    columns: 2,
  },
  {
    id: "contact.main",
    title: "Contact Form",
    description: "Update the verbiage and image for the contact form",
    icon: "📝",
    columns: 1,
  },
  {
    id: "blog.header",
    title: "Blog",
    description: "Heading, intro, and optional hero image on the blog index",
    icon: "📝",
    columns: 1,
  },
];

export const pollenData = {
  pollen: [
    ...globalData,
    ...aboutPageData,
    ...aboutOwnerData,
    ...contactPageData,
    ...homepageData,
    ...homepageServicesData,
    ...servicesPageData,
    ...servicesQuestionsData,
    ...servicesResourcesData,
    ...servicesExpandedPageData,
    ...blogPageData,
  ],
};

export const pollenFieldGroups = {
  pollen: fieldGroups,
};

const _pollenFieldMap = new Map(
  pollenData.pollen.map((field) => [field.key, field]),
);

export function resolveFields(customFields: unknown, keys: string[]): Record<string, string> {
  return resolveTemplateFields(customFields, keys, _pollenFieldMap);
}
