import type { TemplateField } from "~/lib/template-fields";

const globalData: TemplateField[] = [
  {
    key: "pollen.global.cta-title",
    label: "CTA Title",
    description: "Title for the CTA section",
    type: "textarea",
    page: "global",
  },
  {
    key: "pollen.global.cta-subtitle",
    label: "CTA Subtitle",
    description: "Subtitle for the CTA section",
    type: "text",
    page: "global",
  },
  {
    key: "pollen.global.cta-text",
    label: "CTA Text",
    description: "Text for the CTA section",
    type: "textarea",
    page: "global",
  },
  {
    key: "pollen.global.cta-button-text",
    label: "CTA Button Text",
    description: "Button text for the CTA section",
    type: "text",
    page: "global",
  },
  {
    key: "pollen.global.cta-button-link",
    label: "CTA Button Link",
    description: "Button link for the CTA section",
    type: "url",
    page: "global",
  },
  {
    key: "pollen.global.cta-image",
    label: "CTA Image",
    description: "Image for the CTA section",
    type: "url",
    page: "global",
  },
  {
    key: "pollen.global.about-service-title-1",
    label: "About Service Title 1",
    description: "Title for the about service 1",
    type: "text",
    page: "global",
  },
  {
    key: "pollen.global.about-service-description-1",
    label: "About Service Description 1",
    description: "Description for the about service 1",
    type: "textarea",
    page: "global",
  },
  {
    key: "pollen.global.about-service-title-2",
    label: "About Service Title 2",
    description: "Title for the about service 2",
    type: "text",
    page: "global",
  },
  {
    key: "pollen.global.about-service-description-2",
    label: "About Service Description 2",
    description: "Description for the about service 2",
    type: "textarea",
    page: "global",
  },
  {
    key: "pollen.global.about-service-title-3",
    label: "About Service Title 3",
    description: "Title for the about service 3",
    type: "text",
    page: "global",
  },
  {
    key: "pollen.global.about-service-description-3",
    label: "About Service Description 3",
    description: "Description for the about service 3",
    type: "textarea",
    page: "global",
  },
  {
    key: "pollen.global.about-service-title-4",
    label: "About Service Title 4",
    description: "Title for the about service 4",
    type: "text",
    page: "global",
  },

  {
    key: "pollen.global.about-service-description-4",
    label: "About Service Description 4",
    description: "Description for the about service 4",
    type: "textarea",
    page: "global",
  },
];

const aboutPageData: TemplateField[] = [
  {
    key: "pollen.about.title",
    label: "About Title",
    description: "Title for the about page",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.about.subtitle",
    label: "About Subtitle",
    description: "Subtitle for the about page",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.about.text",
    label: "About Text",
    description: "Text for the about page",
    type: "textarea",
    page: "about",
  },
  {
    key: "pollen.about.image",
    label: "About Image",
    description: "Image for the about page",
    type: "url",
    page: "about",
  },
  {
    key: "pollen.about.staff-subheader",
    label: "Staff Subheader",
    description: "Subheader for the staff section",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.about.staff-header",
    label: "Staff Header",
    description: "Header for the staff section",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.about.team-member-1-name",
    label: "Team Member 1",
    description: "Team member 1 for the about page",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.about.team-member-1-role",
    label: "Team Member 1 Role",
    description: "Role for team member 1",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.about.team-member-1-image",
    label: "Team Member 1 Image",
    description: "Image for team member 1",
    type: "url",
    page: "about",
  },
  {
    key: "pollen.about.team-member-2-name",
    label: "Team Member 2",
    description: "Team member 2 for the about page",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.about.team-member-2-role",
    label: "Team Member 2 Role",
    description: "Role for team member 2",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.about.team-member-2-image",
    label: "Team Member 2 Image",
    description: "Image for team member 2",
    type: "url",
    page: "about",
  },
  {
    key: "pollen.about.team-member-3-name",
    label: "Team Member 3",
    description: "Team member 3 for the about page",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.about.team-member-3-role",
    label: "Team Member 3 Role",
    description: "Role for team member 3",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.about.team-member-3-image",
    label: "Team Member 3 Image",
    description: "Image for team member 3",
    type: "url",
    page: "about",
  },
  {
    key: "pollen.about.cta-header",
    label: "CTA Header",
    description: "Header for the CTA section",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.about.cta-subtitle",
    label: "CTA Subtitle",
    description: "Subtitle for the CTA section",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.about.cta-text",
    label: "CTA Text",
    description: "Text for the CTA section",
    type: "textarea",
    page: "about",
  },
  {
    key: "pollen.about.cta-button-text",
    label: "CTA Button Text",
    description: "Button text for the CTA section",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.about.cta-button-link",
    label: "CTA Button Link",
    description: "Button link for the CTA section",
    type: "url",
    page: "about",
  },
  {
    key: "pollen.about.cta-image",
    label: "CTA Image",
    description: "Image for the CTA section",
    type: "url",
    page: "about",
  },
];

const contactPageData: TemplateField[] = [
  {
    key: "pollen.contact.cta-header",
    label: "CTA Header",
    description: "Header for the CTA section",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.contact.cta-subtitle",
    label: "CTA Subtitle",
    description: "Subtitle for the CTA section",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.contact.cta-text",
    label: "CTA Text",
    description: "Text for the CTA section",
    type: "textarea",
    page: "about",
  },
  {
    key: "pollen.contact.cta-button-text",
    label: "CTA Button Text",
    description: "Button text for the CTA section",
    type: "text",
    page: "about",
  },
  {
    key: "pollen.contact.cta-button-link",
    label: "CTA Button Link",
    description: "Button link for the CTA section",
    type: "url",
    page: "about",
  },
  {
    key: "pollen.contact.cta-image",
    label: "CTA Image",
    description: "Image for the CTA section",
    type: "url",
    page: "about",
  },
];

const homepageData: TemplateField[] = [
  {
    key: "pollen.homepage.hero-image",
    label: "Hero Image",
    description: "Image for the hero section",
    type: "url",
    page: "homepage",
  },
  {
    key: "pollen.homepage.hero-title",
    label: "Hero Title",
    description: "Title for the hero section",
    type: "text",
    page: "homepage",
  },
  {
    key: "pollen.homepage.hero-subtitle",
    label: "Hero Subtitle",
    description: "Subtitle for the hero section",
    type: "text",
    page: "homepage",
  },
  {
    key: "pollen.homepage.hero-description-text",
    label: "Hero Description Text",
    description: "Description text for the hero section",
    type: "textarea",
    page: "homepage",
  },
  {
    key: "pollen.homepage.hero-button-text",
    label: "Hero Button Text",
    description: "Button text for the hero section",
    type: "text",
    page: "homepage",
  },
  {
    key: "pollen.homepage.hero-button-link",
    label: "Hero Button Link",
    description: "Button link for the hero section",
    type: "url",
    page: "homepage",
  },
  {
    key: "pollen.homepage.about-service-title-1",
    label: "About Service Title 1",
    description: "Title for the about service 1",
    type: "text",
    page: "homepage",
  },
  {
    key: "pollen.homepage.about-service-title-2",
    label: "About Service Title 2",
    description: "Title for the about service 2",
    type: "text",
    page: "homepage",
  },
  {
    key: "pollen.homepage.about-service-title-3",
    label: "About Service Title 3",
    description: "Title for the about service 3",
    type: "text",
    page: "homepage",
  },
  {
    key: "pollen.homepage.about-service-title-4",
    label: "About Service Title 4",
    description: "Title for the about service 4",
    type: "text",
    page: "homepage",
  },
  {
    key: "pollen.homepage.about-service-description-1",
    label: "About Service Description 1",
    description: "Description for the about service 1",
    type: "textarea",
    page: "homepage",
  },
  {
    key: "pollen.homepage.about-service-description-2",
    label: "About Service Description 2",
    description: "Description for the about service 2",
    type: "textarea",
    page: "homepage",
  },
  {
    key: "pollen.homepage.about-service-description-3",
    label: "About Service Description 3",
    description: "Description for the about service 3",
    type: "textarea",
    page: "homepage",
  },
  {
    key: "pollen.homepage.about-service-description-4",
    label: "About Service Description 4",
    description: "Description for the about service 4",
    type: "textarea",
    page: "homepage",
  },
  {
    key: "pollen.homepage.about-service-title",
    label: "About Service Title",
    description: "Title for the about service section",
    type: "text",
    page: "homepage",
  },
  {
    key: "pollen.homepage.about-service-description",
    label: "About Service Description",
    description: "Description for the about service section",
    type: "textarea",
    page: "homepage",
  },
];

const servicesPageData: TemplateField[] = [
  {
    key: "pollen.services.title",
    label: "Services Title",
    description: "Title for the services page",
    type: "text",
    page: "products",
  },
  {
    key: "pollen.services.subtitle",
    label: "Services Subtitle",
    description: "Subtitle for the services page",
    type: "text",
    page: "products",
  },
  {
    key: "pollen.services.text",
    label: "Services Text",
    description: "Text for the services page",
    type: "textarea",
    page: "products",
  },
  {
    key: "pollen.services.cta-button-text",
    label: "CTA Button Text",
    description: "Button text for the CTA section",
    type: "text",
    page: "products",
  },
  {
    key: "pollen.services.cta-button-link",
    label: "CTA Button Link",
    description: "Button link for the CTA section",
    type: "url",
    page: "products",
  },
  {
    key: "pollen.services.faq-title",
    label: "FAQ Title",
    description: "Title for the FAQ section",
    type: "text",
    page: "products",
  },
  {
    key: "pollen.services.faq-subtitle",
    label: "FAQ Subtitle",
    description: "Subtitle for the FAQ section",
    type: "text",
    page: "products",
  },
  {
    key: "pollen.services.faq-description",
    label: "FAQ Description",
    description: "Description for the FAQ section",
    type: "textarea",
    page: "products",
  },
  {
    key: "pollen.services.faq-question-1",
    label: "FAQ Question 1",
    description: "Question for the FAQ section",
    type: "text",
    page: "products",
  },
  {
    key: "pollen.services.faq-answer-1",
    label: "FAQ Answer 1",
    description: "Answer for the FAQ section",
    type: "textarea",
    page: "products",
  },
  {
    key: "pollen.services.faq-question-2",
    label: "FAQ Question 2",
    description: "Question for the FAQ section",
    type: "text",
    page: "products",
  },
  {
    key: "pollen.services.faq-answer-2",
    label: "FAQ Answer 2",
    description: "Answer for the FAQ section",
    type: "textarea",
    page: "products",
  },
  {
    key: "pollen.services.faq-question-3",
    label: "FAQ Question 3  ",
    description: "Question for the FAQ section",
    type: "text",
    page: "products",
  },
  {
    key: "pollen.services.faq-answer-3",
    label: "Team Member 3 Image",
    description: "Answer for the FAQ section",
    type: "textarea",
    page: "products",
  },
  {
    key: "pollen.services.testimonial-quote-1",
    label: "Testimonial Quote 1",
    description: "Quote for the testimonial section",
    type: "text",
    page: "products",
  },
  {
    key: "pollen.services.testimonial-author-1",
    label: "Testimonial Author 1",
    description: "Author for the testimonial section",
    type: "text",
    page: "products",
  },
  {
    key: "pollen.services.testimonial-quote-2",
    label: "Testimonial Quote 2",
    description: "Quote for the testimonial section",
    type: "textarea",
    page: "products",
  },
  {
    key: "pollen.services.testimonial-author-2",
    label: "Testimonial Author 2",
    description: "Author for the testimonial section",
    type: "text",
    page: "products",
  },
  {
    key: "pollen.services.testimonial-quote-3",
    label: "Testimonial Quote 3",
    description: "Quote for the testimonial section",
    type: "url",
    page: "products",
  },
  {
    key: "pollen.services.testimonial-author-3",
    label: "Testimonial Author 3",
    description: "Author for the testimonial section",
    type: "url",
    page: "products",
  },
  {
    key: "pollen.services.testimonial-subtitle",
    label: "Testimonial Subtitle",
    description: "Subtitle for the testimonial section",
    type: "text",
    page: "products",
  },
  {
    key: "pollen.services.testimonial-title",
    label: "Testimonial Title",
    description: "Title for the testimonial section",
    type: "text",
    page: "products",
  },
];

export const pollenData = {
  pollen: [
    ...globalData,
    ...aboutPageData,
    ...contactPageData,
    ...homepageData,
    ...servicesPageData,
  ],
};
