import type { TemplateField, TemplateFieldGroup } from "~/lib/template-fields";

const homepageHeroData: TemplateField[] = [
  {
    key: "default.homepage.hero-eyebrow",
    label: "Small label",
    description:
      "Short text above your business name in the hero. Leave blank to hide.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
    defaultValue: "New this season",
    placeholder: "New this season",
  },
  {
    key: "default.homepage.hero-image",
    label: "Background photo",
    description: "Full-width photo behind the hero heading and buttons.",
    type: "image",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "default.homepage.hero-description",
    label: "Intro text",
    description:
      "Line below your business name in the hero. Leave blank to hide.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
    defaultValue: "A simple, ready-to-launch storefront.",
    placeholder: "e.g. A simple, ready-to-launch storefront.",
  },
  {
    key: "default.homepage.hero-button-text",
    label: "Button text",
    description: "Text on the main hero button.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    defaultValue: "Shop the catalog",
    placeholder: "Shop the catalog",
  },
  {
    key: "default.homepage.hero-button-link",
    label: "Button link",
    description: "Where the main hero button goes, e.g. /shop.",
    type: "url",
    page: "homepage",
    group: "homepage.hero",
    defaultValue: "/shop",
    placeholder: "/shop",
  },
  {
    key: "default.homepage.hero-button-2-text",
    label: "Second button text",
    description:
      "Text for the quieter button beside the main one. Leave blank to hide it.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    defaultValue: "Our story",
    placeholder: "Our story",
  },
  {
    key: "default.homepage.hero-button-2-link",
    label: "Second button link",
    description: "Where the second hero button goes, e.g. /about.",
    type: "url",
    page: "homepage",
    group: "homepage.hero",
    defaultValue: "/about",
    placeholder: "/about",
  },
];

const homepageCollectionsData: TemplateField[] = [
  {
    key: "default.homepage.collections-eyebrow",
    label: "Small label",
    description:
      "Short text above the collections heading. Leave blank to hide.",
    type: "text",
    page: "homepage",
    group: "homepage.collections",
    gridColumn: "col-span-full",
    defaultValue: "Shop by collection",
    placeholder: "Shop by collection",
  },
  {
    key: "default.homepage.collections-heading",
    label: "Heading",
    description: "Heading above the collections grid.",
    type: "text",
    page: "homepage",
    group: "homepage.collections",
    gridColumn: "col-span-full",
    defaultValue: "Collections",
    placeholder: "Collections",
  },
  {
    key: "default.homepage.collections-cta-text",
    label: "Link text",
    description:
      "Text for the link to all collections, shown beside the heading.",
    type: "text",
    page: "homepage",
    group: "homepage.collections",
    defaultValue: "View everything",
    placeholder: "View everything",
  },
  {
    key: "default.homepage.collections-cta-link",
    label: "Link",
    description: "Where the collections link goes, e.g. /collections.",
    type: "url",
    page: "homepage",
    group: "homepage.collections",
    defaultValue: "/collections",
    placeholder: "/collections",
  },
];

const homepageRailsData: TemplateField[] = [
  {
    key: "default.homepage.rail-one-collection",
    label: "First rail collection",
    description:
      "Pick a collection for the first product rail. Defaults to featured products when none is chosen.",
    type: "collection",
    page: "homepage",
    group: "homepage.rails",
    gridColumn: "col-span-1",
  },
  {
    key: "default.homepage.rail-one-eyebrow",
    label: "First rail small label",
    description: "Short text above the first rail's heading.",
    type: "text",
    page: "homepage",
    group: "homepage.rails",
    gridColumn: "col-span-1",
    defaultValue: "Featured",
    placeholder: "Featured",
  },
  {
    key: "default.homepage.rail-one-title",
    label: "First rail heading",
    description: "Heading for the first product rail.",
    type: "text",
    page: "homepage",
    group: "homepage.rails",
    gridColumn: "col-span-1",
    defaultValue: "This week's picks.",
    placeholder: "This week's picks.",
  },
  {
    key: "default.homepage.rail-one-button-text",
    label: "First rail button text",
    description: "Label on the link at the end of the first rail.",
    type: "text",
    page: "homepage",
    group: "homepage.rails",
    defaultValue: "All products",
    placeholder: "All products",
  },
  {
    key: "default.homepage.rail-one-button-link",
    label: "First rail button link",
    description:
      "Where the first rail's link goes. Ignored when a collection is picked above — that collection's page is used instead.",
    type: "url",
    page: "homepage",
    group: "homepage.rails",
    defaultValue: "/shop",
    placeholder: "/shop",
  },
  {
    key: "default.homepage.rail-two-collection",
    label: "Second rail collection",
    description:
      "Pick a collection for the second product rail. Defaults to the next featured products when none is chosen.",
    type: "collection",
    page: "homepage",
    group: "homepage.rails",
    gridColumn: "col-span-1",
  },
  {
    key: "default.homepage.rail-two-eyebrow",
    label: "Second rail small label",
    description: "Short text above the second rail's heading.",
    type: "text",
    page: "homepage",
    group: "homepage.rails",
    gridColumn: "col-span-1",
    defaultValue: "Customer favorites",
    placeholder: "Customer favorites",
  },
  {
    key: "default.homepage.rail-two-title",
    label: "Second rail heading",
    description: "Heading for the second product rail.",
    type: "text",
    page: "homepage",
    group: "homepage.rails",
    gridColumn: "col-span-1",
    defaultValue: "What people keep reaching for.",
    placeholder: "What people keep reaching for.",
  },
  {
    key: "default.homepage.rail-two-button-text",
    label: "Second rail button text",
    description: "Label on the link at the end of the second rail.",
    type: "text",
    page: "homepage",
    group: "homepage.rails",
    defaultValue: "Shop bestsellers",
    placeholder: "Shop bestsellers",
  },
  {
    key: "default.homepage.rail-two-button-link",
    label: "Second rail button link",
    description:
      "Where the second rail's link goes. Ignored when a collection is picked above — that collection's page is used instead.",
    type: "url",
    page: "homepage",
    group: "homepage.rails",
    defaultValue: "/shop",
    placeholder: "/shop",
  },
];

const homepageStoryData: TemplateField[] = [
  {
    key: "default.homepage.cta-eyebrow",
    label: "Small label",
    description: "Short text above the story heading. Leave blank to hide.",
    type: "text",
    page: "homepage",
    group: "homepage.story",
    gridColumn: "col-span-full",
    defaultValue: "A note from the maker",
    placeholder: "A note from the maker",
  },
  {
    key: "default.homepage.cta-heading",
    label: "Heading",
    description:
      "Heading for the story section below the product rails. Leave blank to hide it.",
    type: "text",
    page: "homepage",
    group: "homepage.story",
    gridColumn: "col-span-full",
    defaultValue: "Made with care.",
    placeholder: "Made with care.",
  },
  {
    key: "default.homepage.cta-description",
    label: "Body text",
    description:
      "A sentence or two about who you are and why you started, shown below the story heading. Leave blank to hide it.",
    type: "textarea",
    page: "homepage",
    group: "homepage.story",
    gridColumn: "col-span-full",
    defaultValue:
      "Replace this with a sentence or two about who you are and why you started. A little goes a long way.",
    placeholder: "One short sentence",
  },
  {
    key: "default.homepage.cta-image",
    label: "Photo",
    description: "Lifestyle or studio photo shown beside the story text.",
    type: "image",
    page: "homepage",
    group: "homepage.story",
    gridColumn: "col-span-full",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "default.homepage.cta-button-text",
    label: "Button text",
    description: "Text for the link at the end of the story section.",
    type: "text",
    page: "homepage",
    group: "homepage.story",
    defaultValue: "Read more",
    placeholder: "Read more",
  },
  {
    key: "default.homepage.cta-button-link",
    label: "Button link",
    description: "Where the story link goes, e.g. /about.",
    type: "url",
    page: "homepage",
    group: "homepage.story",
    defaultValue: "/about",
    placeholder: "/about",
  },
];

// `testimonial-quote` / `testimonial-author` were retired 2026-09-27: the
// homepage testimonial now shows the latest Admin → Testimonials entry
// (never a template-owned quote — see field-conventions.md "Never duplicate
// Settings data"), falling back to a saved legacy quote/author read directly
// via `getRawCustomFieldString` in `default-homepage.tsx`. Report to
// RETIRED_TEMPLATE_KEYS: "default.homepage.testimonial-quote",
// "default.homepage.testimonial-author".
const homepageTestimonialData: TemplateField[] = [
  {
    key: "default.homepage.testimonial-cta-text",
    label: "Link text",
    description:
      "Text for the link to your full reviews page, shown below the quote. Leave blank to hide.",
    type: "text",
    page: "homepage",
    group: "homepage.testimonial",
    defaultValue: "Read all reviews",
    placeholder: "Read all reviews",
  },
  {
    key: "default.homepage.testimonial-cta-link",
    label: "Link",
    description: "Where the reviews link goes, e.g. /testimonials.",
    type: "url",
    page: "homepage",
    group: "homepage.testimonial",
    defaultValue: "/testimonials",
    placeholder: "/testimonials",
  },
];

const homepagePromiseData: TemplateField[] = [
  {
    key: "default.homepage.promise-1-title",
    label: "First promise heading",
    description: "Heading for the first promise.",
    type: "text",
    page: "homepage",
    group: "homepage.promise",
    gridColumn: "col-span-1",
    defaultValue: "Secure checkout",
    placeholder: "Secure checkout",
  },
  {
    key: "default.homepage.promise-1-desc",
    label: "First promise description",
    description: "Short line below the first promise heading.",
    type: "text",
    page: "homepage",
    group: "homepage.promise",
    gridColumn: "col-span-1",
    defaultValue: "Payments are encrypted and processed securely.",
    placeholder: "One short line",
  },
  {
    key: "default.homepage.promise-2-title",
    label: "Second promise heading",
    description: "Heading for the second promise.",
    type: "text",
    page: "homepage",
    group: "homepage.promise",
    gridColumn: "col-span-1",
    defaultValue: "Delivery options",
    placeholder: "Delivery options",
  },
  {
    key: "default.homepage.promise-2-desc",
    label: "Second promise description",
    description: "Short line below the second promise heading.",
    type: "text",
    page: "homepage",
    group: "homepage.promise",
    gridColumn: "col-span-1",
    defaultValue: "See shipping costs and options at checkout.",
    placeholder: "One short line",
  },
  {
    key: "default.homepage.promise-3-title",
    label: "Third promise heading",
    description: "Heading for the third promise.",
    type: "text",
    page: "homepage",
    group: "homepage.promise",
    gridColumn: "col-span-1",
    defaultValue: "Made with care",
    placeholder: "Made with care",
  },
  {
    key: "default.homepage.promise-3-desc",
    label: "Third promise description",
    description: "Short line below the third promise heading.",
    type: "text",
    page: "homepage",
    group: "homepage.promise",
    gridColumn: "col-span-1",
    defaultValue: "Every order is packed with care.",
    placeholder: "Every order is packed with care.",
  },
  {
    key: "default.homepage.promise-4-title",
    label: "Fourth promise heading",
    description: "Heading for the fourth promise.",
    type: "text",
    page: "homepage",
    group: "homepage.promise",
    gridColumn: "col-span-1",
    defaultValue: "Personal service",
    placeholder: "Personal service",
  },
  {
    key: "default.homepage.promise-4-desc",
    label: "Fourth promise description",
    description: "Short line below the fourth promise heading.",
    type: "text",
    page: "homepage",
    group: "homepage.promise",
    gridColumn: "col-span-1",
    defaultValue: "You'll always reach a real person.",
    placeholder: "You'll always reach a real person.",
  },
];

export const defaultHomepageData: TemplateField[] = [
  ...homepageHeroData,
  ...homepageCollectionsData,
  ...homepageRailsData,
  ...homepageStoryData,
  ...homepageTestimonialData,
  ...homepagePromiseData,
];

export const defaultHomepageFieldGroups: TemplateFieldGroup[] = [
  {
    id: "homepage.hero",
    title: "Hero",
    description: "Main banner at the top of the homepage.",
    icon: "🎯",
    columns: 2,
  },
  {
    id: "homepage.collections",
    title: "Collections grid",
    description: "3-up collection grid below the hero.",
    icon: "🗂️",
    columns: 2,
  },
  {
    id: "homepage.rails",
    title: "Product Rails",
    description: "Two collection-based product rails.",
    icon: "🛍️",
    columns: 2,
  },
  {
    id: "homepage.story",
    title: "Story",
    description: "About / story strip with a photo and text.",
    icon: "✍️",
    columns: 1,
  },
  {
    id: "homepage.testimonial",
    title: "Testimonial",
    description:
      "Shows your latest approved testimonial from Admin → Testimonials, with a link to the full reviews page.",
    icon: "💬",
    columns: 2,
  },
  {
    id: "homepage.promise",
    title: "Promise Strip",
    description: "Four short promises shown at the bottom of the homepage.",
    icon: "✅",
    columns: 2,
  },
];
