import type { TemplateField, TemplateFieldGroup } from "~/lib/template-fields";

const homepageHeroData: TemplateField[] = [
  {
    key: "default.homepage.hero-eyebrow",
    label: "Hero Eyebrow",
    description: "Small label above the business name in the hero",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
    defaultValue: "New this season",
    placeholder: "New this season",
  },
  {
    key: "default.homepage.hero-image",
    label: "Hero Image",
    description: "Background image for the hero section",
    type: "image",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "default.homepage.hero-description",
    label: "Hero Description",
    description: "Tagline displayed below the business name",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
    defaultValue: "A simple, ready-to-launch storefront.",
    placeholder: "e.g. A simple, ready-to-launch storefront.",
  },
  {
    key: "default.homepage.hero-button-text",
    label: "Primary Button Text",
    description: "Text for the primary hero CTA button",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    defaultValue: "Shop the catalog",
    placeholder: "Shop the catalog",
  },
  {
    key: "default.homepage.hero-button-link",
    label: "Primary Button Link",
    description: "URL for the primary hero CTA button",
    type: "url",
    page: "homepage",
    group: "homepage.hero",
    defaultValue: "/shop",
    placeholder: "/shop",
  },
  {
    key: "default.homepage.hero-button-2-text",
    label: "Secondary Button Text",
    description: "Text for the secondary hero CTA button",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    defaultValue: "Our story",
    placeholder: "Our story",
  },
  {
    key: "default.homepage.hero-button-2-link",
    label: "Secondary Button Link",
    description: "URL for the secondary hero CTA button",
    type: "url",
    page: "homepage",
    group: "homepage.hero",
    defaultValue: "/about",
    placeholder: "/about",
  },
];

const homepageCollectionsData: TemplateField[] = [
  {
    key: "default.homepage.collections-eyebrow",
    label: "Collections Eyebrow",
    description: "Small label above the collections section heading",
    type: "text",
    page: "homepage",
    group: "homepage.collections",
    gridColumn: "col-span-full",
    defaultValue: "Shop by collection",
    placeholder: "Shop by collection",
  },
  {
    key: "default.homepage.collections-heading",
    label: "Collections Heading",
    description: "Main heading for the collections grid",
    type: "text",
    page: "homepage",
    group: "homepage.collections",
    gridColumn: "col-span-full",
    defaultValue: "Collections",
    placeholder: "Collections",
  },
  {
    key: "default.homepage.collections-cta-text",
    label: "Collections CTA Text",
    description: "Link text to view all collections",
    type: "text",
    page: "homepage",
    group: "homepage.collections",
    defaultValue: "View everything",
    placeholder: "View everything",
  },
  {
    key: "default.homepage.collections-cta-link",
    label: "Collections CTA Link",
    description: "URL for the collections CTA link",
    type: "url",
    page: "homepage",
    group: "homepage.collections",
    defaultValue: "/collections",
    placeholder: "/collections",
  },
];

const homepageRailsData: TemplateField[] = [
  {
    key: "default.homepage.rail-one-collection",
    label: "Rail 1 — Collection",
    description:
      "Pick a collection for the first product rail. Defaults to featured products when unset.",
    type: "collection",
    page: "homepage",
    group: "homepage.rails",
    gridColumn: "col-span-1",
  },
  {
    key: "default.homepage.rail-one-eyebrow",
    label: "Rail 1 — Eyebrow",
    description: "Small label above the section heading",
    type: "text",
    page: "homepage",
    group: "homepage.rails",
    gridColumn: "col-span-1",
    defaultValue: "Featured",
    placeholder: "Featured",
  },
  {
    key: "default.homepage.rail-one-title",
    label: "Rail 1 — Heading",
    description: "Section heading for the first product rail",
    type: "text",
    page: "homepage",
    group: "homepage.rails",
    gridColumn: "col-span-1",
    defaultValue: "This week's picks.",
    placeholder: "This week's picks.",
  },
  {
    key: "default.homepage.rail-one-button-text",
    label: "Rail 1 — CTA Text",
    description: "Button label linking to the collection or shop",
    type: "text",
    page: "homepage",
    group: "homepage.rails",
    defaultValue: "All products",
    placeholder: "All products",
  },
  {
    key: "default.homepage.rail-one-button-link",
    label: "Rail 1 — CTA Link",
    description: "Overridden automatically if a collection is selected",
    type: "url",
    page: "homepage",
    group: "homepage.rails",
    defaultValue: "/shop",
    placeholder: "/shop",
  },
  {
    key: "default.homepage.rail-two-collection",
    label: "Rail 2 — Collection",
    description:
      "Pick a collection for the second product rail. Defaults to next featured products when unset.",
    type: "collection",
    page: "homepage",
    group: "homepage.rails",
    gridColumn: "col-span-1",
  },
  {
    key: "default.homepage.rail-two-eyebrow",
    label: "Rail 2 — Eyebrow",
    description: "Small label above the section heading",
    type: "text",
    page: "homepage",
    group: "homepage.rails",
    gridColumn: "col-span-1",
    defaultValue: "Customer favorites",
    placeholder: "Customer favorites",
  },
  {
    key: "default.homepage.rail-two-title",
    label: "Rail 2 — Heading",
    description: "Section heading for the second product rail",
    type: "text",
    page: "homepage",
    group: "homepage.rails",
    gridColumn: "col-span-1",
    defaultValue: "What people keep reaching for.",
    placeholder: "What people keep reaching for.",
  },
  {
    key: "default.homepage.rail-two-button-text",
    label: "Rail 2 — CTA Text",
    description: "Button label linking to the collection or shop",
    type: "text",
    page: "homepage",
    group: "homepage.rails",
    defaultValue: "Shop bestsellers",
    placeholder: "Shop bestsellers",
  },
  {
    key: "default.homepage.rail-two-button-link",
    label: "Rail 2 — CTA Link",
    description: "Overridden automatically if a collection is selected",
    type: "url",
    page: "homepage",
    group: "homepage.rails",
    defaultValue: "/shop",
    placeholder: "/shop",
  },
];

const homepageStoryData: TemplateField[] = [
  {
    key: "default.homepage.cta-eyebrow",
    label: "Story Eyebrow",
    description: "Small label above the story section heading",
    type: "text",
    page: "homepage",
    group: "homepage.story",
    gridColumn: "col-span-full",
    defaultValue: "A note from the maker",
    placeholder: "A note from the maker",
  },
  {
    key: "default.homepage.cta-heading",
    label: "Story Heading",
    description: "Heading for the story / about section",
    type: "text",
    page: "homepage",
    group: "homepage.story",
    gridColumn: "col-span-full",
    defaultValue: "Made by hand, with care.",
    placeholder: "Made by hand, with care.",
  },
  {
    key: "default.homepage.cta-description",
    label: "Story Body",
    description: "A sentence or two about who you are and why you started.",
    type: "textarea",
    page: "homepage",
    group: "homepage.story",
    gridColumn: "col-span-full",
    defaultValue:
      "Replace this with a sentence or two about who you are and why you started. A little goes a long way.",
    placeholder: "Tell your story...",
  },
  {
    key: "default.homepage.cta-image",
    label: "Story Image",
    description: "Lifestyle or studio photo for the story section",
    type: "image",
    page: "homepage",
    group: "homepage.story",
    gridColumn: "col-span-full",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "default.homepage.cta-button-text",
    label: "Story CTA Text",
    description: "Link label for the story section",
    type: "text",
    page: "homepage",
    group: "homepage.story",
    defaultValue: "Read more",
    placeholder: "Read more",
  },
  {
    key: "default.homepage.cta-button-link",
    label: "Story CTA Link",
    description: "Where the story link points",
    type: "url",
    page: "homepage",
    group: "homepage.story",
    defaultValue: "/about",
    placeholder: "/about",
  },
];

const homepageTestimonialData: TemplateField[] = [
  {
    key: "default.homepage.testimonial-quote",
    label: "Testimonial Quote",
    description: "A short review quote displayed on the homepage",
    type: "textarea",
    page: "homepage",
    group: "homepage.testimonial",
    gridColumn: "col-span-full",
    defaultValue:
      "Beautifully packaged, fairly priced, and exactly what I needed. The kind of small shop you want to keep buying from.",
    placeholder: "A short testimonial...",
  },
  {
    key: "default.homepage.testimonial-author",
    label: "Testimonial Author",
    description: "Name and/or label for the testimonial",
    type: "text",
    page: "homepage",
    group: "homepage.testimonial",
    gridColumn: "col-span-full",
    defaultValue: "— A happy customer · Verified buyer",
    placeholder: "— Devon M. · Verified buyer",
  },
  {
    key: "default.homepage.testimonial-cta-text",
    label: "Testimonial CTA Text",
    description: "Link to the testimonials / reviews page",
    type: "text",
    page: "homepage",
    group: "homepage.testimonial",
    defaultValue: "Read all reviews",
    placeholder: "Read all reviews",
  },
  {
    key: "default.homepage.testimonial-cta-link",
    label: "Testimonial CTA Link",
    description: "URL for the reviews link",
    type: "url",
    page: "homepage",
    group: "homepage.testimonial",
    defaultValue: "/testimonials",
    placeholder: "/testimonials",
  },
];

const homepagePromiseData: TemplateField[] = [
  {
    key: "default.homepage.promise-1-title",
    label: "Promise 1 — Title",
    description: "Heading for the first promise item",
    type: "text",
    page: "homepage",
    group: "homepage.promise",
    gridColumn: "col-span-1",
    defaultValue: "Free shipping",
    placeholder: "Free shipping",
  },
  {
    key: "default.homepage.promise-1-desc",
    label: "Promise 1 — Description",
    description: "Short description for the first promise item",
    type: "text",
    page: "homepage",
    group: "homepage.promise",
    gridColumn: "col-span-1",
    defaultValue: "On orders over $75 within the US.",
    placeholder: "On orders over $75 within the US.",
  },
  {
    key: "default.homepage.promise-2-title",
    label: "Promise 2 — Title",
    description: "Heading for the second promise item",
    type: "text",
    page: "homepage",
    group: "homepage.promise",
    gridColumn: "col-span-1",
    defaultValue: "Easy returns",
    placeholder: "Easy returns",
  },
  {
    key: "default.homepage.promise-2-desc",
    label: "Promise 2 — Description",
    description: "Short description for the second promise item",
    type: "text",
    page: "homepage",
    group: "homepage.promise",
    gridColumn: "col-span-1",
    defaultValue: "30 days, no questions asked.",
    placeholder: "30 days, no questions asked.",
  },
  {
    key: "default.homepage.promise-3-title",
    label: "Promise 3 — Title",
    description: "Heading for the third promise item",
    type: "text",
    page: "homepage",
    group: "homepage.promise",
    gridColumn: "col-span-1",
    defaultValue: "Handmade",
    placeholder: "Handmade",
  },
  {
    key: "default.homepage.promise-3-desc",
    label: "Promise 3 — Description",
    description: "Short description for the third promise item",
    type: "text",
    page: "homepage",
    group: "homepage.promise",
    gridColumn: "col-span-1",
    defaultValue: "Every item made with care.",
    placeholder: "Every item made with care.",
  },
  {
    key: "default.homepage.promise-4-title",
    label: "Promise 4 — Title",
    description: "Heading for the fourth promise item",
    type: "text",
    page: "homepage",
    group: "homepage.promise",
    gridColumn: "col-span-1",
    defaultValue: "Personal service",
    placeholder: "Personal service",
  },
  {
    key: "default.homepage.promise-4-desc",
    label: "Promise 4 — Description",
    description: "Short description for the fourth promise item",
    type: "text",
    page: "homepage",
    group: "homepage.promise",
    gridColumn: "col-span-1",
    defaultValue: "You'll always reach a real person.",
    placeholder: "You'll always reach a real person.",
  },
];

export const defaultHomepageData: TemplateField[] = [
  ...homepageHeroData,
  ...homepageCollectionsData,
  ...homepageRailsData,
  ...homepageStoryData,
  ...homepageTestimonialData,
  ...homepagePromiseData,
];

export const defaultHomepageFieldGroups: TemplateFieldGroup[] = [
  {
    id: "homepage.hero",
    title: "Hero Section",
    description: "Main banner at the top of the homepage",
    icon: "🎯",
    columns: 2,
  },
  {
    id: "homepage.collections",
    title: "Collections Section",
    description: "3-up collection grid below the hero",
    icon: "🗂️",
    columns: 2,
  },
  {
    id: "homepage.rails",
    title: "Product Rails",
    description: "Two collection-based product rails",
    icon: "🛍️",
    columns: 2,
  },
  {
    id: "homepage.story",
    title: "Story Section",
    description: "About / story strip with image and text",
    icon: "✍️",
    columns: 1,
  },
  {
    id: "homepage.testimonial",
    title: "Testimonial Preview",
    description: "A single featured customer quote",
    icon: "💬",
    columns: 2,
  },
  {
    id: "homepage.promise",
    title: "Promise Strip",
    description: "Four short promises shown at the bottom of the homepage",
    icon: "✅",
    columns: 2,
  },
];
