import type { TemplateField, TemplateFieldGroup } from "~/lib/template-fields";

const homepageHeroData: TemplateField[] = [
  {
    key: "default.homepage.hero-image",
    label: "Hero Image",
    description: "Background image for the hero section",
    type: "image",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "default.homepage.hero-description",
    label: "Hero Description",
    description: "Tagline displayed below the business name",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
    defaultValue: "Take a look around!",
    placeholder: "e.g. Take a look around!",
  },
  {
    key: "default.homepage.hero-button-text",
    label: "Primary Button Text",
    description: "Text for the primary hero CTA button",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    defaultValue: "Shop Now",
    placeholder: "Shop Now",
  },
  {
    key: "default.homepage.hero-button-link",
    label: "Primary Button Link",
    description: "URL for the primary hero CTA button",
    type: "url",
    page: "homepage",
    group: "homepage.hero",
    defaultValue: "/products",
    placeholder: "/products",
  },
  {
    key: "default.homepage.hero-button-2-text",
    label: "Secondary Button Text",
    description: "Text for the secondary hero CTA button",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    defaultValue: "View Deals",
    placeholder: "View Deals",
  },
  {
    key: "default.homepage.hero-button-2-link",
    label: "Secondary Button Link",
    description: "URL for the secondary hero CTA button",
    type: "url",
    page: "homepage",
    group: "homepage.hero",
    defaultValue: "/shop",
    placeholder: "/shop",
  },
];

const homepageRailsData: TemplateField[] = [
  // Rail 1
  {
    key: "default.homepage.rail-one-collection",
    label: "Rail 1 — Collection",
    description:
      "Pick a collection for the first product rail. Defaults to featured products when unset.",
    type: "collection",
    page: "homepage",
    group: "homepage.rails",
    gridColumn: "col-span-1",
  },
  {
    key: "default.homepage.rail-one-title",
    label: "Rail 1 — Heading",
    description: "Section heading for the first product rail",
    type: "text",
    page: "homepage",
    group: "homepage.rails",
    gridColumn: "col-span-1",
    defaultValue: "Featured Products",
    placeholder: "Featured Products",
  },
  {
    key: "default.homepage.rail-one-button-text",
    label: "Rail 1 — CTA Text",
    description: "Button label linking to the collection or shop",
    type: "text",
    page: "homepage",
    group: "homepage.rails",
    defaultValue: "Shop All",
    placeholder: "Shop All",
  },
  {
    key: "default.homepage.rail-one-button-link",
    label: "Rail 1 — CTA Link",
    description: "Overridden automatically if a collection is selected",
    type: "url",
    page: "homepage",
    group: "homepage.rails",
    defaultValue: "/shop",
    placeholder: "/shop",
  },
  // Rail 2
  {
    key: "default.homepage.rail-two-collection",
    label: "Rail 2 — Collection",
    description:
      "Pick a collection for the second product rail. Defaults to next featured products when unset.",
    type: "collection",
    page: "homepage",
    group: "homepage.rails",
    gridColumn: "col-span-1",
  },
  {
    key: "default.homepage.rail-two-title",
    label: "Rail 2 — Heading",
    description: "Section heading for the second product rail",
    type: "text",
    page: "homepage",
    group: "homepage.rails",
    gridColumn: "col-span-1",
    defaultValue: "New Arrivals",
    placeholder: "New Arrivals",
  },
  {
    key: "default.homepage.rail-two-button-text",
    label: "Rail 2 — CTA Text",
    description: "Button label linking to the collection or shop",
    type: "text",
    page: "homepage",
    group: "homepage.rails",
    defaultValue: "Shop All",
    placeholder: "Shop All",
  },
  {
    key: "default.homepage.rail-two-button-link",
    label: "Rail 2 — CTA Link",
    description: "Overridden automatically if a collection is selected",
    type: "url",
    page: "homepage",
    group: "homepage.rails",
    defaultValue: "/shop",
    placeholder: "/shop",
  },
];

const homepageCtaData: TemplateField[] = [
  {
    key: "default.homepage.cta-heading",
    label: "CTA Heading",
    description: "Heading for the call-to-action section",
    type: "text",
    page: "homepage",
    group: "homepage.cta",
    gridColumn: "col-span-full",
    defaultValue: "About Us",
    placeholder: "About Us",
  },
  {
    key: "default.homepage.cta-description",
    label: "CTA Description",
    description: "Body text for the call-to-action section",
    type: "textarea",
    page: "homepage",
    group: "homepage.cta",
    gridColumn: "col-span-full",
    defaultValue:
      "Learn more about our mission, values, and what makes us unique. We are dedicated to providing the best experience for our customers.",
    placeholder: "A short description about your brand...",
  },
  {
    key: "default.homepage.cta-image",
    label: "CTA Image",
    description: "Optional image for the call-to-action section",
    type: "image",
    page: "homepage",
    group: "homepage.cta",
    gridColumn: "col-span-full",
    defaultValue: "/placeholder.svg",
  },
];

export const defaultHomepageData = [
  ...homepageHeroData,
  ...homepageRailsData,
  ...homepageCtaData,
];

export const defaultHomepageFieldGroups: TemplateFieldGroup[] = [
  {
    id: "homepage.hero",
    title: "Hero Section",
    description: "Main banner at the top of the homepage",
    icon: "🎯",
    columns: 2,
  },
  {
    id: "homepage.rails",
    title: "Product Rails",
    description: "Two collection-based product rails below the hero",
    icon: "🛍️",
    columns: 2,
  },
  {
    id: "homepage.cta",
    title: "Call to Action",
    description: "About / CTA section at the bottom of the homepage",
    icon: "📣",
    columns: 1,
  },
];
