import { Droplets, Flower2, Leaf, Sparkles } from "lucide-react";

import type { TemplateField, TemplateFieldGroup } from "~/lib/template-fields";
import { resolveTemplateFields } from "~/lib/resolve-template-fields";

export const DEFAULT_ELEGANT_TRUST_BADGES = [
  {
    icon: Leaf,
    title: "Organic Certified",
    description: "100% organic ingredients",
  },
  {
    icon: Droplets,
    title: "Natural Extracts",
    description: "Pure botanical formulas",
  },
  {
    icon: Sparkles,
    title: "Clean Beauty",
    description: "No toxic chemicals",
  },
  {
    icon: Flower2,
    title: "Vegan Formula",
    description: "Plant-powered skincare",
  },
];

export const DEFAULT_ELEGANT_ABOUT_FEATURES = [
  {
    icon: Leaf,
    title: "Eco-Friendly Packaging",
    description: "Recyclable and biodegradable materials",
  },
  {
    icon: Droplets,
    title: "Natural Extracts",
    description: "Pure botanical formulas",
  },
  {
    icon: Sparkles,
    title: "Clean Beauty",
    description: "No toxic chemicals",
  },
  {
    icon: Flower2,
    title: "Vegan Formula",
    description: "Plant-powered skincare",
  },
];

const globalData: TemplateField[] = [
  {
    key: "elegant.tagline",
    label: "Tagline",
    description: "Your store's tagline shown in the hero section",
    type: "text",
    page: "global",
    defaultValue: "Natural Skincare",
    placeholder: "e.g. Natural Skincare",
  },
];

const homepageTrustBadgesData: TemplateField[] = [
  {
    key: "elegant.homepage.trust-badges-list",
    label: "Trust Badges",
    description: "Trust badges shown on the homepage",
    type: "list",
    page: "homepage",
    group: "homepage.trust-badges",
    gridColumn: "col-span-full",
    itemSchema: [
      {
        key: "icon",
        label: "Icon",
        type: "icon",
        description: "Icon shown on the card",
      },
      {
        key: "title",
        label: "Title",
        type: "text",
        description: "Card heading",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        description: "Supporting text",
      },
    ],
    minItems: 0,
    maxItems: 4,
  },
];

const homepageHeroData: TemplateField[] = [
  {
    key: "elegant.homepage.hero-image",
    label: "Hero Image",
    description: "Main hero image (used instead of video when set)",
    type: "image",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "elegant.homepage.hero-video",
    label: "Hero Video",
    description: "Main hero video",
    type: "video",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
  },

  {
    key: "elegant.homepage.hero-tagline",
    label: "Hero Tagline",
    description: "Tagline for the hero section",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Natural Skincare",
    placeholder: "e.g. Natural Skincare",
  },
  {
    key: "elegant.homepage.hero-title-line-1",
    label: "Hero Title — Line 1",
    description: "First line of the hero heading",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Made with care.",
    placeholder: "e.g. Made with care.",
  },
  {
    key: "elegant.homepage.hero-title-line-2",
    label: "Hero Title — Line 2",
    description: "Second line of the hero heading (displayed larger)",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Especially for you.",
    placeholder: "e.g. Especially for you.",
  },
  {
    key: "elegant.homepage.hero-description",
    label: "Hero Description",
    description: "Short tagline below the hero heading",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
    defaultValue: "Check out our products!",
    placeholder: "e.g. Discover our collection",
  },
  {
    key: "elegant.homepage.hero-button-text",
    label: "Hero Button Text",
    description: "Text for the hero CTA button",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Shop Now",
    placeholder: "Shop Now",
  },
  {
    key: "elegant.homepage.hero-button-link",
    label: "Hero Button Link",
    description: "URL for the hero CTA button",
    type: "url",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "/shop",
    placeholder: "/shop",
  },
];

const homepageProductsData: TemplateField[] = [
  {
    key: "elegant.homepage.products-tagline",
    label: "Products Tagline",
    description: "Tagline for the products section",
    type: "text",
    page: "homepage",
    group: "homepage.products",
    gridColumn: "col-span-full",
    defaultValue: "Our Products",
    placeholder: "e.g. Our Products",
  },
  {
    key: "elegant.homepage.products-title",
    label: "Products Title",
    description: "Title for the products section",
    type: "text",
    page: "homepage",
    group: "homepage.products",
    gridColumn: "col-span-full",
    defaultValue: "Featured",
    placeholder: "e.g. Featured",
  },
  {
    key: "elegant.homepage.products-description",
    label: "Products Description",
    description: "Description for the products section",
    type: "text",
    page: "homepage",
    group: "homepage.products",
    gridColumn: "col-span-full",
    defaultValue: "Explore our collection of premium products",
    placeholder: "e.g. Explore our collection of premium products",
  },
  {
    key: "elegant.homepage.products-button-text",
    label: "Products Button Text",
    description: "Text for the products CTA button",
    type: "text",
    page: "homepage",
    group: "homepage.products",
    gridColumn: "col-span-1",
    defaultValue: "View All Products",
    placeholder: "e.g. View All Products",
  },
  {
    key: "elegant.homepage.products-button-link",
    label: "Products Button Link",
    description: "URL for the products CTA button",
    type: "url",
    page: "homepage",
    group: "homepage.products",
    gridColumn: "col-span-1",
    defaultValue: "/shop",
    placeholder: "/shop",
  },
];

const homepageAboutData: TemplateField[] = [
  {
    key: "elegant.homepage.about.tagline",
    label: "About Tagline",
    description: "Tagline for the About section on the homepage",
    type: "text",
    page: "homepage",
    group: "homepage.about",
    gridColumn: "col-span-full",
    defaultValue: "About Us",
    placeholder: "About Us",
  },
  {
    key: "elegant.homepage.about.title",
    label: "About Title",
    description: "Heading for the About section on the homepage",
    type: "text",
    page: "homepage",
    group: "homepage.about",
    gridColumn: "col-span-full",
    defaultValue: "About Us",
    placeholder: "About Us",
  },
  {
    key: "elegant.homepage.about.text",
    label: "About Text",
    description: "Body text for the About section on the homepage",
    type: "textarea",
    page: "homepage",
    group: "homepage.about",
    gridColumn: "col-span-full",
    defaultValue:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec sollicitudin urna, vitae dictum nisi. Nullam lobortis ut neque eget cursus.",
    placeholder: "A short description about your brand or products...",
  },
  {
    key: "elegant.homepage.about.image",
    label: "About Image",
    description: "Image for the About section on the homepage",
    type: "image",
    page: "homepage",
    group: "homepage.about",
    gridColumn: "col-span-full",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "elegant.homepage.about.video",
    label: "About Video",
    description: "Video for the About section on the homepage",
    type: "video",
    page: "homepage",
    group: "homepage.about",
    gridColumn: "col-span-full",
  },
  {
    key: "elegant.homepage.about-features-list",
    label: "About Features List",
    description: "Features shown on the about section",
    type: "list",
    page: "homepage",
    group: "homepage.about",
    gridColumn: "col-span-full",
    itemSchema: [
      {
        key: "icon",
        label: "Icon",
        type: "icon",
        description: "Icon shown on the card",
      },
      {
        key: "title",
        label: "Title",
        type: "text",
        description: "Card heading",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        description: "Supporting text",
      },
    ],
    minItems: 0,
    maxItems: 4,
  },
];

const homepageFeaturesData: TemplateField[] = [
  {
    key: "elegant.homepage.feature-1-title",
    label: "Feature 1 Title",
    description: "Title for the first feature card",
    type: "text",
    page: "homepage",
    group: "homepage.features",
    defaultValue: "Eco-Friendly Packaging",
    placeholder: "e.g. Eco-Friendly Packaging",
  },
  {
    key: "elegant.homepage.feature-1-description",
    label: "Feature 1 Description",
    description: "Description for the first feature card",
    type: "text",
    page: "homepage",
    group: "homepage.features",
    defaultValue: "Recyclable and biodegradable materials",
    placeholder: "Short description...",
  },
  {
    key: "elegant.homepage.feature-2-title",
    label: "Feature 2 Title",
    description: "Title for the second feature card",
    type: "text",
    page: "homepage",
    group: "homepage.features",
    defaultValue: "100% Natural",
    placeholder: "e.g. 100% Natural",
  },
  {
    key: "elegant.homepage.feature-2-description",
    label: "Feature 2 Description",
    description: "Description for the second feature card",
    type: "text",
    page: "homepage",
    group: "homepage.features",
    defaultValue: "No synthetic chemicals or parabens",
    placeholder: "Short description...",
  },
  {
    key: "elegant.homepage.feature-3-title",
    label: "Feature 3 Title",
    description: "Title for the third feature card",
    type: "text",
    page: "homepage",
    group: "homepage.features",
    defaultValue: "Plant-Based",
    placeholder: "e.g. Plant-Based",
  },
  {
    key: "elegant.homepage.feature-3-description",
    label: "Feature 3 Description",
    description: "Description for the third feature card",
    type: "text",
    page: "homepage",
    group: "homepage.features",
    defaultValue: "Botanical extracts and essential oils",
    placeholder: "Short description...",
  },
  {
    key: "elegant.homepage.feature-4-title",
    label: "Feature 4 Title",
    description: "Title for the fourth feature card",
    type: "text",
    page: "homepage",
    group: "homepage.features",
    defaultValue: "Ethical Sourcing",
    placeholder: "e.g. Ethical Sourcing",
  },
  {
    key: "elegant.homepage.feature-4-description",
    label: "Feature 4 Description",
    description: "Description for the fourth feature card",
    type: "text",
    page: "homepage",
    group: "homepage.features",
    defaultValue: "Fair trade certified ingredients",
    placeholder: "Short description...",
  },
];

const homepageCtaData: TemplateField[] = [
  {
    key: "elegant.cta.background",
    label: "CTA Background Image",
    description: "Background image for the CTA banner",
    type: "image",
    page: "homepage",
    group: "homepage.cta",
    gridColumn: "col-span-full",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "elegant.cta.title",
    label: "CTA Title",
    description: "Main heading for the CTA banner",
    type: "text",
    page: "homepage",
    group: "homepage.cta",
    gridColumn: "col-span-full",
    defaultValue: "100% Natural",
    placeholder: "e.g. 100% Natural",
  },
  {
    key: "elegant.cta.pointone",
    label: "CTA Point One",
    description: "First bullet point for the CTA banner",
    type: "text",
    page: "homepage",
    group: "homepage.cta",
    defaultValue: "No Harsh Chemicals",
    placeholder: "e.g. No Harsh Chemicals",
  },
  {
    key: "elegant.cta.pointtwo",
    label: "CTA Point Two",
    description: "Second bullet point for the CTA banner",
    type: "text",
    page: "homepage",
    group: "homepage.cta",
    defaultValue: "Plant-Based Goodness",
    placeholder: "e.g. Plant-Based Goodness",
  },
  {
    key: "elegant.cta.pointthree",
    label: "CTA Point Three",
    description: "Third bullet point for the CTA banner",
    type: "text",
    page: "homepage",
    group: "homepage.cta",
    defaultValue: "Ethically Sourced",
    placeholder: "e.g. Ethically Sourced",
  },
];

const blogPageData: TemplateField[] = [
  {
    key: "elegant.blog.listing-title",
    label: "Blog listing title",
    description: "Heading shown at the top of the blog index",
    type: "text",
    page: "blog",
    group: "blog.header",
    gridColumn: "col-span-full",
    defaultValue: "Journal",
    placeholder: "Journal",
  },
  {
    key: "elegant.blog.listing-intro",
    label: "Blog listing intro",
    description: "Short text below the blog heading",
    type: "textarea",
    page: "blog",
    group: "blog.header",
    gridColumn: "col-span-full",
    defaultValue:
      "News, tips, and updates from our team. Use the search box to find a topic.",
    placeholder: "Intro paragraph for your blog...",
  },
];

const fieldGroups: TemplateFieldGroup[] = [
  {
    id: "homepage.hero",
    title: "Hero Section",
    description: "Main banner at the top of the homepage",
    icon: "🎯",
    columns: 2,
  },
  {
    id: "homepage.trust-badges",
    title: "Trust Badges",
    description: "Trust badges shown on the homepage",
    icon: "🔒",
    columns: 1,
  },
  {
    id: "homepage.products",
    title: "Products Section",
    description: "Products section on the homepage",
    icon: "📦",
    columns: 2,
  },
  {
    id: "homepage.about",
    title: "About Section",
    description: "About blurb and image shown below the product grid",
    icon: "📖",
    columns: 1,
  },
  {
    id: "homepage.features",
    title: "Feature Cards",
    description: "Four feature cards displayed alongside the about section",
    icon: "✨",
    columns: 2,
  },
  {
    id: "homepage.cta",
    title: "CTA Banner",
    description: "Call-to-action banner with bullet points",
    icon: "📣",
    columns: 1,
  },
  {
    id: "blog.header",
    title: "Blog listing",
    description: "Heading and intro on the blog index",
    icon: "📝",
    columns: 1,
  },
  {
    id: "contact.hero",
    title: "Contact Page Hero",
    description: "Heading and subtitle for the contact page",
    icon: "📬",
    columns: 1,
  },
  {
    id: "contact.info",
    title: "Contact Information",
    description: "Info panel shown alongside the contact form",
    icon: "📍",
    columns: 2,
  },
  {
    id: "contact.form",
    title: "Contact Form",
    description: "Heading above the contact form",
    icon: "✉️",
    columns: 1,
  },
  {
    id: "about.hero",
    title: "About Hero",
    description: "Hero image and heading for the about page",
    icon: "🌿",
    columns: 2,
  },
  {
    id: "about.story",
    title: "About Story Section",
    description: "Main story text and image",
    icon: "📖",
    columns: 2,
  },
  {
    id: "about.values",
    title: "Mission & Vision",
    description: "Mission and vision statements",
    icon: "🎯",
    columns: 1,
  },
];

const contactPageData: TemplateField[] = [
  {
    key: "elegant.contact.hero-title",
    label: "Contact Page Title",
    description: "Heading shown on the contact page hero",
    type: "text",
    page: "contact",
    group: "contact.hero",
    defaultValue: "Contact Us",
    placeholder: "Contact Us",
  },
  {
    key: "elegant.contact.hero-subtitle",
    label: "Contact Page Subtitle",
    description: "Optional subtitle below the contact page heading",
    type: "text",
    page: "contact",
    group: "contact.hero",
    defaultValue: "",
    placeholder: "We'd love to hear from you",
  },
  {
    key: "elegant.contact.info-title",
    label: "Contact Info Heading",
    description: "Heading for the contact information panel",
    type: "text",
    page: "contact",
    group: "contact.info",
    defaultValue: "Let's Connect",
    placeholder: "Let's Connect",
  },
  {
    key: "elegant.contact.info-description",
    label: "Contact Info Description",
    description: "Text below the contact info heading",
    type: "textarea",
    page: "contact",
    group: "contact.info",
    defaultValue: "",
    placeholder: "A short message about how to get in touch...",
  },
  {
    key: "elegant.contact.email",
    label: "Contact Email Override",
    description:
      "Override the contact email shown on this page (defaults to support email)",
    type: "text",
    page: "contact",
    group: "contact.info",
    defaultValue: "",
    placeholder: "hello@example.com",
  },
  {
    key: "elegant.contact.phone",
    label: "Contact Phone Override",
    description: "Override the phone number shown on this page",
    type: "text",
    page: "contact",
    group: "contact.info",
    defaultValue: "",
    placeholder: "(555) 000-0000",
  },
  {
    key: "elegant.contact.address",
    label: "Contact Address Override",
    description: "Override the address shown on this page",
    type: "textarea",
    page: "contact",
    group: "contact.info",
    defaultValue: "",
    placeholder: "123 Main St, Detroit, MI 48201",
  },
  {
    key: "elegant.contact.form-title",
    label: "Contact Form Heading",
    description: "Heading above the contact form",
    type: "text",
    page: "contact",
    group: "contact.form",
    defaultValue: "Send a Message",
    placeholder: "Send a Message",
  },
];

const aboutPageData: TemplateField[] = [
  {
    key: "elegant.about.hero-image",
    label: "About Hero Image",
    description: "Full-width image at the top of the about page",
    type: "image",
    page: "about",
    group: "about.hero",
    gridColumn: "col-span-full",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "elegant.about.hero-title",
    label: "About Hero Title",
    description: "Heading overlaid on the hero image",
    type: "text",
    page: "about",
    group: "about.hero",
    defaultValue: "Our Story",
    placeholder: "Our Story",
  },
  {
    key: "elegant.about.hero-subtitle",
    label: "About Hero Subtitle",
    description: "Optional subtitle below the hero heading",
    type: "text",
    page: "about",
    group: "about.hero",
    defaultValue: "",
    placeholder: "Where it all began",
  },
  {
    key: "elegant.about.story-heading",
    label: "Story Section Heading",
    description: "Heading for the main story section",
    type: "text",
    page: "about",
    group: "about.story",
    defaultValue: "About Us",
    placeholder: "About Us",
  },
  {
    key: "elegant.about.story-body",
    label: "Story Body Text",
    description: "Main body copy for the about page story section",
    type: "textarea",
    page: "about",
    group: "about.story",
    defaultValue: "",
    placeholder: "Tell your brand's story here...",
  },
  {
    key: "elegant.about.story-image",
    label: "Story Section Image",
    description: "Image shown alongside the story text",
    type: "image",
    page: "about",
    group: "about.story",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "elegant.about.mission",
    label: "Mission Statement",
    description: "Your brand's mission statement",
    type: "textarea",
    page: "about",
    group: "about.values",
    defaultValue: "",
    placeholder: "Our mission is to...",
  },
  {
    key: "elegant.about.vision",
    label: "Vision Statement",
    description: "Your brand's vision statement",
    type: "textarea",
    page: "about",
    group: "about.values",
    defaultValue: "",
    placeholder: "We envision a world where...",
  },
];

export const elegantData = {
  elegant: [
    ...globalData,
    ...homepageHeroData,
    ...homepageProductsData,
    ...homepageAboutData,
    ...homepageFeaturesData,
    ...homepageCtaData,
    ...blogPageData,
    ...contactPageData,
    ...aboutPageData,
    ...homepageTrustBadgesData,
  ],
};

export const elegantFieldGroups = {
  elegant: fieldGroups,
};

const _elegantFieldMap = new Map(
  elegantData.elegant.map((field) => [field.key, field]),
);

export function resolveFields(
  customFields: unknown,
  keys: string[],
): Record<string, string> {
  return resolveTemplateFields(customFields, keys, _elegantFieldMap);
}
