import type { TemplateField, TemplateFieldGroup } from "~/lib/template-fields";

// ─── Checkout field definitions ───────────────────────────────────────────────

export const viiCheckoutData: TemplateField[] = [
  {
    key: "vii.checkout.heading",
    label: "Checkout Heading",
    description: "The serif heading shown in the checkout header bar.",
    type: "text",
    page: "checkout",
    group: "checkout.main",
    gridColumn: "col-span-1",
    defaultValue: "Checkout",
  },
  {
    key: "vii.checkout.contact-overline",
    label: "Contact Information Overline",
    description: "Small uppercase label above the contact fieldset.",
    type: "text",
    page: "checkout",
    group: "checkout.main",
    gridColumn: "col-span-1",
    defaultValue: "Step 1",
  },
  {
    key: "vii.checkout.contact-heading",
    label: "Contact Information Heading",
    description: "Serif heading for the contact information fieldset.",
    type: "text",
    page: "checkout",
    group: "checkout.main",
    gridColumn: "col-span-1",
    defaultValue: "Contact Information",
  },
  {
    key: "vii.checkout.delivery-overline",
    label: "Delivery Overline",
    description: "Small uppercase label above the delivery method section.",
    type: "text",
    page: "checkout",
    group: "checkout.main",
    gridColumn: "col-span-1",
    defaultValue: "Step 2",
  },
  {
    key: "vii.checkout.delivery-heading",
    label: "Delivery Heading",
    description: "Serif heading for the delivery method section.",
    type: "text",
    page: "checkout",
    group: "checkout.main",
    gridColumn: "col-span-1",
    defaultValue: "Delivery",
  },
  {
    key: "vii.checkout.shipping-overline",
    label: "Shipping Address Overline",
    description: "Small uppercase label above the shipping address fieldset.",
    type: "text",
    page: "checkout",
    group: "checkout.main",
    gridColumn: "col-span-1",
    defaultValue: "Step 3",
  },
  {
    key: "vii.checkout.shipping-heading",
    label: "Shipping Address Heading",
    description: "Serif heading for the shipping address fieldset.",
    type: "text",
    page: "checkout",
    group: "checkout.main",
    gridColumn: "col-span-1",
    defaultValue: "Shipping Address",
  },
  {
    key: "vii.checkout.summary-overline",
    label: "Order Summary Overline",
    description: "Small uppercase label on the order summary panel.",
    type: "text",
    page: "checkout",
    group: "checkout.main",
    gridColumn: "col-span-1",
    defaultValue: "Your Order",
  },
  {
    key: "vii.checkout.summary-heading",
    label: "Order Summary Heading",
    description: "Serif heading for the order summary panel.",
    type: "text",
    page: "checkout",
    group: "checkout.main",
    gridColumn: "col-span-1",
    defaultValue: "Order Summary",
  },
  {
    key: "vii.checkout.submit-label",
    label: "Submit Button Label",
    description: "Text on the primary checkout submit button.",
    type: "text",
    page: "checkout",
    group: "checkout.main",
    gridColumn: "col-span-1",
    defaultValue: "Continue to payment",
  },
  {
    key: "vii.checkout.unavailable-heading",
    label: "Checkout Unavailable Heading",
    description:
      "Heading shown when the store has not yet set up payment processing.",
    type: "text",
    page: "checkout",
    group: "checkout.main",
    gridColumn: "col-span-1",
    defaultValue: "Checkout unavailable",
  },
  {
    key: "vii.checkout.unavailable-body",
    label: "Checkout Unavailable Body",
    description: "Body copy shown when checkout is unavailable.",
    type: "textarea",
    page: "checkout",
    group: "checkout.main",
    gridColumn: "col-span-full",
    defaultValue:
      "This store hasn't set up payment processing yet. Please contact the store owner.",
  },
  {
    key: "vii.checkout.empty-heading",
    label: "Empty Bag Heading",
    description: "Serif heading shown when the bag is empty.",
    type: "text",
    page: "checkout",
    group: "checkout.main",
    gridColumn: "col-span-1",
    defaultValue: "Your bag is empty",
  },
  {
    key: "vii.checkout.empty-cta",
    label: "Empty Bag CTA Label",
    description: "Label on the CTA button shown when the bag is empty.",
    type: "text",
    page: "checkout",
    group: "checkout.main",
    gridColumn: "col-span-1",
    defaultValue: "Continue shopping",
  },
];

// ─── Field group ──────────────────────────────────────────────────────────────

export const viiCheckoutFieldGroups: TemplateFieldGroup[] = [
  {
    id: "checkout.main",
    title: "Checkout",
    description:
      "Headings, overlines, button labels, and messaging for the checkout flow",
    icon: "💳",
    columns: 2,
  },
];
