import type { TemplateField, TemplateFieldGroup } from "~/lib/template-fields";

export const elegantBlogFieldGroups: TemplateFieldGroup[] = [
  {
    id: "blog.header",
    title: "Blog listing",
    description: "Heading and intro on the blog index",
    icon: "📝",
    columns: 1,
  },
  {
    id: "blog.list",
    title: "Blog feed",
    description:
      "Labels shown in the post feed, featured post, and search states on the blog index",
    icon: "🗂️",
    columns: 1,
  },
  {
    id: "blog.post",
    title: "Blog post",
    description: "Labels shown on individual blog post pages",
    icon: "📰",
    columns: 1,
  },
];

export const elegantBlogData: TemplateField[] = [
  {
    key: "elegant.blog.listing-title",
    label: "Blog listing title",
    description: "Heading shown at the top of the blog index",
    type: "text",
    page: "blog",
    group: "blog.header",
    gridColumn: "col-span-full",
    defaultValue: "Journal",
    placeholder: "Journal",
  },
  {
    key: "elegant.blog.listing-intro",
    label: "Blog listing intro",
    description: "Short text below the blog heading",
    type: "textarea",
    page: "blog",
    group: "blog.header",
    gridColumn: "col-span-full",
    defaultValue:
      "News, tips, and updates from our team. Use the search box to find a topic.",
    placeholder: "Intro paragraph for your blog...",
  },
  {
    key: "elegant.blog.listing-label",
    label: "Small label",
    description: "Small label above the blog listing heading.",
    type: "text",
    page: "blog",
    group: "blog.header",
    defaultValue: "Journal",
    placeholder: "Journal",
  },
  {
    key: "elegant.blog.empty-text",
    label: "No posts message",
    description:
      "Shown on the blog index when you haven't published any posts yet.",
    type: "text",
    page: "blog",
    group: "blog.list",
    gridColumn: "col-span-full",
    defaultValue: "No posts yet — check back soon.",
    placeholder: "No posts yet — check back soon.",
  },
  {
    key: "elegant.blog.featured-badge",
    label: "Featured post badge",
    description: "Small badge over the featured post's image.",
    type: "text",
    page: "blog",
    group: "blog.list",
    defaultValue: "Latest",
    placeholder: "Latest",
  },
  {
    key: "elegant.blog.featured-cta",
    label: "Featured post link text",
    description: "Link text below the featured post's excerpt.",
    type: "text",
    page: "blog",
    group: "blog.list",
    defaultValue: "Read the piece",
    placeholder: "Read the piece",
  },
  {
    key: "elegant.blog.grid-label",
    label: "Post grid label",
    description: "Small label above the grid of other posts.",
    type: "text",
    page: "blog",
    group: "blog.list",
    defaultValue: "More from the journal",
    placeholder: "More from the journal",
  },
  {
    key: "elegant.blog.no-results-heading",
    label: "No search results heading",
    description: "Shown when a search doesn't match any posts.",
    type: "text",
    page: "blog",
    group: "blog.list",
    defaultValue: "Nothing found.",
    placeholder: "Nothing found.",
  },
  {
    key: "elegant.blog.no-results-body",
    label: "No search results text",
    description: "Shown below the no-results heading.",
    type: "text",
    page: "blog",
    group: "blog.list",
    defaultValue: "Try a different search term.",
    placeholder: "Try a different search term.",
  },
  {
    key: "elegant.blog.post-back-text",
    label: "Back link text",
    description:
      "Link back to the blog listing, shown above and below the post.",
    type: "text",
    page: "blog",
    group: "blog.post",
    defaultValue: "Back to journal",
    placeholder: "Back to journal",
  },
  {
    key: "elegant.blog.post-keep-reading-label",
    label: "Keep reading label",
    description: "Small label above the related-posts heading.",
    type: "text",
    page: "blog",
    group: "blog.post",
    defaultValue: "Keep reading",
    placeholder: "Keep reading",
  },
  {
    key: "elegant.blog.post-keep-reading-heading",
    label: "Keep reading heading",
    description:
      'Heading above related posts. Rendered as "<text> <emphasized word>."',
    type: "text",
    page: "blog",
    group: "blog.post",
    defaultValue: "More from the",
    placeholder: "More from the",
  },
  {
    key: "elegant.blog.post-keep-reading-accent",
    label: "Keep reading emphasized word",
    description: "The italicized word at the end of the keep-reading heading.",
    type: "text",
    page: "blog",
    group: "blog.post",
    defaultValue: "journal",
    placeholder: "journal",
  },
  {
    key: "elegant.blog.post-all-posts-text",
    label: "All posts link text",
    description: "Link text at the bottom of the related-posts section.",
    type: "text",
    page: "blog",
    group: "blog.post",
    defaultValue: "All posts",
    placeholder: "All posts",
  },
];
