import type { TemplateField, TemplateFieldGroup } from "~/lib/template-fields";

export const elegantCollectionsFieldGroups: TemplateFieldGroup[] = [
  {
    id: "collections.header",
    title: "Collections page",
    description: "Heading, intro, and closing band on the collections listing",
    icon: "🗂️",
    columns: 1,
  },
  {
    id: "collections.detail",
    title: "Collection page",
    description: "Labels shown on an individual collection page",
    icon: "🏷️",
    columns: 1,
  },
];

export const elegantCollectionsData: TemplateField[] = [
  // ── collections.header ──
  {
    key: "elegant.collections.small-label",
    label: "Small label",
    description: "Small label above the collections heading.",
    type: "text",
    page: "collections",
    group: "collections.header",
    defaultValue: "Collections",
    placeholder: "Collections",
  },
  {
    key: "elegant.collections.heading",
    label: "Heading, first line",
    description: "First line of the collections page heading.",
    type: "text",
    page: "collections",
    group: "collections.header",
    defaultValue: "Small edits,",
    placeholder: "Small edits,",
  },
  {
    key: "elegant.collections.heading-accent",
    label: "Heading, second line",
    description: "Second, emphasized line of the collections page heading.",
    type: "text",
    page: "collections",
    group: "collections.header",
    defaultValue: "built around",
    placeholder: "built around",
  },
  {
    key: "elegant.collections.heading-line3",
    label: "Heading, third line",
    description: "Third line of the collections page heading.",
    type: "text",
    page: "collections",
    group: "collections.header",
    defaultValue: "a life.",
    placeholder: "a life.",
  },
  {
    key: "elegant.collections.intro",
    label: "Intro text",
    description: "Short text below the collections heading.",
    type: "textarea",
    page: "collections",
    group: "collections.header",
    gridColumn: "col-span-full",
    defaultValue:
      "Curated edits for moments in the day, thoughtfully arranged.",
    placeholder: "Intro paragraph for your collections page...",
  },
  {
    key: "elegant.collections.empty-heading",
    label: "Empty state heading",
    description: "Shown when you haven't published any collections yet.",
    type: "text",
    page: "collections",
    group: "collections.header",
    defaultValue: "Nothing here yet.",
    placeholder: "Nothing here yet.",
  },
  {
    key: "elegant.collections.empty-body",
    label: "Empty state text",
    description: "Shown below the empty-state heading.",
    type: "text",
    page: "collections",
    group: "collections.header",
    defaultValue: "Collections will appear once added.",
    placeholder: "Collections will appear once added.",
  },
  {
    key: "elegant.collections.cta-label",
    label: "Closing band label",
    description: "Small label above the closing call-to-action heading.",
    type: "text",
    page: "collections",
    group: "collections.header",
    defaultValue: "Don't see what you need?",
    placeholder: "Don't see what you need?",
  },
  {
    key: "elegant.collections.cta-heading",
    label: "Closing band heading",
    description:
      'Heading in the closing band. Rendered as "<text> <emphasized word>?"',
    type: "text",
    page: "collections",
    group: "collections.header",
    defaultValue: "Something more",
    placeholder: "Something more",
  },
  {
    key: "elegant.collections.cta-heading-accent",
    label: "Closing band emphasized word",
    description: "The italicized word in the closing band heading.",
    type: "text",
    page: "collections",
    group: "collections.header",
    defaultValue: "personal",
    placeholder: "personal",
  },
  {
    key: "elegant.collections.cta-body",
    label: "Closing band text",
    description: "Paragraph in the closing call-to-action band.",
    type: "textarea",
    page: "collections",
    group: "collections.header",
    gridColumn: "col-span-full",
    defaultValue:
      "Reach out and tell us what you're looking for. We'd love to help you find the right fit.",
    placeholder: "Tell visitors how to reach you...",
  },
  {
    key: "elegant.collections.cta-button-text",
    label: "Closing band button text",
    description: "Button in the closing band, links to your contact page.",
    type: "text",
    page: "collections",
    group: "collections.header",
    defaultValue: "Get in touch",
    placeholder: "Get in touch",
  },

  // ── collections.detail ──
  {
    key: "elegant.collections.detail-back-text",
    label: "Back link text",
    description: "Link back to the collections listing.",
    type: "text",
    page: "collections",
    group: "collections.detail",
    defaultValue: "All collections",
    placeholder: "All collections",
  },
  {
    key: "elegant.collections.detail-small-label",
    label: "Small label",
    description: "Small label above the collection name.",
    type: "text",
    page: "collections",
    group: "collections.detail",
    defaultValue: "Collection",
    placeholder: "Collection",
  },
  {
    key: "elegant.collections.detail-continue-text",
    label: "Continue browsing button text",
    description: "Button below the collection description, links to your shop.",
    type: "text",
    page: "collections",
    group: "collections.detail",
    defaultValue: "Continue browsing",
    placeholder: "Continue browsing",
  },
  {
    key: "elegant.collections.detail-products-label",
    label: "Products label",
    description: "Small label above the products heading.",
    type: "text",
    page: "collections",
    group: "collections.detail",
    defaultValue: "What's inside",
    placeholder: "What's inside",
  },
  {
    key: "elegant.collections.detail-count-word",
    label: "Products heading word",
    description:
      'The emphasized word after the product count, e.g. "The 6 <word>."',
    type: "text",
    page: "collections",
    group: "collections.detail",
    defaultValue: "pieces",
    placeholder: "pieces",
  },
  {
    key: "elegant.collections.detail-empty-heading",
    label: "Empty collection heading",
    description: "Shown when a collection has no products yet.",
    type: "text",
    page: "collections",
    group: "collections.detail",
    defaultValue: "Nothing here yet.",
    placeholder: "Nothing here yet.",
  },
  {
    key: "elegant.collections.detail-browse-all-text",
    label: "Browse all products link text",
    description: "Link shown when a collection has no products yet.",
    type: "text",
    page: "collections",
    group: "collections.detail",
    defaultValue: "Browse all products",
    placeholder: "Browse all products",
  },
  {
    key: "elegant.collections.detail-other-label",
    label: "Other collections label",
    description: "Small label above the other-collections heading.",
    type: "text",
    page: "collections",
    group: "collections.detail",
    defaultValue: "Other edits",
    placeholder: "Other edits",
  },
  {
    key: "elegant.collections.detail-other-heading",
    label: "Other collections heading",
    description:
      'Heading above other collections. Rendered as "<text> <emphasized word>."',
    type: "text",
    page: "collections",
    group: "collections.detail",
    defaultValue: "Or try one of",
    placeholder: "Or try one of",
  },
  {
    key: "elegant.collections.detail-other-accent",
    label: "Other collections emphasized word",
    description: "The italicized word at the end of the heading.",
    type: "text",
    page: "collections",
    group: "collections.detail",
    defaultValue: "these",
    placeholder: "these",
  },
];
