import type { TemplateField, TemplateFieldGroup } from "~/lib/template-fields";

export const elegantHomepageTrustBadgesData: TemplateField[] = [
  {
    key: "elegant.homepage.trust-badges-list",
    label: "Trust badges",
    description: "Trust badges shown in the scrolling strip below the hero.",
    type: "list",
    page: "homepage",
    group: "homepage.trust-badges",
    gridColumn: "col-span-full",
    itemLabel: "badge",
    defaultsWhenEmpty: true,
    itemSchema: [
      {
        key: "icon",
        label: "Icon",
        type: "icon",
        description: "Not shown in the scrolling strip.",
        optional: true,
      },
      {
        key: "title",
        label: "Title",
        type: "text",
        description: "Shown in the scrolling strip, e.g. 'Free Shipping'.",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        description: "Not shown in the scrolling strip.",
        optional: true,
      },
    ],
    minItems: 0,
    maxItems: 4,
  },
];

export const elegantHomepageHeroData: TemplateField[] = [
  {
    key: "elegant.homepage.hero-image",
    label: "Image",
    description: "Shown in the hero when no video is set below.",
    type: "image",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "elegant.homepage.hero-video",
    label: "Video",
    description:
      "Autoplaying video in the hero. Takes priority over the image above when set.",
    type: "video",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
  },

  {
    key: "elegant.homepage.hero-tagline",
    label: "Small label",
    description: "Small label above the hero heading. Leave blank to hide.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Thoughtfully Made",
    placeholder: "e.g. Thoughtfully Made",
  },
  {
    key: "elegant.homepage.hero-title-line-1",
    label: "Heading, first line",
    description: "First line of the hero heading.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Made with care.",
    placeholder: "e.g. Made with care.",
  },
  {
    key: "elegant.homepage.hero-title-line-2",
    label: "Heading, second line",
    description: "Second line of the hero heading, shown in italics.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Especially for you.",
    placeholder: "e.g. Especially for you.",
  },
  {
    key: "elegant.homepage.hero-description",
    label: "Intro text",
    description: "Short line below the hero heading.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
    defaultValue: "Check out our products!",
    placeholder: "e.g. Discover our collection",
  },
  {
    key: "elegant.homepage.hero-button-text",
    label: "Primary button text",
    description: "Text on the main button, e.g. Shop Now.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Shop Now",
    placeholder: "Shop Now",
  },
  {
    key: "elegant.homepage.hero-button-link",
    label: "Primary button link",
    description: "Where the button goes, e.g. /shop.",
    type: "url",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "/shop",
    placeholder: "/shop",
  },
  {
    key: "elegant.homepage.hero-secondary-button-text",
    label: "Secondary button text",
    description:
      "Text for the second button next to the primary one. Leave blank to hide it.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Our story",
    placeholder: "e.g. Our story",
  },
  {
    key: "elegant.homepage.hero-secondary-button-link",
    label: "Secondary button link",
    description: "Where the second button goes, e.g. /about.",
    type: "url",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "/about",
    placeholder: "/about",
  },
];

export const elegantHomepageProductsData: TemplateField[] = [
  {
    key: "elegant.homepage.products-tagline",
    label: "Small label",
    description:
      "Small label above the heading in the featured products section.",
    type: "text",
    page: "homepage",
    group: "homepage.products",
    gridColumn: "col-span-full",
    defaultValue: "Our Products",
    placeholder: "e.g. Our Products",
  },
  {
    key: "elegant.homepage.products-title",
    label: "Heading",
    description: "Heading for the featured products section.",
    type: "text",
    page: "homepage",
    group: "homepage.products",
    gridColumn: "col-span-full",
    defaultValue: "Featured",
    placeholder: "e.g. Featured",
  },
  {
    key: "elegant.homepage.products-description",
    label: "Description",
    description:
      "Short line below the heading, above the product grid. Leave blank to hide.",
    type: "text",
    page: "homepage",
    group: "homepage.products",
    gridColumn: "col-span-full",
    defaultValue: "Explore our collection of premium products",
    placeholder: "e.g. Explore our collection of premium products",
  },
  {
    key: "elegant.homepage.products-button-text",
    label: "Button text",
    description:
      "Text for the button below the product grid, linking to the shop.",
    type: "text",
    page: "homepage",
    group: "homepage.products",
    gridColumn: "col-span-1",
    defaultValue: "View All Products",
    placeholder: "e.g. View All Products",
  },
  {
    key: "elegant.homepage.products-button-link",
    label: "Button link",
    description: "Where the button goes, e.g. /shop.",
    type: "url",
    page: "homepage",
    group: "homepage.products",
    gridColumn: "col-span-1",
    defaultValue: "/shop",
    placeholder: "/shop",
  },
];

export const elegantHomepageAboutData: TemplateField[] = [
  {
    key: "elegant.homepage.about.tagline",
    label: "Small label",
    description: "Small label above the heading in the About section.",
    type: "text",
    page: "homepage",
    group: "homepage.about",
    gridColumn: "col-span-full",
    defaultValue: "About Us",
    placeholder: "About Us",
  },
  {
    key: "elegant.homepage.about.title",
    label: "Heading",
    description: "Heading for the About section on the homepage.",
    type: "text",
    page: "homepage",
    group: "homepage.about",
    gridColumn: "col-span-full",
    defaultValue: "About Us",
    placeholder: "About Us",
  },
  {
    key: "elegant.homepage.about.text",
    label: "Body text",
    description: "Main paragraph in the About section on the homepage.",
    type: "textarea",
    page: "homepage",
    group: "homepage.about",
    gridColumn: "col-span-full",
    defaultValue:
      "Every piece we offer is chosen with care — made to be used, loved, and kept for years.",
    placeholder: "A short description about your brand or products...",
  },
  {
    key: "elegant.homepage.about.image",
    label: "Image",
    description: "Shown in the About section when no video is set below.",
    type: "image",
    page: "homepage",
    group: "homepage.about",
    gridColumn: "col-span-full",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "elegant.homepage.about.video",
    label: "Video",
    description:
      "Autoplaying video in the About section. Takes priority over the image above when set.",
    type: "video",
    page: "homepage",
    group: "homepage.about",
    gridColumn: "col-span-full",
  },
  {
    key: "elegant.homepage.about.button-text",
    label: "Button text",
    description:
      "Label for the link to the full About page. Leave blank to hide the button.",
    type: "text",
    page: "homepage",
    group: "homepage.about",
    gridColumn: "col-span-1",
    defaultValue: "Read our story",
    placeholder: "e.g. Read our story",
  },
  {
    key: "elegant.homepage.about.button-link",
    label: "Button link",
    description: "Where the button goes, e.g. /about.",
    type: "url",
    page: "homepage",
    group: "homepage.about",
    gridColumn: "col-span-1",
    defaultValue: "/about",
    placeholder: "/about",
  },
];

export const elegantHomepageFeaturesData: TemplateField[] = [
  {
    key: "elegant.homepage.about-features-list",
    label: "Feature cards",
    description:
      "Feature cards shown inside the About section on the homepage.",
    type: "list",
    page: "homepage",
    group: "homepage.features",
    gridColumn: "col-span-full",
    itemLabel: "feature",
    defaultsWhenEmpty: true,
    itemSchema: [
      {
        key: "icon",
        label: "Icon",
        type: "icon",
        description: "Icon shown on the card.",
      },
      {
        key: "title",
        label: "Title",
        type: "text",
        description: "Card heading.",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        description: "Supporting text.",
      },
    ],
    minItems: 0,
    maxItems: 4,
  },
];

export const elegantHomepageCtaData: TemplateField[] = [
  {
    key: "elegant.cta.background",
    label: "Background image",
    description:
      "Optional background image for the banner. Leave blank for a plain dark background.",
    type: "image",
    page: "homepage",
    group: "homepage.cta",
    gridColumn: "col-span-full",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "elegant.cta.title",
    label: "Heading",
    description: "Main heading on the banner.",
    type: "text",
    page: "homepage",
    group: "homepage.cta",
    gridColumn: "col-span-full",
    defaultValue: "Quality You Can Trust",
    placeholder: "e.g. Quality You Can Trust",
  },
  {
    key: "elegant.cta.pointone",
    label: "First bullet point",
    description: "First checklist item on the banner. Leave blank to hide it.",
    type: "text",
    page: "homepage",
    group: "homepage.cta",
    defaultValue: "Carefully Selected Materials",
    placeholder: "e.g. Carefully Selected Materials",
  },
  {
    key: "elegant.cta.pointtwo",
    label: "Second bullet point",
    description: "Second checklist item on the banner. Leave blank to hide it.",
    type: "text",
    page: "homepage",
    group: "homepage.cta",
    defaultValue: "Thoughtful Craftsmanship",
    placeholder: "e.g. Thoughtful Craftsmanship",
  },
  {
    key: "elegant.cta.pointthree",
    label: "Third bullet point",
    description: "Third checklist item on the banner. Leave blank to hide it.",
    type: "text",
    page: "homepage",
    group: "homepage.cta",
    defaultValue: "Ethically Sourced",
    placeholder: "e.g. Ethically Sourced",
  },
];

export const elegantHomepageTestimonialsData: TemplateField[] = [
  {
    key: "elegant.homepage.testimonials-label",
    label: "Small label",
    description: "Small label above the testimonials heading.",
    type: "text",
    page: "homepage",
    group: "homepage.testimonials",
    gridColumn: "col-span-1",
    defaultValue: "Kind Words",
    placeholder: "e.g. Kind Words",
  },
  {
    key: "elegant.homepage.testimonials-heading",
    label: "Heading",
    description: "Heading above the scrolling testimonials.",
    type: "text",
    page: "homepage",
    group: "homepage.testimonials",
    gridColumn: "col-span-1",
    defaultValue: "Loved by our community",
    placeholder: "e.g. Loved by our community",
  },
];

export const elegantHomepageNewsletterData: TemplateField[] = [
  {
    key: "elegant.homepage.newsletter-label",
    label: "Small label",
    description: "Small label above the newsletter heading.",
    type: "text",
    page: "homepage",
    group: "homepage.newsletter",
    gridColumn: "col-span-full",
    defaultValue: "Letters from the studio",
    placeholder: "e.g. Letters from the studio",
  },
  {
    key: "elegant.homepage.newsletter-heading",
    label: "Heading",
    description:
      "The plain part of the newsletter heading (e.g. 'One short note,').",
    type: "text",
    page: "homepage",
    group: "homepage.newsletter",
    gridColumn: "col-span-1",
    defaultValue: "One short note,",
    placeholder: "e.g. One short note,",
  },
  {
    key: "elegant.homepage.newsletter-heading-accent",
    label: "Heading, highlighted words",
    description: "Shown in italics after the heading. Leave blank to hide.",
    type: "text",
    page: "homepage",
    group: "homepage.newsletter",
    gridColumn: "col-span-1",
    defaultValue: "once a month.",
    placeholder: "e.g. once a month.",
  },
  {
    key: "elegant.homepage.newsletter-body",
    label: "Body text",
    description:
      "Short paragraph below the newsletter heading. Leave blank to hide.",
    type: "textarea",
    page: "homepage",
    group: "homepage.newsletter",
    gridColumn: "col-span-full",
    defaultValue:
      "New arrivals, restocks, and the occasional behind-the-scenes note. No noise.",
  },
  {
    key: "elegant.homepage.newsletter-button",
    label: "Button text",
    description: "Text for the email sign-up button.",
    type: "text",
    page: "homepage",
    group: "homepage.newsletter",
    gridColumn: "col-span-1",
    defaultValue: "Subscribe",
    placeholder: "e.g. Subscribe",
  },
];

export const elegantHomepageFieldGroups: TemplateFieldGroup[] = [
  {
    id: "homepage.hero",
    title: "Hero",
    description: "Main banner at the top of the homepage",
    icon: "🎯",
    columns: 2,
  },
  {
    id: "homepage.trust-badges",
    title: "Trust badges",
    description: "Trust badges shown on the homepage",
    icon: "🔒",
    columns: 1,
  },
  {
    id: "homepage.products",
    title: "Featured products",
    description: "Product grid on the homepage, pulling from your catalog",
    icon: "📦",
    columns: 2,
  },
  {
    id: "homepage.about",
    title: "About",
    description: "About blurb and image or video shown below the product grid",
    icon: "📖",
    columns: 1,
  },
  {
    id: "homepage.features",
    title: "Feature cards",
    description: "Feature cards displayed inside the About section",
    icon: "✨",
    columns: 2,
  },
  {
    id: "homepage.testimonials",
    title: "Testimonials",
    description:
      "Small label and heading above the scrolling testimonials. Quotes come from Admin → Testimonials.",
    icon: "💬",
    columns: 2,
  },
  {
    id: "homepage.cta",
    title: "Banner with bullet points",
    description: "Full-width banner with a heading and short checklist",
    icon: "📣",
    columns: 1,
  },
  {
    id: "homepage.newsletter",
    title: "Newsletter",
    description:
      'Email sign-up band. Sign-ups aren\'t collected yet — submitting shows a friendly "check back soon" message instead of a fake success.',
    icon: "✉️",
    columns: 2,
  },
];

export const elegantHomepageData: TemplateField[] = [
  ...elegantHomepageHeroData,
  ...elegantHomepageProductsData,
  ...elegantHomepageAboutData,
  ...elegantHomepageFeaturesData,
  ...elegantHomepageTestimonialsData,
  ...elegantHomepageCtaData,
  ...elegantHomepageNewsletterData,
  ...elegantHomepageTrustBadgesData,
];
