import type { TemplateField, TemplateFieldGroup } from "~/lib/template-fields";
import type { TemplateSection } from "~/lib/template-sections";

/**
 * Full homepage build (design.md "Per-page section concepts › Homepage"):
 * hero (living sky), What We Do (three alternating lanes), Gallery, From
 * idea to theme (process), and the Estimate Quote band. Five sections, in
 * design.md's render order.
 *
 * "Dream it. Selest themes it." is split across three fields so the script
 * word ("Selest") sits mid-heading via `DreamH1`'s `after` prop — see
 * `dream-homepage-hero.tsx`. This replaces the phase-2 tracer, which
 * duplicated "Selest" by rendering the full must-keep line AND a separate
 * accent field (see chrome-phase2.md Deviation #3).
 */

// ─── Hero (not hideable) ────────────────────────────────────────────────────

const heroData: TemplateField[] = [
  {
    key: "dream.homepage.hero-heading",
    label: "Heading",
    description:
      "First part of the hero headline, before the highlighted word.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Dream it.",
  },
  {
    key: "dream.homepage.hero-accent",
    label: "Highlighted word",
    description:
      "One script-styled word in the middle of the hero headline. Never more than one word.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Selest",
  },
  {
    key: "dream.homepage.hero-heading-after",
    label: "Heading (continued)",
    description: "Rest of the hero headline, after the highlighted word.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "themes it.",
  },
  {
    key: "dream.homepage.hero-lede",
    label: "Intro",
    description: "Short line under the hero headline.",
    type: "textarea",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
    defaultValue:
      "Elegant decor, rentals, draping, and backdrops for celebrations that need a beautiful focal point.",
  },
  {
    key: "dream.homepage.hero-cta-label",
    label: "Primary button label",
    description: "Label for the hero's primary button.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Request an Estimate Quote",
  },
  {
    key: "dream.homepage.hero-cta-url",
    label: "Primary button link",
    description: "Where the hero's primary button links to.",
    type: "url",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "/contact",
  },
  {
    key: "dream.homepage.hero-cta-secondary-label",
    label: "Secondary button label",
    description: "Label for the hero's outlined secondary button.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "What We Do",
  },
  {
    key: "dream.homepage.hero-cta-secondary-url",
    label: "Secondary button link",
    description: "Where the hero's secondary button links to.",
    type: "url",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "#what-we-do",
  },
  {
    key: "dream.homepage.hero-shelf-photo-1",
    label: "Shelf photo 1",
    description:
      "Photo 1 on the hero shelf — a wide 3:2 frame. The shelf drifts slowly beneath the hero text.",
    type: "image",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "dream.homepage.hero-shelf-photo-1-alt",
    label: "Shelf photo 1 alt text",
    description:
      "Describes shelf photo 1 (the wide 3:2 frame) for screen readers.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "A white draped arbor set up outdoors by Selest",
  },
  {
    key: "dream.homepage.hero-shelf-photo-1-caption",
    label: "Shelf photo 1 caption",
    description:
      "Short caption pill shown over shelf photo 1 (the wide 3:2 frame).",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Outdoor draping",
  },
  {
    key: "dream.homepage.hero-shelf-photo-2",
    label: "Shelf photo 2",
    description:
      "Photo 2 on the hero shelf — a tall 4:5 frame. The shelf drifts slowly beneath the hero text.",
    type: "image",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "dream.homepage.hero-shelf-photo-2-alt",
    label: "Shelf photo 2 alt text",
    description:
      "Describes shelf photo 2 (the tall 4:5 frame) for screen readers.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "A wall of pastel balloons styled by Selest",
  },
  {
    key: "dream.homepage.hero-shelf-photo-2-caption",
    label: "Shelf photo 2 caption",
    description:
      "Short caption pill shown over shelf photo 2 (the tall 4:5 frame).",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Balloon wall",
  },
  {
    key: "dream.homepage.hero-shelf-photo-3",
    label: "Shelf photo 3",
    description:
      "Photo 3 on the hero shelf — a square frame. The shelf drifts slowly beneath the hero text.",
    type: "image",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "dream.homepage.hero-shelf-photo-3-alt",
    label: "Shelf photo 3 alt text",
    description:
      "Describes shelf photo 3 (the square frame) for screen readers.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "A tablescape with centerpieces styled by Selest",
  },
  {
    key: "dream.homepage.hero-shelf-photo-3-caption",
    label: "Shelf photo 3 caption",
    description:
      "Short caption pill shown over shelf photo 3 (the square frame).",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Tablescape",
  },
  {
    key: "dream.homepage.hero-shelf-photo-4",
    label: "Shelf photo 4",
    description:
      "Photo 4 on the hero shelf — a wide 3:2 frame. The shelf drifts slowly beneath the hero text.",
    type: "image",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "dream.homepage.hero-shelf-photo-4-alt",
    label: "Shelf photo 4 alt text",
    description:
      "Describes shelf photo 4 (the wide 3:2 frame) for screen readers.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "White throne chairs framed by draping at a Selest event",
  },
  {
    key: "dream.homepage.hero-shelf-photo-4-caption",
    label: "Shelf photo 4 caption",
    description:
      "Short caption pill shown over shelf photo 4 (the wide 3:2 frame).",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Throne chairs",
  },
  {
    key: "dream.homepage.hero-shelf-photo-5",
    label: "Shelf photo 5",
    description:
      "Photo 5 on the hero shelf — a tall 4:5 frame. The shelf drifts slowly beneath the hero text.",
    type: "image",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "dream.homepage.hero-shelf-photo-5-alt",
    label: "Shelf photo 5 alt text",
    description:
      "Describes shelf photo 5 (the tall 4:5 frame) for screen readers.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "A floral backdrop with candlelight styled by Selest",
  },
  {
    key: "dream.homepage.hero-shelf-photo-5-caption",
    label: "Shelf photo 5 caption",
    description:
      "Short caption pill shown over shelf photo 5 (the tall 4:5 frame).",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Floral backdrop",
  },
  {
    key: "dream.homepage.hero-shelf-photo-6",
    label: "Shelf photo 6",
    description:
      "Photo 6 on the hero shelf — a wide 3:2 frame. The shelf drifts slowly beneath the hero text.",
    type: "image",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "dream.homepage.hero-shelf-photo-6-alt",
    label: "Shelf photo 6 alt text",
    description:
      "Describes shelf photo 6 (the wide 3:2 frame) for screen readers.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "A table dressed with balloons at a Selest event",
  },
  {
    key: "dream.homepage.hero-shelf-photo-6-caption",
    label: "Shelf photo 6 caption",
    description:
      "Short caption pill shown over shelf photo 6 (the wide 3:2 frame).",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Balloon table",
  },
];

// ─── What We Do (hideable) ──────────────────────────────────────────────────

const whatWeDoData: TemplateField[] = [
  {
    key: "dream.homepage.what-we-do-heading",
    label: "Heading",
    description: "Heading for the What we do section.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "What we do",
  },
  {
    key: "dream.homepage.what-we-do-lede",
    label: "Intro",
    description: "Short line under the What we do heading.",
    type: "textarea",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-full",
    defaultValue:
      "Three ways Selest brings a celebration together, from the room itself to the smallest detail.",
  },
  {
    key: "dream.homepage.row-1-heading",
    label: "Row 1 heading",
    description: "Heading for the first of the three alternating rows.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "Event Decor",
  },
  {
    key: "dream.homepage.row-1-body",
    label: "Row 1 body",
    description: "Short paragraph for the first row.",
    type: "textarea",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-full",
    defaultValue:
      "Selest builds the room around your occasion — backdrops, florals, and focal points designed to be photographed.",
  },
  {
    key: "dream.homepage.row-1-link-label",
    label: "Row 1 link label",
    description: "Label for the first row's link.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "See Event Decor",
  },
  {
    key: "dream.homepage.row-1-link-url",
    label: "Row 1 link",
    description: "Where the first row's link points to.",
    type: "url",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "/services",
  },
  {
    key: "dream.homepage.row-1-photo",
    label: "Row 1 photo",
    description: "Main photo for the first row.",
    type: "image",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "dream.homepage.row-1-photo-alt",
    label: "Row 1 photo alt text",
    description: "Describes the first row's main photo for screen readers.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "A fully styled event decor setup by Selest",
  },
  {
    key: "dream.homepage.row-1-side-photo",
    label: "Row 1 side photo",
    description: "Smaller companion photo for the first row.",
    type: "image",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "dream.homepage.row-1-side-photo-alt",
    label: "Row 1 side photo alt text",
    description: "Describes the first row's side photo for screen readers.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "Detail of an event decor accent piece",
  },
  {
    key: "dream.homepage.row-2-heading",
    label: "Row 2 heading",
    description: "Heading for the second of the three alternating rows.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "Event Rentals",
  },
  {
    key: "dream.homepage.row-2-body",
    label: "Row 2 body",
    description: "Short paragraph for the second row.",
    type: "textarea",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-full",
    defaultValue:
      "Chairs, linens, and statement furniture — rented and delivered so every seat matches the mood.",
  },
  {
    key: "dream.homepage.row-2-link-label",
    label: "Row 2 link label",
    description: "Label for the second row's link.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "See Event Rentals",
  },
  {
    key: "dream.homepage.row-2-link-url",
    label: "Row 2 link",
    description: "Where the second row's link points to.",
    type: "url",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "/services",
  },
  {
    key: "dream.homepage.row-2-photo",
    label: "Row 2 photo",
    description: "Main photo for the second row.",
    type: "image",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "dream.homepage.row-2-photo-alt",
    label: "Row 2 photo alt text",
    description: "Describes the second row's main photo for screen readers.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "Rental chairs and table settings styled by Selest",
  },
  {
    key: "dream.homepage.row-2-side-photo",
    label: "Row 2 side photo",
    description: "Smaller companion photo for the second row.",
    type: "image",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "dream.homepage.row-2-side-photo-alt",
    label: "Row 2 side photo alt text",
    description: "Describes the second row's side photo for screen readers.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "Detail of a rental linen and place setting",
  },
  {
    key: "dream.homepage.row-3-heading",
    label: "Row 3 heading",
    description: "Heading for the third of the three alternating rows.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "Customized Draping",
  },
  {
    key: "dream.homepage.row-3-body",
    label: "Row 3 body",
    description: "Short paragraph for the third row.",
    type: "textarea",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-full",
    defaultValue:
      "Fabric shaped around your space — ceilings, walls, and thrones draped to fit the theme exactly.",
  },
  {
    key: "dream.homepage.row-3-link-label",
    label: "Row 3 link label",
    description: "Label for the third row's link.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "See Customized Draping",
  },
  {
    key: "dream.homepage.row-3-link-url",
    label: "Row 3 link",
    description: "Where the third row's link points to.",
    type: "url",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "/services",
  },
  {
    key: "dream.homepage.row-3-photo",
    label: "Row 3 photo",
    description: "Main photo for the third row.",
    type: "image",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "dream.homepage.row-3-photo-alt",
    label: "Row 3 photo alt text",
    description: "Describes the third row's main photo for screen readers.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "A draped ceiling and throne chair styled by Selest",
  },
  {
    key: "dream.homepage.row-3-side-photo",
    label: "Row 3 side photo",
    description: "Smaller companion photo for the third row.",
    type: "image",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "dream.homepage.row-3-side-photo-alt",
    label: "Row 3 side photo alt text",
    description: "Describes the third row's side photo for screen readers.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "Detail of draped fabric along a wall",
  },
];

// ─── Gallery (hideable) ─────────────────────────────────────────────────────

const galleryData: TemplateField[] = [
  {
    key: "dream.homepage.gallery-heading",
    label: "Heading",
    description: "Heading for the gallery section.",
    type: "text",
    page: "homepage",
    group: "homepage.gallery",
    gridColumn: "col-span-1",
    defaultValue: "Gallery",
  },
  {
    key: "dream.homepage.gallery-lede",
    label: "Intro",
    description: "Short line beside the gallery heading.",
    type: "textarea",
    page: "homepage",
    group: "homepage.gallery",
    gridColumn: "col-span-full",
    defaultValue: "A look at recent setups, straight from Selest's events.",
  },
  {
    key: "dream.homepage.gallery",
    label: "Gallery",
    description:
      "Pick a photo gallery to show here. Leave unset to show the designed empty state.",
    type: "gallery",
    page: "homepage",
    group: "homepage.gallery",
    gridColumn: "col-span-full",
    defaultValue: "",
  },
  {
    key: "dream.homepage.gallery-empty-message",
    label: "Empty state text",
    description:
      "Shown when no gallery is set (or it has no photos yet), above the link to the contact page.",
    type: "text",
    page: "homepage",
    group: "homepage.gallery",
    gridColumn: "col-span-full",
    defaultValue: "Photos of recent setups are on their way.",
  },
  {
    key: "dream.homepage.gallery-empty-link-label",
    label: "Empty state link text",
    description: "Label for the empty state's link to the contact page.",
    type: "text",
    page: "homepage",
    group: "homepage.gallery",
    gridColumn: "col-span-1",
    defaultValue: "Request an Estimate Quote",
  },
];

// ─── From idea to theme (hideable) ──────────────────────────────────────────

const processData: TemplateField[] = [
  {
    key: "dream.homepage.process-heading",
    label: "Heading",
    description: "Heading for the process section.",
    type: "text",
    page: "homepage",
    group: "homepage.process",
    gridColumn: "col-span-1",
    defaultValue: "From idea to theme",
  },
  {
    key: "dream.homepage.process-lede",
    label: "Intro",
    description: "Short line under the process heading.",
    type: "textarea",
    page: "homepage",
    group: "homepage.process",
    gridColumn: "col-span-full",
    defaultValue: "How a conversation with Selest becomes an event.",
  },
  {
    key: "dream.homepage.process-step-1-heading",
    label: "Step 1 heading",
    description: "Heading for the first step.",
    type: "text",
    page: "homepage",
    group: "homepage.process",
    gridColumn: "col-span-1",
    defaultValue: "Share the occasion",
  },
  {
    key: "dream.homepage.process-step-1-body",
    label: "Step 1 body",
    description: "Short line describing the first step.",
    type: "textarea",
    page: "homepage",
    group: "homepage.process",
    gridColumn: "col-span-full",
    defaultValue:
      "Tell Selest the date, the space, and the feeling you want the day to have.",
  },
  {
    key: "dream.homepage.process-step-2-heading",
    label: "Step 2 heading",
    description: "Heading for the second step.",
    type: "text",
    page: "homepage",
    group: "homepage.process",
    gridColumn: "col-span-1",
    defaultValue: "Choose the decor path",
  },
  {
    key: "dream.homepage.process-step-2-body",
    label: "Step 2 body",
    description: "Short line describing the second step.",
    type: "textarea",
    page: "homepage",
    group: "homepage.process",
    gridColumn: "col-span-full",
    defaultValue:
      "Selest recommends the decor, rentals, and draping that fit your event and space.",
  },
  {
    key: "dream.homepage.process-step-3-heading",
    label: "Step 3 heading",
    description: "Heading for the third step.",
    type: "text",
    page: "homepage",
    group: "homepage.process",
    gridColumn: "col-span-1",
    defaultValue: "Build the look",
  },
  {
    key: "dream.homepage.process-step-3-body",
    label: "Step 3 body",
    description: "Short line describing the third step.",
    type: "textarea",
    page: "homepage",
    group: "homepage.process",
    gridColumn: "col-span-full",
    defaultValue:
      "The pieces come together on-site, styled and ready before your guests arrive.",
  },
];

// ─── Estimate Quote band (hideable) ─────────────────────────────────────────

/**
 * Built-in checklist-chip rows — the single source for the
 * `dream.homepage.quote-chips` field's `defaultRows` and (via
 * `DREAM_QUOTE_CHIPS_FALLBACK` in `./dream-homepage-quote-chips.ts`) the
 * storefront's render fallback when the saved list is empty.
 */
export const DREAM_QUOTE_CHIPS_DEFAULT_ROWS: Record<string, string>[] = [
  { label: "Date + time" },
  { label: "Location" },
  { label: "Theme" },
  { label: "Colors" },
  { label: "Draping" },
  { label: "Rentals" },
  { label: "Space photos" },
  { label: "Full decor?" },
];

const quoteData: TemplateField[] = [
  {
    key: "dream.homepage.quote-heading",
    label: "Heading",
    description:
      "First part of this section's heading, before the highlighted words.",
    type: "text",
    page: "homepage",
    group: "homepage.quote",
    gridColumn: "col-span-1",
    defaultValue: "Request an",
  },
  {
    key: "dream.homepage.quote-accent",
    label: "Highlighted words",
    description: 'Script-styled rest of the heading (e.g. "Estimate Quote").',
    type: "text",
    page: "homepage",
    group: "homepage.quote",
    gridColumn: "col-span-1",
    defaultValue: "Estimate Quote",
  },
  {
    key: "dream.homepage.quote-lede",
    label: "Intro",
    description: "Short line under this section's heading.",
    type: "textarea",
    page: "homepage",
    group: "homepage.quote",
    gridColumn: "col-span-full",
    defaultValue:
      "Send Selest a few details and she'll recommend the right setup for your event.",
  },
  {
    key: "dream.homepage.quote-chips",
    label: "Checklist chips",
    description:
      "Up to 10 short chips listing what to have ready. Leave empty to use the default checklist.",
    type: "list",
    page: "homepage",
    group: "homepage.quote",
    gridColumn: "col-span-full",
    maxItems: 10,
    defaultsWhenEmpty: true,
    itemLabel: "detail",
    summaryKey: "label",
    itemSchema: [
      {
        key: "label",
        label: "Label",
        type: "text",
        description: "Short checklist detail, e.g. a date or a headcount.",
        placeholder: "e.g. Date + time",
      },
    ],
    defaultRows: DREAM_QUOTE_CHIPS_DEFAULT_ROWS,
  },
  {
    key: "dream.homepage.quote-cta-label",
    label: "Button label",
    description: "Label for this section's button.",
    type: "text",
    page: "homepage",
    group: "homepage.quote",
    gridColumn: "col-span-1",
    defaultValue: "Request an Estimate Quote",
  },
  {
    key: "dream.homepage.quote-cta-url",
    label: "Button link",
    description: "Where this section's button links to.",
    type: "url",
    page: "homepage",
    group: "homepage.quote",
    gridColumn: "col-span-1",
    defaultValue: "/contact",
  },
];

export const dreamHomepageData: TemplateField[] = [
  ...heroData,
  ...whatWeDoData,
  ...galleryData,
  ...processData,
  ...quoteData,
];

export const dreamHomepageFieldGroups: TemplateFieldGroup[] = [
  {
    id: "homepage.hero",
    title: "Hero",
    description:
      "Headline, intro, buttons, and the drifting photo shelf beneath them.",
    icon: "☁️",
    columns: 2,
  },
  {
    id: "homepage.what-we-do",
    title: "What we do",
    description:
      "Heading, intro, and the three alternating decor, rentals, and draping rows.",
    icon: "🪄",
    columns: 2,
  },
  {
    id: "homepage.gallery",
    title: "Gallery",
    description: "Heading, intro, and the picked photo gallery.",
    icon: "🖼️",
    columns: 2,
  },
  {
    id: "homepage.process",
    title: "From idea to theme",
    description: "Heading, intro, and the three-step process.",
    icon: "🧭",
    columns: 2,
  },
  {
    id: "homepage.quote",
    title: "Quote request",
    description:
      "Closing section with the checklist chips and quote request button.",
    icon: "✉️",
    columns: 2,
  },
];

export const dreamHomepageSections: TemplateSection[] = [
  {
    id: "homepage.hero",
    page: "homepage",
    title: "Hero",
    description:
      "Animated hero background with the business logo, headline, buttons, and the photo shelf",
    groupIds: ["homepage.hero"],
    order: 0,
    hideable: false,
  },
  {
    id: "homepage.what-we-do",
    page: "homepage",
    title: "What we do",
    description:
      "Three alternating rows: Event Decor, Event Rentals, Customized Draping",
    groupIds: ["homepage.what-we-do"],
    order: 1,
    hideable: true,
  },
  {
    id: "homepage.gallery",
    page: "homepage",
    title: "Gallery",
    description: "The owner-picked photo gallery, or a designed empty state",
    groupIds: ["homepage.gallery"],
    order: 2,
    hideable: true,
  },
  {
    id: "homepage.process",
    page: "homepage",
    title: "From idea to theme",
    description: "Three-step process from first message to styled event",
    groupIds: ["homepage.process"],
    order: 3,
    hideable: true,
  },
  {
    id: "homepage.quote",
    page: "homepage",
    title: "Quote request",
    description: "Closing checklist section linking to the contact page",
    groupIds: ["homepage.quote"],
    order: 4,
    hideable: true,
  },
];
