import type { TemplateField, TemplateFieldGroup } from "~/lib/template-fields";
import type { TemplateSection } from "~/lib/template-sections";

/**
 * Full homepage build (design.md "Per-page section concepts › Homepage"):
 * hero (living sky), What We Do (three alternating lanes), Gallery, From
 * idea to theme (process), and the Estimate Quote band. Five sections, in
 * design.md's render order.
 *
 * "Dream it. Selest themes it." is split across three fields so the script
 * word ("Selest") sits mid-heading via `DreamH1`'s `after` prop — see
 * `dream-homepage-hero.tsx`. This replaces the phase-2 tracer, which
 * duplicated "Selest" by rendering the full must-keep line AND a separate
 * accent field (see chrome-phase2.md Deviation #3).
 */

// ─── Hero (not hideable) ────────────────────────────────────────────────────

const heroData: TemplateField[] = [
  {
    key: "dream.homepage.hero-heading",
    label: "Heading",
    description:
      "First part of the hero headline, before the script accent word.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Dream it.",
  },
  {
    key: "dream.homepage.hero-accent",
    label: "Heading Accent Word",
    description:
      "One script word rendered in rose, mid-headline (design.md: never more than one word).",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Selest",
  },
  {
    key: "dream.homepage.hero-heading-after",
    label: "Heading (after accent)",
    description: "Rest of the headline, after the script accent word.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "themes it.",
  },
  {
    key: "dream.homepage.hero-lede",
    label: "Lede",
    description: "Short line under the hero headline.",
    type: "textarea",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
    defaultValue:
      "Elegant decor, rentals, draping, and backdrops for celebrations that need a beautiful focal point.",
  },
  {
    key: "dream.homepage.hero-cta-label",
    label: "Primary Button Label",
    description: "Label for the hero's primary button.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Request an Estimate Quote",
  },
  {
    key: "dream.homepage.hero-cta-url",
    label: "Primary Button Link",
    description: "Where the hero's primary button links to.",
    type: "url",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "/contact",
  },
  {
    key: "dream.homepage.hero-cta-secondary-label",
    label: "Secondary Button Label",
    description: "Label for the hero's outlined secondary button.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "What We Do",
  },
  {
    key: "dream.homepage.hero-cta-secondary-url",
    label: "Secondary Button Link",
    description: "Where the hero's secondary button links to.",
    type: "url",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "#what-we-do",
  },
  {
    key: "dream.homepage.hero-shelf-photo-1",
    label: "Shelf Photo 1",
    description:
      "Photo 1 on the hero shelf — a wide 3:2 frame. The shelf drifts slowly beneath the hero text.",
    type: "image",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "dream.homepage.hero-shelf-photo-1-alt",
    label: "Shelf Photo 1 Alt Text",
    description:
      "Describes shelf photo 1 (the wide 3:2 frame) for screen readers.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "A white draped arbor set up outdoors by Selest",
  },
  {
    key: "dream.homepage.hero-shelf-photo-1-caption",
    label: "Shelf Photo 1 Caption",
    description:
      "Short caption pill shown over shelf photo 1 (the wide 3:2 frame).",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Outdoor draping",
  },
  {
    key: "dream.homepage.hero-shelf-photo-2",
    label: "Shelf Photo 2",
    description:
      "Photo 2 on the hero shelf — a tall 4:5 frame. The shelf drifts slowly beneath the hero text.",
    type: "image",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "dream.homepage.hero-shelf-photo-2-alt",
    label: "Shelf Photo 2 Alt Text",
    description:
      "Describes shelf photo 2 (the tall 4:5 frame) for screen readers.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "A wall of pastel balloons styled by Selest",
  },
  {
    key: "dream.homepage.hero-shelf-photo-2-caption",
    label: "Shelf Photo 2 Caption",
    description:
      "Short caption pill shown over shelf photo 2 (the tall 4:5 frame).",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Balloon wall",
  },
  {
    key: "dream.homepage.hero-shelf-photo-3",
    label: "Shelf Photo 3",
    description:
      "Photo 3 on the hero shelf — a square frame. The shelf drifts slowly beneath the hero text.",
    type: "image",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "dream.homepage.hero-shelf-photo-3-alt",
    label: "Shelf Photo 3 Alt Text",
    description:
      "Describes shelf photo 3 (the square frame) for screen readers.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "A tablescape with centerpieces styled by Selest",
  },
  {
    key: "dream.homepage.hero-shelf-photo-3-caption",
    label: "Shelf Photo 3 Caption",
    description:
      "Short caption pill shown over shelf photo 3 (the square frame).",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Tablescape",
  },
  {
    key: "dream.homepage.hero-shelf-photo-4",
    label: "Shelf Photo 4",
    description:
      "Photo 4 on the hero shelf — a wide 3:2 frame. The shelf drifts slowly beneath the hero text.",
    type: "image",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "dream.homepage.hero-shelf-photo-4-alt",
    label: "Shelf Photo 4 Alt Text",
    description:
      "Describes shelf photo 4 (the wide 3:2 frame) for screen readers.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "White throne chairs framed by draping at a Selest event",
  },
  {
    key: "dream.homepage.hero-shelf-photo-4-caption",
    label: "Shelf Photo 4 Caption",
    description:
      "Short caption pill shown over shelf photo 4 (the wide 3:2 frame).",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Throne chairs",
  },
  {
    key: "dream.homepage.hero-shelf-photo-5",
    label: "Shelf Photo 5",
    description:
      "Photo 5 on the hero shelf — a tall 4:5 frame. The shelf drifts slowly beneath the hero text.",
    type: "image",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "dream.homepage.hero-shelf-photo-5-alt",
    label: "Shelf Photo 5 Alt Text",
    description:
      "Describes shelf photo 5 (the tall 4:5 frame) for screen readers.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "A floral backdrop with candlelight styled by Selest",
  },
  {
    key: "dream.homepage.hero-shelf-photo-5-caption",
    label: "Shelf Photo 5 Caption",
    description:
      "Short caption pill shown over shelf photo 5 (the tall 4:5 frame).",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Floral backdrop",
  },
  {
    key: "dream.homepage.hero-shelf-photo-6",
    label: "Shelf Photo 6",
    description:
      "Photo 6 on the hero shelf — a wide 3:2 frame. The shelf drifts slowly beneath the hero text.",
    type: "image",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "dream.homepage.hero-shelf-photo-6-alt",
    label: "Shelf Photo 6 Alt Text",
    description:
      "Describes shelf photo 6 (the wide 3:2 frame) for screen readers.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "A table dressed with balloons at a Selest event",
  },
  {
    key: "dream.homepage.hero-shelf-photo-6-caption",
    label: "Shelf Photo 6 Caption",
    description:
      "Short caption pill shown over shelf photo 6 (the wide 3:2 frame).",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Balloon table",
  },
];

// ─── What We Do (hideable) ──────────────────────────────────────────────────

const whatWeDoData: TemplateField[] = [
  {
    key: "dream.homepage.what-we-do-heading",
    label: "Heading",
    description: "Heading for the What We Do section.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "What we do",
  },
  {
    key: "dream.homepage.what-we-do-lede",
    label: "Lede",
    description: "Short line under the What We Do heading.",
    type: "textarea",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-full",
    defaultValue:
      "Three ways Selest brings a celebration together, from the room itself to the smallest detail.",
  },
  {
    key: "dream.homepage.row-1-heading",
    label: "Row 1 Heading — Event Decor",
    description: "Heading for the Event Decor row.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "Event Decor",
  },
  {
    key: "dream.homepage.row-1-body",
    label: "Row 1 Body — Event Decor",
    description: "Short paragraph describing Event Decor.",
    type: "textarea",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-full",
    defaultValue:
      "Selest builds the room around your occasion — backdrops, florals, and focal points designed to be photographed.",
  },
  {
    key: "dream.homepage.row-1-link-label",
    label: "Row 1 Link Label",
    description: "Label for the Event Decor row's link.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "See Event Decor",
  },
  {
    key: "dream.homepage.row-1-link-url",
    label: "Row 1 Link URL",
    description: "Where the Event Decor row's link points to.",
    type: "url",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "/services",
  },
  {
    key: "dream.homepage.row-1-photo",
    label: "Row 1 Main Photo",
    description: "Main photo for the Event Decor row.",
    type: "image",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "dream.homepage.row-1-photo-alt",
    label: "Row 1 Main Photo Alt Text",
    description: "Describes the Event Decor main photo for screen readers.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "A fully styled event decor setup by Selest",
  },
  {
    key: "dream.homepage.row-1-side-photo",
    label: "Row 1 Side Photo",
    description: "Smaller companion photo for the Event Decor row.",
    type: "image",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "dream.homepage.row-1-side-photo-alt",
    label: "Row 1 Side Photo Alt Text",
    description: "Describes the Event Decor side photo for screen readers.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "Detail of an event decor accent piece",
  },
  {
    key: "dream.homepage.row-2-heading",
    label: "Row 2 Heading — Event Rentals",
    description: "Heading for the Event Rentals row.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "Event Rentals",
  },
  {
    key: "dream.homepage.row-2-body",
    label: "Row 2 Body — Event Rentals",
    description: "Short paragraph describing Event Rentals.",
    type: "textarea",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-full",
    defaultValue:
      "Chairs, linens, and statement furniture — rented and delivered so every seat matches the mood.",
  },
  {
    key: "dream.homepage.row-2-link-label",
    label: "Row 2 Link Label",
    description: "Label for the Event Rentals row's link.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "See Event Rentals",
  },
  {
    key: "dream.homepage.row-2-link-url",
    label: "Row 2 Link URL",
    description: "Where the Event Rentals row's link points to.",
    type: "url",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "/services",
  },
  {
    key: "dream.homepage.row-2-photo",
    label: "Row 2 Main Photo",
    description: "Main photo for the Event Rentals row.",
    type: "image",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "dream.homepage.row-2-photo-alt",
    label: "Row 2 Main Photo Alt Text",
    description: "Describes the Event Rentals main photo for screen readers.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "Rental chairs and table settings styled by Selest",
  },
  {
    key: "dream.homepage.row-2-side-photo",
    label: "Row 2 Side Photo",
    description: "Smaller companion photo for the Event Rentals row.",
    type: "image",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "dream.homepage.row-2-side-photo-alt",
    label: "Row 2 Side Photo Alt Text",
    description: "Describes the Event Rentals side photo for screen readers.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "Detail of a rental linen and place setting",
  },
  {
    key: "dream.homepage.row-3-heading",
    label: "Row 3 Heading — Customized Draping",
    description: "Heading for the Customized Draping row.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "Customized Draping",
  },
  {
    key: "dream.homepage.row-3-body",
    label: "Row 3 Body — Customized Draping",
    description: "Short paragraph describing Customized Draping.",
    type: "textarea",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-full",
    defaultValue:
      "Fabric shaped around your space — ceilings, walls, and thrones draped to fit the theme exactly.",
  },
  {
    key: "dream.homepage.row-3-link-label",
    label: "Row 3 Link Label",
    description: "Label for the Customized Draping row's link.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "See Customized Draping",
  },
  {
    key: "dream.homepage.row-3-link-url",
    label: "Row 3 Link URL",
    description: "Where the Customized Draping row's link points to.",
    type: "url",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "/services",
  },
  {
    key: "dream.homepage.row-3-photo",
    label: "Row 3 Main Photo",
    description: "Main photo for the Customized Draping row.",
    type: "image",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "dream.homepage.row-3-photo-alt",
    label: "Row 3 Main Photo Alt Text",
    description:
      "Describes the Customized Draping main photo for screen readers.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "A draped ceiling and throne chair styled by Selest",
  },
  {
    key: "dream.homepage.row-3-side-photo",
    label: "Row 3 Side Photo",
    description: "Smaller companion photo for the Customized Draping row.",
    type: "image",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "dream.homepage.row-3-side-photo-alt",
    label: "Row 3 Side Photo Alt Text",
    description:
      "Describes the Customized Draping side photo for screen readers.",
    type: "text",
    page: "homepage",
    group: "homepage.what-we-do",
    gridColumn: "col-span-1",
    defaultValue: "Detail of draped fabric along a wall",
  },
];

// ─── Gallery (hideable) ─────────────────────────────────────────────────────

const galleryData: TemplateField[] = [
  {
    key: "dream.homepage.gallery-heading",
    label: "Heading",
    description: "Heading for the gallery section.",
    type: "text",
    page: "homepage",
    group: "homepage.gallery",
    gridColumn: "col-span-1",
    defaultValue: "Gallery",
  },
  {
    key: "dream.homepage.gallery-lede",
    label: "Lede",
    description: "Short line beside the gallery heading.",
    type: "textarea",
    page: "homepage",
    group: "homepage.gallery",
    gridColumn: "col-span-full",
    defaultValue: "A look at recent setups, straight from Selest's events.",
  },
  {
    key: "dream.homepage.gallery",
    label: "Gallery",
    description:
      "Pick a photo gallery to show here. Leave unset to show the designed empty state.",
    type: "gallery",
    page: "homepage",
    group: "homepage.gallery",
    gridColumn: "col-span-full",
    defaultValue: "",
  },
  {
    key: "dream.homepage.gallery-empty-message",
    label: "Empty State Message",
    description: "Shown when no gallery is set (or it has no photos yet).",
    type: "text",
    page: "homepage",
    group: "homepage.gallery",
    gridColumn: "col-span-full",
    defaultValue: "Photos of recent setups are on their way.",
  },
  {
    key: "dream.homepage.gallery-empty-link-label",
    label: "Empty State Link Label",
    description: "Label for the empty state's link to the Estimate Quote page.",
    type: "text",
    page: "homepage",
    group: "homepage.gallery",
    gridColumn: "col-span-1",
    defaultValue: "Request an Estimate Quote",
  },
];

// ─── From idea to theme (hideable) ──────────────────────────────────────────

const processData: TemplateField[] = [
  {
    key: "dream.homepage.process-heading",
    label: "Heading",
    description: "Heading for the process section.",
    type: "text",
    page: "homepage",
    group: "homepage.process",
    gridColumn: "col-span-1",
    defaultValue: "From idea to theme",
  },
  {
    key: "dream.homepage.process-lede",
    label: "Lede",
    description: "Short line under the process heading.",
    type: "textarea",
    page: "homepage",
    group: "homepage.process",
    gridColumn: "col-span-full",
    defaultValue: "How a conversation with Selest becomes an event.",
  },
  {
    key: "dream.homepage.process-step-1-heading",
    label: "Step 1 Heading",
    description: "Heading for the first step.",
    type: "text",
    page: "homepage",
    group: "homepage.process",
    gridColumn: "col-span-1",
    defaultValue: "Share the occasion",
  },
  {
    key: "dream.homepage.process-step-1-body",
    label: "Step 1 Body",
    description: "Short line describing the first step.",
    type: "textarea",
    page: "homepage",
    group: "homepage.process",
    gridColumn: "col-span-full",
    defaultValue:
      "Tell Selest the date, the space, and the feeling you want the day to have.",
  },
  {
    key: "dream.homepage.process-step-2-heading",
    label: "Step 2 Heading",
    description: "Heading for the second step.",
    type: "text",
    page: "homepage",
    group: "homepage.process",
    gridColumn: "col-span-1",
    defaultValue: "Choose the decor path",
  },
  {
    key: "dream.homepage.process-step-2-body",
    label: "Step 2 Body",
    description: "Short line describing the second step.",
    type: "textarea",
    page: "homepage",
    group: "homepage.process",
    gridColumn: "col-span-full",
    defaultValue:
      "Selest recommends the decor, rentals, and draping that fit your event and space.",
  },
  {
    key: "dream.homepage.process-step-3-heading",
    label: "Step 3 Heading",
    description: "Heading for the third step.",
    type: "text",
    page: "homepage",
    group: "homepage.process",
    gridColumn: "col-span-1",
    defaultValue: "Build the look",
  },
  {
    key: "dream.homepage.process-step-3-body",
    label: "Step 3 Body",
    description: "Short line describing the third step.",
    type: "textarea",
    page: "homepage",
    group: "homepage.process",
    gridColumn: "col-span-full",
    defaultValue:
      "The pieces come together on-site, styled and ready before your guests arrive.",
  },
];

// ─── Estimate Quote band (hideable) ─────────────────────────────────────────

const quoteData: TemplateField[] = [
  {
    key: "dream.homepage.quote-heading",
    label: "Heading",
    description: "First part of the band's heading, before the accent.",
    type: "text",
    page: "homepage",
    group: "homepage.quote",
    gridColumn: "col-span-1",
    defaultValue: "Request an",
  },
  {
    key: "dream.homepage.quote-accent",
    label: "Heading Accent",
    description:
      'Script-styled rest of the heading (design.md must-keep: "Estimate Quote").',
    type: "text",
    page: "homepage",
    group: "homepage.quote",
    gridColumn: "col-span-1",
    defaultValue: "Estimate Quote",
  },
  {
    key: "dream.homepage.quote-lede",
    label: "Lede",
    description: "Short line under the band's heading.",
    type: "textarea",
    page: "homepage",
    group: "homepage.quote",
    gridColumn: "col-span-full",
    defaultValue:
      "Send Selest a few details and she'll recommend the right setup for your event.",
  },
  {
    key: "dream.homepage.quote-chips",
    label: "Checklist Chips",
    description:
      "Up to 10 short chips listing what to have ready. Leave empty to use the default checklist.",
    type: "list",
    page: "homepage",
    group: "homepage.quote",
    gridColumn: "col-span-full",
    maxItems: 10,
    itemSchema: [
      {
        key: "label",
        label: "Label",
        type: "text",
        placeholder: "e.g. Date + time",
      },
    ],
  },
  {
    key: "dream.homepage.quote-cta-label",
    label: "Button Label",
    description: "Label for the band's button.",
    type: "text",
    page: "homepage",
    group: "homepage.quote",
    gridColumn: "col-span-1",
    defaultValue: "Request an Estimate Quote",
  },
  {
    key: "dream.homepage.quote-cta-url",
    label: "Button Link",
    description: "Where the band's button links to.",
    type: "url",
    page: "homepage",
    group: "homepage.quote",
    gridColumn: "col-span-1",
    defaultValue: "/contact",
  },
];

export const dreamHomepageData: TemplateField[] = [
  ...heroData,
  ...whatWeDoData,
  ...galleryData,
  ...processData,
  ...quoteData,
];

export const dreamHomepageFieldGroups: TemplateFieldGroup[] = [
  {
    id: "homepage.hero",
    title: "Hero",
    description:
      "The living-sky hero — logo, headline, lede, CTAs, and the drifting photo shelf beneath them.",
    icon: "☁️",
    columns: 2,
  },
  {
    id: "homepage.what-we-do",
    title: "What We Do",
    description:
      "Heading, lede, and the three alternating Decor / Rentals / Draping rows.",
    icon: "🪄",
    columns: 2,
  },
  {
    id: "homepage.gallery",
    title: "Gallery",
    description: "Heading, lede, and the picked photo gallery.",
    icon: "🖼️",
    columns: 2,
  },
  {
    id: "homepage.process",
    title: "From Idea to Theme",
    description: "Heading, lede, and the three-step process.",
    icon: "🧭",
    columns: 2,
  },
  {
    id: "homepage.quote",
    title: "Estimate Quote Band",
    description:
      "Closing band with the checklist chips and Estimate Quote button.",
    icon: "✉️",
    columns: 2,
  },
];

export const dreamHomepageSections: TemplateSection[] = [
  {
    id: "homepage.hero",
    page: "homepage",
    title: "Hero",
    description:
      "Living sky with the business logo, headline, CTAs, and the photo shelf",
    groupIds: ["homepage.hero"],
    order: 0,
    hideable: false,
  },
  {
    id: "homepage.what-we-do",
    page: "homepage",
    title: "What We Do",
    description:
      "Three alternating rows: Event Decor, Event Rentals, Customized Draping",
    groupIds: ["homepage.what-we-do"],
    order: 1,
    hideable: true,
  },
  {
    id: "homepage.gallery",
    page: "homepage",
    title: "Gallery",
    description: "The owner-picked photo gallery, or a designed empty state",
    groupIds: ["homepage.gallery"],
    order: 2,
    hideable: true,
  },
  {
    id: "homepage.process",
    page: "homepage",
    title: "From Idea to Theme",
    description: "Three-step process from first message to styled event",
    groupIds: ["homepage.process"],
    order: 3,
    hideable: true,
  },
  {
    id: "homepage.quote",
    page: "homepage",
    title: "Estimate Quote Band",
    description: "Closing checklist band linking to the Estimate Quote page",
    groupIds: ["homepage.quote"],
    order: 4,
    hideable: true,
  },
];
