import type { TemplateField, TemplateFieldGroup } from "~/lib/template-fields";

const homepageHeroData: TemplateField[] = [
  {
    key: "bamboo.homepage.hero-image",
    label: "Homepage Hero Image",
    description:
      "This image is used as the main focal point of the hero section.",
    type: "image",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
  },
  {
    key: "bamboo.homepage.hero-background",
    label: "Homepage Hero Background",
    description:
      "This image is used as the background texture of the hero section. Defaults to a subtle tan color if no image is provided.",
    type: "image",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
  },
  {
    key: "bamboo.homepage.hero-title",
    label: "Homepage Hero Title",
    description: "Title for the hero section",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Elevate Your Everyday",
  },
  {
    key: "bamboo.homepage.hero-tagline",
    label: "Homepage Hero Tagline",
    description: "Tagline for the hero section, above the title.",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
  },
  {
    key: "bamboo.homepage.hero-description",
    label: "Homepage Hero Description",
    description: "Description for the hero section",
    type: "textarea",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
    defaultValue:
      "Luxuriously soft, tree-free bamboo paper products crafted in Detroit. Because what you bring into your home should be as thoughtful as the life you build in it.",
  },
  {
    key: "bamboo.homepage.hero-primary-button-text",
    label: "Hero Primary Button Text",
    description: "Primary CTA button text (e.g. Shop Now)",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Shop Now",
  },
  {
    key: "bamboo.homepage.hero-primary-button-link",
    label: "Hero Primary Button Link",
    description: "Primary CTA button URL",
    type: "url",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "/shop",
  },
  {
    key: "bamboo.homepage.hero-secondary-button-text",
    label: "Hero Secondary Button Text",
    description: "Secondary button text (e.g. Our Story)",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Our Story",
  },
  {
    key: "bamboo.homepage.hero-secondary-button-link",
    label: "Hero Secondary Button Link",
    description: "Secondary button URL",
    type: "url",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "/about",
  },
];

const homepageFeaturedData: TemplateField[] = [
  {
    key: "bamboo.homepage.featured-title",
    label: "Featured Section Title",
    description: "Title for the featured products section",
    type: "text",
    page: "homepage",
    group: "homepage.featured",
    defaultValue: "Our Curated Collection",
  },
  {
    key: "bamboo.homepage.featured-description",
    label: "Featured Section Description",
    description: "Description below the featured section title",
    type: "textarea",
    page: "homepage",
    group: "homepage.featured",
    defaultValue:
      "Every product is 100% bamboo, tree-free, and crafted to the highest standard. No compromises.",
  },
  {
    key: "bamboo.homepage.featured-button-text",
    label: "View All Button Text",
    description: "Text for the View All Products button",
    type: "text",
    page: "homepage",
    group: "homepage.featured",
    defaultValue: "View All Products",
  },
];

const homepageAboutTeaserData: TemplateField[] = [
  {
    key: "bamboo.homepage.about-teaser-heading",
    label: "About Teaser Heading",
    description: "Heading for the about teaser block",
    type: "text",
    page: "homepage",
    group: "homepage.aboutTeaser",
    defaultValue: "From Detroit, With Purpose",
  },
  {
    key: "bamboo.homepage.about-teaser-body",
    label: "About Teaser Body",
    description: "Body text for the about teaser",
    type: "textarea",
    page: "homepage",
    group: "homepage.aboutTeaser",
    defaultValue:
      "We started Finally Results LLC with a simple belief: the everyday products in your home should be better -- better for your family, and better for the planet. Our roots in Detroit drive everything we do.",
  },
  {
    key: "bamboo.homepage.about-teaser-button-text",
    label: "About Teaser Button Text",
    description: "Learn More button text",
    type: "text",
    page: "homepage",
    group: "homepage.aboutTeaser",
    defaultValue: "Learn More",
  },
];

const homepageSustainabilityData: TemplateField[] = [
  {
    key: "bamboo.homepage.sustainability-1-label",
    label: "Sustainability Feature 1 Label",
    description: "First feature label (e.g. Premium Quality)",
    type: "text",
    page: "homepage",
    group: "homepage.sustainability",
    defaultValue: "Premium Quality",
  },
  {
    key: "bamboo.homepage.sustainability-1-description",
    label: "Sustainability Feature 1 Description",
    description: "First feature description",
    type: "textarea",
    page: "homepage",
    group: "homepage.sustainability",
    defaultValue:
      "Experience top-quality household paper products, crafted for comfort and reliability.",
  },
  {
    key: "bamboo.homepage.sustainability-2-label",
    label: "Sustainability Feature 2 Label",
    description: "Second feature label",
    type: "text",
    page: "homepage",
    group: "homepage.sustainability",
    defaultValue: "Competitive Prices",
  },
  {
    key: "bamboo.homepage.sustainability-2-description",
    label: "Sustainability Feature 2 Description",
    description: "Second feature description",
    type: "textarea",
    page: "homepage",
    group: "homepage.sustainability",
    defaultValue: "Affordable prices without compromising quality.",
  },
  {
    key: "bamboo.homepage.sustainability-3-label",
    label: "Sustainability Feature 3 Label",
    description: "Third feature label",
    type: "text",
    page: "homepage",
    group: "homepage.sustainability",
    defaultValue: "Customer-Centric Approach",
  },
  {
    key: "bamboo.homepage.sustainability-3-description",
    label: "Sustainability Feature 3 Description",
    description: "Third feature description",
    type: "textarea",
    page: "homepage",
    group: "homepage.sustainability",
    defaultValue: "Your satisfaction comes first in everything we do.",
  },
];

const homepageLocationData: TemplateField[] = [
  {
    key: "bamboo.homepage.location-heading",
    label: "Location Section Heading",
    description: "Heading for the location section on homepage",
    type: "text",
    page: "homepage",
    group: "homepage.location",
    defaultValue: "Our Location",
  },
];

const homepageTestimonialsData: TemplateField[] = [
  {
    key: "bamboo.homepage.testimonial-1-name",
    label: "Testimonial 1 Name",
    description: "First testimonial author name",
    type: "text",
    page: "homepage",
    group: "homepage.testimonials",
    defaultValue: "Sarah M.",
  },
  {
    key: "bamboo.homepage.testimonial-1-location",
    label: "Testimonial 1 Location",
    description: "First testimonial location",
    type: "text",
    page: "homepage",
    group: "homepage.testimonials",
    defaultValue: "Ann Arbor, MI",
  },
  {
    key: "bamboo.homepage.testimonial-1-quote",
    label: "Testimonial 1 Quote",
    description: "First testimonial quote",
    type: "textarea",
    page: "homepage",
    group: "homepage.testimonials",
    defaultValue:
      "I never thought I would care this much about toilet paper, but the softness and quality are genuinely impressive. Knowing it is eco-friendly makes it even better.",
  },
  {
    key: "bamboo.homepage.testimonial-2-name",
    label: "Testimonial 2 Name",
    description: "Second testimonial author name",
    type: "text",
    page: "homepage",
    group: "homepage.testimonials",
    defaultValue: "James T.",
  },
  {
    key: "bamboo.homepage.testimonial-2-location",
    label: "Testimonial 2 Location",
    description: "Second testimonial location",
    type: "text",
    page: "homepage",
    group: "homepage.testimonials",
    defaultValue: "Chicago, IL",
  },
  {
    key: "bamboo.homepage.testimonial-2-quote",
    label: "Testimonial 2 Quote",
    description: "Second testimonial quote",
    type: "textarea",
    page: "homepage",
    group: "homepage.testimonials",
    defaultValue:
      "We switched our entire household to Finally Results and have not looked back. The starter kit is the perfect way to try everything. Our septic system thanks us too.",
  },
  {
    key: "bamboo.homepage.testimonial-3-name",
    label: "Testimonial 3 Name",
    description: "Third testimonial author name",
    type: "text",
    page: "homepage",
    group: "homepage.testimonials",
    defaultValue: "Angela R.",
  },
  {
    key: "bamboo.homepage.testimonial-3-location",
    label: "Testimonial 3 Location",
    description: "Third testimonial location",
    type: "text",
    page: "homepage",
    group: "homepage.testimonials",
    defaultValue: "Detroit, MI",
  },
  {
    key: "bamboo.homepage.testimonial-3-quote",
    label: "Testimonial 3 Quote",
    description: "Third testimonial quote",
    type: "textarea",
    page: "homepage",
    group: "homepage.testimonials",
    defaultValue:
      "Supporting a local Detroit business that actually cares about sustainability? That is a win-win. The product quality is on par with luxury brands at a fraction of the environmental cost.",
  },
];

const aboutHeroData: TemplateField[] = [
  {
    key: "bamboo.about.hero-heading",
    label: "About Hero Heading",
    description: "Main heading for the about page",
    type: "text",
    page: "about",
    group: "about.hero",
    defaultValue: "Our Story",
  },
  {
    key: "bamboo.about.hero-intro",
    label: "About Hero Intro",
    description: "Intro paragraph below the heading",
    type: "textarea",
    page: "about",
    group: "about.hero",
    defaultValue:
      "Finally Results LLC was born from a simple belief: the everyday products in your home should be better -- better for your family, and better for the planet.",
  },
  {
    key: "bamboo.about.hero-image",
    label: "About Hero Image",
    description: "Image for the about page",
    type: "image",
    page: "about",
    group: "about.hero",
    gridColumn: "col-span-1",
  },
  {
    key: "bamboo.about.hero-tagline",
    label: "About Hero Tagline",
    description: "Tagline for the about page, above the title.",
    type: "text",
    page: "about",
    group: "about.hero",
    gridColumn: "col-span-1",
  },
];

const aboutMissionData: TemplateField[] = [
  {
    key: "bamboo.about.mission-heading",
    label: "Why We Started Heading",
    description: "Heading for the Why We Started section",
    type: "text",
    page: "about",
    group: "about.mission",
    defaultValue: "Why We Started",
  },
  {
    key: "bamboo.about.mission-paragraph",
    label: "Why We Started Text",
    description: "Text for the Why We Started section",
    type: "textarea",
    page: "about",
    group: "about.mission",
    defaultValue:
      "Welcome to Finally Results LLC, your trusted supplier of retail household paper products nationwide. We take pride in offering top-quality items that enhance your everyday life, such as toilet paper. Our commitment to excellence is evident in the careful selection of materials, ensuring that our bathroom toilet tissue is made of 100% recycled virgin pulp, delivering septic-safe properties and superior absorbency.",
  },
  {
    key: "bamboo.about.mission-image",
    label: "Why We Started Image",
    description: "Image for the Why We Started section",
    type: "image",
    page: "about",
    group: "about.mission",
    gridColumn: "col-span-1",
  },
];

const aboutValuesData: TemplateField[] = [
  {
    key: "bamboo.about.values-heading",
    label: "Values Section Heading",
    description: "What We Stand For heading",
    type: "text",
    page: "about",
    group: "about.values",
    defaultValue: "What We Stand For",
  },
  {
    key: "bamboo.about.value-1-title",
    label: "Value 1 Title",
    description: "First value card title",
    type: "text",
    page: "about",
    group: "about.values",
    defaultValue: "Sustainability First",
  },
  {
    key: "bamboo.about.value-1-description",
    label: "Value 1 Description",
    description: "First value card description",
    type: "textarea",
    page: "about",
    group: "about.values",
    defaultValue:
      "Every decision we make starts with the planet. From sourcing to packaging, we choose the path that leaves the smallest footprint.",
  },
  {
    key: "bamboo.about.value-2-title",
    label: "Value 2 Title",
    description: "Second value card title",
    type: "text",
    page: "about",
    group: "about.values",
    defaultValue: "Premium Quality",
  },
  {
    key: "bamboo.about.value-2-description",
    label: "Value 2 Description",
    description: "Second value card description",
    type: "textarea",
    page: "about",
    group: "about.values",
    defaultValue:
      "We refuse to compromise. Our bamboo products match or exceed the softness and strength of traditional premium brands.",
  },
  {
    key: "bamboo.about.value-3-title",
    label: "Value 3 Title",
    description: "Third value card title",
    type: "text",
    page: "about",
    group: "about.values",
    defaultValue: "Community Driven",
  },
  {
    key: "bamboo.about.value-3-description",
    label: "Value 3 Description",
    description: "Third value card description",
    type: "textarea",
    page: "about",
    group: "about.values",
    defaultValue:
      "Rooted in Detroit, we believe in building something that serves our community and sets an example for responsible business.",
  },
];

const aboutSupplierData: TemplateField[] = [
  {
    key: "bamboo.about.supplier-heading",
    label: "Supplier Heading",
    description: "Heading for the Supplier section",
    type: "text",
    page: "about",
    group: "about.supplier",
    defaultValue: "Supplier",
  },
  {
    key: "bamboo.about.supplier-text",
    label: "Supplier Text",
    description: "Text for the Supplier section",
    type: "textarea",
    page: "about",
    group: "about.supplier",
    defaultValue:
      "We are a trusted supplier of retail household paper products nationwide. We take pride in offering top-quality items that enhance your everyday life, such as toilet paper. Our commitment to excellence is evident in the careful selection of materials, ensuring that our bathroom toilet tissue is made of 100% recycled virgin pulp, delivering septic-safe properties and superior absorbency.",
  },
  {
    key: "bamboo.about.supplier-image",
    label: "Supplier Image",
    description: "Image for the Supplier section",
    type: "image",
    page: "about",
    group: "about.supplier",
    gridColumn: "col-span-1",
  },
];

const aboutWhyBambooData: TemplateField[] = [
  {
    key: "bamboo.about.why-bamboo-heading",
    label: "Why Bamboo Heading",
    description: "Why Bamboo? section heading",
    type: "text",
    page: "about",
    group: "about.whyBamboo",
    defaultValue: "Why Bamboo?",
  },
  {
    key: "bamboo.about.why-bamboo-intro",
    label: "Why Bamboo Intro",
    description: "Intro line for Why Bamboo section",
    type: "textarea",
    page: "about",
    group: "about.whyBamboo",
    defaultValue:
      "Bamboo is nature's most remarkable renewable resource. Here is why we chose it as the foundation for everything we make.",
  },
  {
    key: "bamboo.about.fact-1-title",
    label: "Bamboo Fact 1 Title",
    description: "First bamboo fact title",
    type: "text",
    page: "about",
    group: "about.whyBamboo",
    defaultValue: "Rapid Growth",
  },
  {
    key: "bamboo.about.fact-1-description",
    label: "Bamboo Fact 1 Description",
    description: "First bamboo fact description",
    type: "textarea",
    page: "about",
    group: "about.whyBamboo",
    defaultValue:
      "Bamboo grows up to 35 inches per day and reaches maturity in 3-5 years, compared to 20-50 years for hardwood trees.",
  },
  {
    key: "bamboo.about.fact-2-title",
    label: "Bamboo Fact 2 Title",
    description: "Second bamboo fact title",
    type: "text",
    page: "about",
    group: "about.whyBamboo",
    defaultValue: "No Replanting Needed",
  },
  {
    key: "bamboo.about.fact-2-description",
    label: "Bamboo Fact 2 Description",
    description: "Second bamboo fact description",
    type: "textarea",
    page: "about",
    group: "about.whyBamboo",
    defaultValue:
      "Bamboo regenerates from its own root system after harvest, which means the soil stays intact and carbon continues to be sequestered.",
  },
  {
    key: "bamboo.about.fact-3-title",
    label: "Bamboo Fact 3 Title",
    description: "Third bamboo fact title",
    type: "text",
    page: "about",
    group: "about.whyBamboo",
    defaultValue: "Water Efficient",
  },
  {
    key: "bamboo.about.fact-3-description",
    label: "Bamboo Fact 3 Description",
    description: "Third bamboo fact description",
    type: "textarea",
    page: "about",
    group: "about.whyBamboo",
    defaultValue:
      "Bamboo requires significantly less water than traditional tree farming and thrives without pesticides or fertilizers.",
  },
];

const aboutNationwideData: TemplateField[] = [
  {
    key: "bamboo.about.nationwide-heading",
    label: "Nationwide Distribution Heading",
    description: "Heading for the Nationwide Distribution section",
    type: "text",
    page: "about",
    group: "about.nationwide",
    defaultValue: "Nationwide Distribution",
  },
  {
    key: "bamboo.about.nationwide-text",
    label: "Nationwide Distribution Text",
    description: "Text for the Nationwide Distribution section",
    type: "textarea",
    page: "about",
    group: "about.nationwide",
    defaultValue:
      "We are a trusted supplier of retail household paper products nationwide. We take pride in offering top-quality items that enhance your everyday life, such as toilet paper. Our commitment to excellence is evident in the careful selection of materials, ensuring that our bathroom toilet tissue is made of 100% recycled virgin pulp, delivering septic-safe properties and superior absorbency.",
  },
  {
    key: "bamboo.about.nationwide-image",
    label: "Nationwide Distribution Image",
    description: "Image for the Nationwide Distribution section",
    type: "image",
    page: "about",
    group: "about.nationwide",
    gridColumn: "col-span-1",
  },
  {
    key: "bamboo.about.nationwide-fact-1-title",
    label: "Nationwide Distribution Fact 1 Title",
    description: "First fact title for the Nationwide Distribution section",
    type: "text",
    page: "about",
    group: "about.nationwide",
    defaultValue: "Nationwide Shipping",
  },
  {
    key: "bamboo.about.nationwide-fact-1-description",
    label: "Nationwide Distribution Fact 1 Description",
    description:
      "First fact description for the Nationwide Distribution section",
    type: "textarea",
    page: "about",
    group: "about.nationwide",
    defaultValue:
      "We ship our products to customers in all 50 states. We are a trusted supplier of retail household paper products nationwide. We take pride in offering top-quality items that enhance your everyday life, such as toilet paper. Our commitment to excellence is evident in the careful selection of materials, ensuring that our bathroom toilet tissue is made of 100% recycled virgin pulp, delivering septic-safe properties and superior absorbency.",
  },
  {
    key: "bamboo.about.nationwide-fact-2-title",
    label: "Nationwide Distribution Fact 2 Title",
    description: "Second fact title for the Nationwide Distribution section",
    type: "text",
    page: "about",
    group: "about.nationwide",
    defaultValue: "Nationwide Shipping",
  },
  {
    key: "bamboo.about.nationwide-fact-2-description",
    label: "Nationwide Distribution Fact 2 Description",
    description:
      "Second fact description for the Nationwide Distribution section",
    type: "textarea",
    page: "about",
    group: "about.nationwide",
    defaultValue:
      "We ship our products to customers in all 50 states. We are a trusted supplier of retail household paper products nationwide. We take pride in offering top-quality items that enhance your everyday life, such as toilet paper. Our commitment to excellence is evident in the careful selection of materials, ensuring that our bathroom toilet tissue is made of 100% recycled virgin pulp, delivering septic-safe properties and superior absorbency.",
  },
  {
    key: "bamboo.about.nationwide-fact-3-title",
    label: "Nationwide Distribution Fact 3 Title",
    description: "Third fact title for the Nationwide Distribution section",
    type: "text",
    page: "about",
    group: "about.nationwide",
    defaultValue: "Nationwide Shipping",
  },
  {
    key: "bamboo.about.nationwide-fact-3-description",
    label: "Nationwide Distribution Fact 3 Description",
    description:
      "Third fact description for the Nationwide Distribution section",
    type: "textarea",
    page: "about",
    group: "about.nationwide",
    defaultValue:
      "We ship our products to customers in all 50 states. We are a trusted supplier of retail household paper products nationwide. We take pride in offering top-quality items that enhance your everyday life, such as toilet paper. Our commitment to excellence is evident in the careful selection of materials, ensuring that our bathroom toilet tissue is made of 100% recycled virgin pulp, delivering septic-safe properties and superior absorbency.",
  },
];

const aboutDetroitData: TemplateField[] = [
  {
    key: "bamboo.about.detroit-heading",
    label: "Detroit Section Heading",
    description: "Rooted in Detroit heading",
    type: "text",
    page: "about",
    group: "about.detroit",
    defaultValue: "Rooted in Detroit",
  },
  {
    key: "bamboo.about.detroit-body",
    label: "Detroit Section Body",
    description: "Detroit roots paragraph",
    type: "textarea",
    page: "about",
    group: "about.detroit",
    defaultValue:
      "Detroit is a city that understands transformation. From the automotive revolution to its current renaissance in art, technology, and small business, this city teaches you that great things are built through perseverance and purpose. We chose to build Finally Results here because Detroit embodies everything our brand stands for: quality craftsmanship, community, and the belief that you can always do better.",
  },
];

const aboutCTAData: TemplateField[] = [
  {
    key: "bamboo.about.cta-heading",
    label: "CTA Heading",
    description: "CTA heading",
    type: "text",
    page: "about",
    group: "about.cta",
    defaultValue: "Ready to Make the Switch?",
  },
  {
    key: "bamboo.about.cta-text",
    label: "CTA Text",
    description: "CTA text",
    type: "textarea",
    page: "about",
    group: "about.cta",
    defaultValue:
      "Join the families, businesses, and communities across the nation who trust Finally Results for their everyday essentials.",
  },
  {
    key: "bamboo.about.cta-button-text",
    label: "CTA Button Text",
    description: "CTA button text",
    type: "text",
    page: "about",
    group: "about.cta",
    defaultValue: "Shop Our Products",
  },
  {
    key: "bamboo.about.cta-button-link",
    label: "CTA Button Link",
    description: "CTA button link",
    type: "url",
    page: "about",
    group: "about.cta",
    defaultValue: "/shop",
  },
];

const contactPageData: TemplateField[] = [
  {
    key: "bamboo.contact.header",
    label: "Contact Page Header",
    description: "Main heading for the contact page",
    type: "text",
    page: "contact",
    group: "contact.info",
    defaultValue: "Get in Touch",
  },
  {
    key: "bamboo.contact.subheader",
    label: "Contact Page Subheader",
    description: "Subheader or intro below the heading",
    type: "textarea",
    page: "contact",
    group: "contact.info",
    defaultValue:
      "Have a question, want to partner with us, or just want to say hello? We would love to hear from you.",
  },
  {
    key: "bamboo.contact.email",
    label: "Contact Email",
    description: "Email address displayed on contact page",
    type: "text",
    page: "contact",
    group: "contact.info",
    defaultValue: "hello@finallyresults.com",
  },
  {
    key: "bamboo.contact.location",
    label: "Contact Location",
    description: "Location text (e.g. city, state)",
    type: "text",
    page: "contact",
    group: "contact.info",
    defaultValue: "Detroit, Michigan",
  },
  {
    key: "bamboo.contact.phone",
    label: "Contact Phone",
    description: "Phone number",
    type: "text",
    page: "contact",
    group: "contact.info",
    defaultValue: "(313) 555-0199",
  },
  {
    key: "bamboo.contact.hours",
    label: "Business Hours",
    description: "Business hours text",
    type: "text",
    page: "contact",
    group: "contact.info",
    defaultValue: "Mon - Fri, 9am - 5pm EST",
  },
];

const globalLocationData: TemplateField[] = [
  {
    key: "bamboo.global.location-address",
    label: "Global Location Address",
    description: "Address for the global location section (used for map link)",
    type: "text",
    page: "global",
    group: "global.location",
    gridColumn: "col-span-full",
    defaultValue: "18058, Detroit, MI 48234",
  },
  {
    key: "bamboo.global.location-map",
    label: "Global Location Map",
    description: "Map image for the global location section",
    type: "image",
    page: "global",
    group: "global.location",
    gridColumn: "col-span-full",
  },
];

const fieldGroups: TemplateFieldGroup[] = [
  {
    id: "homepage.hero",
    title: "Hero Section",
    description: "Main banner area at the top of homepage",
    icon: "🎯",
    columns: 2,
  },
  {
    id: "homepage.featured",
    title: "Featured Products",
    description: "Featured products section title and description",
    icon: "📦",
    columns: 2,
  },
  {
    id: "homepage.aboutTeaser",
    title: "About Teaser",
    description: "About teaser block on homepage",
    icon: "📄",
    columns: 2,
  },
  {
    id: "homepage.sustainability",
    title: "Sustainability Banner",
    description:
      "Three feature highlights (e.g. Premium Quality, Competitive Prices)",
    icon: "🌿",
    columns: 2,
  },
  {
    id: "homepage.location",
    title: "Location Section",
    description: "Location heading on homepage",
    icon: "📍",
    columns: 2,
  },
  {
    id: "homepage.testimonials",
    title: "Testimonials",
    description: "Customer testimonials (name, location, quote)",
    icon: "💬",
    columns: 2,
  },
  {
    id: "about.hero",
    title: "About Hero",
    description: "About page hero heading and intro",
    icon: "📖",
    columns: 2,
  },
  {
    id: "about.mission",
    title: "Our Mission",
    description: "Mission section heading and paragraphs",
    icon: "🎯",
    columns: 2,
  },
  {
    id: "about.values",
    title: "What We Stand For",
    description: "Values section with three value cards",
    icon: "❤️",
    columns: 2,
  },
  {
    id: "about.supplier",
    title: "Supplier",
    description: "Supplier section heading and text",
    icon: "🏪",
    columns: 2,
  },
  {
    id: "about.whyBamboo",
    title: "Why Bamboo",
    description: "Why Bamboo section and bamboo facts",
    icon: "🎋",
    columns: 2,
  },
  {
    id: "about.nationwide",
    title: "Nationwide Distribution",
    description: "Nationwide distribution section",
    icon: "🗺️",
    columns: 2,
  },
  {
    id: "about.detroit",
    title: "Rooted in Detroit",
    description: "Detroit roots section",
    icon: "🏙️",
    columns: 2,
  },
  {
    id: "about.cta",
    title: "About CTA",
    description: "About CTA section",
    icon: "💬",
    columns: 2,
  },
  {
    id: "contact.info",
    title: "Contact Info",
    description: "Contact page header and contact details",
    icon: "📧",
    columns: 2,
  },
  {
    id: "global.location",
    title: "Global Location Section",
    description: "Global location section on the homepage",
    icon: "🗺️",
    columns: 2,
  },
];

export const bambooData = {
  bamboo: [
    ...homepageHeroData,
    ...homepageFeaturedData,
    ...homepageAboutTeaserData,
    ...homepageSustainabilityData,
    ...homepageLocationData,
    ...homepageTestimonialsData,
    ...aboutHeroData,
    ...aboutMissionData,
    ...aboutValuesData,
    ...aboutWhyBambooData,
    ...aboutDetroitData,
    ...contactPageData,
    ...globalLocationData,
    ...aboutSupplierData,
    ...aboutNationwideData,
    ...aboutCTAData,
  ],
};

export const bambooFieldGroups = {
  bamboo: fieldGroups,
};
