import type { TemplateField, TemplateFieldGroup } from "~/lib/template-fields";

export const globalData: TemplateField[] = [
  {
    key: "global.logo",
    label: "Logo",
    description: "Logo for the global header",
    type: "url",
    page: "global",
  },
  {
    key: "homepage.portfolio.gallery",
    label: "Portfolio Gallery",
    description: "Gallery to display on homepage",
    type: "gallery",
    page: "homepage",
  },
];

const aboutPageData: TemplateField[] = [
  {
    key: "modern.about.mission-header",
    label: "Mission Header",
    description: "Header for the mission section",
    type: "text",
    page: "about",
  },
  {
    key: "modern.about.mission-description",
    label: "Mission Description",
    description: "Description for the mission section",
    type: "textarea",
    page: "about",
  },
  {
    key: "modern.about.values-subheader",
    label: "Values Subheader",
    description: "Subheader for the values section",
    type: "text",
    page: "about",
  },
  {
    key: "modern.about.values-header",
    label: "Values Header",
    description: "Header for the values section",
    type: "text",
    page: "about",
  },
  {
    key: "modern.about.value-1-title",
    label: "Value 1 Title",
    description: "Title for the first value",
    type: "text",
    page: "about",
  },
  {
    key: "modern.about.value-1-description",
    label: "Value 1 Description",
    description: "Description for the first value",
    type: "textarea",
    page: "about",
  },
  {
    key: "modern.about.value-2-title",
    label: "Value 2 Title",
    description: "Title for the second value",
    type: "text",
    page: "about",
  },
  {
    key: "modern.about.value-2-description",
    label: "Value 2 Description",
    description: "Description for the second value",
    type: "textarea",
    page: "about",
  },
  {
    key: "modern.about.value-3-title",
    label: "Value 3 Title",
    description: "Title for the third value",
    type: "text",
    page: "about",
  },
  {
    key: "modern.about.value-3-description",
    label: "Value 3 Description",
    description: "Description for the third value",
    type: "textarea",
    page: "about",
  },
  {
    key: "modern.about.story-subheader",
    label: "Story Subheader",
    description: "Subheader for the story section",
    type: "text",
    page: "about",
  },
  {
    key: "modern.about.story-header",
    label: "Story Header",
    description: "Header for the story section",
    type: "text",
    page: "about",
  },
  {
    key: "modern.about.story-paragraph-1",
    label: "Story Paragraph 1",
    description: "First paragraph for the story section",
    type: "textarea",
    page: "about",
  },
  {
    key: "modern.about.story-paragraph-2",
    label: "Story Paragraph 2",
    description: "Second paragraph for the story section",
    type: "textarea",
    page: "about",
  },
  {
    key: "modern.about.first-image",
    label: "Story Image",
    description: "Image for the story section",
    type: "image",
    page: "about",
  },
  {
    key: "modern.about.cta-header",
    label: "CTA Header",
    description: "Header for the CTA section",
    type: "text",
    page: "about",
  },
  {
    key: "modern.about.cta-text",
    label: "CTA Text",
    description: "Text for the CTA section",
    type: "textarea",
    page: "about",
  },
  {
    key: "modern.about.cta-button-text",
    label: "CTA Button Text",
    description: "Button text for the CTA section",
    type: "text",
    page: "about",
  },
  {
    key: "modern.about.cta-button-link",
    label: "CTA Button Link",
    description: "Button link for the CTA section",
    type: "url",
    page: "about",
  },
];

const contactPageData: TemplateField[] = [
  {
    key: "modern.contact.header-subheader",
    label: "Header Subheader",
    description: "Subheader for the header section",
    type: "text",
    page: "contact",
  },
  {
    key: "modern.contact.header-title",
    label: "Header Title",
    description: "Title for the header section",
    type: "text",
    page: "contact",
  },
  {
    key: "modern.contact.header-description",
    label: "Header Description",
    description: "Description for the header section",
    type: "textarea",
    page: "contact",
  },
  {
    key: "modern.contact.info-title",
    label: "Info Section Title",
    description: "Title for the contact information section",
    type: "text",
    page: "contact",
  },
  {
    key: "modern.contact.info-description",
    label: "Info Section Description",
    description: "Description for the contact information section",
    type: "textarea",
    page: "contact",
  },
  {
    key: "modern.contact.email-label",
    label: "Email Label",
    description: "Label for the email field",
    type: "text",
    page: "contact",
  },
  {
    key: "modern.contact.email",
    label: "Email Address",
    description: "Email address for contact",
    type: "text",
    page: "contact",
  },
  {
    key: "modern.contact.phone-label",
    label: "Phone Label",
    description: "Label for the phone field",
    type: "text",
    page: "contact",
  },
  {
    key: "modern.contact.phone",
    label: "Phone Number",
    description: "Phone number for contact",
    type: "text",
    page: "contact",
  },
  {
    key: "modern.contact.address-label",
    label: "Address Label",
    description: "Label for the address field",
    type: "text",
    page: "contact",
  },
  {
    key: "modern.contact.address",
    label: "Address",
    description: "Physical address for contact",
    type: "textarea",
    page: "contact",
  },
  {
    key: "modern.contact.hours-label",
    label: "Hours Label",
    description: "Label for the hours field",
    type: "text",
    page: "contact",
  },
  {
    key: "modern.contact.hours",
    label: "Business Hours",
    description: "Business hours for contact",
    type: "textarea",
    page: "contact",
  },
  {
    key: "modern.contact.form-title",
    label: "Form Title",
    description: "Title for the contact form section",
    type: "text",
    page: "contact",
  },
  {
    key: "modern.contact.form-description",
    label: "Form Description",
    description: "Description for the contact form section",
    type: "text",
    page: "contact",
  },
  {
    key: "modern.contact.faq-subheader",
    label: "FAQ Subheader",
    description: "Subheader for the FAQ section",
    type: "text",
    page: "contact",
  },
  {
    key: "modern.contact.faq-title",
    label: "FAQ Title",
    description: "Title for the FAQ section",
    type: "text",
    page: "contact",
  },
  {
    key: "modern.contact.faq-1-question",
    label: "FAQ 1 Question",
    description: "Question for the first FAQ",
    type: "text",
    page: "contact",
  },
  {
    key: "modern.contact.faq-1-answer",
    label: "FAQ 1 Answer",
    description: "Answer for the first FAQ",
    type: "textarea",
    page: "contact",
  },
  {
    key: "modern.contact.faq-2-question",
    label: "FAQ 2 Question",
    description: "Question for the second FAQ",
    type: "text",
    page: "contact",
  },
  {
    key: "modern.contact.faq-2-answer",
    label: "FAQ 2 Answer",
    description: "Answer for the second FAQ",
    type: "textarea",
    page: "contact",
  },
  {
    key: "modern.contact.faq-3-question",
    label: "FAQ 3 Question",
    description: "Question for the third FAQ",
    type: "text",
    page: "contact",
  },
  {
    key: "modern.contact.faq-3-answer",
    label: "FAQ 3 Answer",
    description: "Answer for the third FAQ",
    type: "textarea",
    page: "contact",
  },
  {
    key: "modern.contact.faq-4-question",
    label: "FAQ 4 Question",
    description: "Question for the fourth FAQ",
    type: "text",
    page: "contact",
  },
  {
    key: "modern.contact.faq-4-answer",
    label: "FAQ 4 Answer",
    description: "Answer for the fourth FAQ",
    type: "textarea",
    page: "contact",
  },
];

const homepageData: TemplateField[] = [
  {
    key: "modern.homepage.hero-image",
    label: "Hero Image",
    description: "Image for the hero section",
    type: "image",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
    defaultValue: "/placeholder.svg",
  },
  {
    key: "modern.homepage.hero-title",
    label: "Hero Title",
    description: "Title for the hero section",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
    defaultValue: "Designed for modern living",
  },
  {
    key: "modern.homepage.hero-subtitle",
    label: "Hero Subtitle",
    description: "Subtitle for the hero section",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-full",
    defaultValue:
      "Thoughtfully crafted home goods that blend beauty with everyday function.",
  },
  {
    key: "modern.homepage.hero-cta-button-text",
    label: "Hero CTA Button Text",
    description: "Button text for the hero section",
    type: "text",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "Shop Collection",
  },
  {
    key: "modern.homepage.hero-cta-button-link",
    label: "Hero CTA Button Link",
    description: "Button link for the hero section",
    type: "url",
    page: "homepage",
    group: "homepage.hero",
    gridColumn: "col-span-1",
    defaultValue: "/shop",
  },
  {
    key: "modern.homepage.features-title-1",
    label: "Features Title 1",
    description: "Title for the features section",
    type: "text",
    page: "homepage",
    group: "homepage.features",
    gridColumn: "col-span-1",
    defaultValue: "What sets your business apart?",
  },
  {
    key: "modern.homepage.features-description-1",
    label: "Features Description",
    description: "Description for the features section",
    type: "textarea",
    page: "homepage",
    group: "homepage.features",
    gridColumn: "col-span-full",
    defaultValue:
      "We are a family-owned business that has been in operation for over 20 years.",
  },
  {
    key: "modern.homepage.features-title-2",
    label: "Features Title 2",
    description: "Title for the features section",
    type: "text",
    page: "homepage",
    group: "homepage.features",
    gridColumn: "col-span-1",
    defaultValue: "What sets your business apart?",
  },
  {
    key: "modern.homepage.features-description-2",
    label: "Features Description 2",
    description: "Description for the features section",
    type: "textarea",
    page: "homepage",
    group: "homepage.features",
    gridColumn: "col-span-full",
    defaultValue:
      "We are a family-owned business that has been in operation for over 20 years.",
  },
  {
    key: "modern.homepage.features-title-3",
    label: "Features Title 3",
    description: "Title for the features section",
    type: "text",
    page: "homepage",
    group: "homepage.features",
    gridColumn: "col-span-1",
    defaultValue: "What sets your business apart?",
  },
  {
    key: "modern.homepage.features-description-3",
    label: "Features Description 3",
    description: "Description for the features section",
    type: "textarea",
    page: "homepage",
    group: "homepage.features",
    gridColumn: "col-span-full",
    defaultValue:
      "We are a family-owned business that has been in operation for over 20 years.",
  },
  {
    key: "modern.homepage.products-title",
    label: "Products Title",
    description: "Title for the products section",
    type: "text",
    page: "homepage",
    group: "homepage.products",
    defaultValue: "Featured Products",
    gridColumn: "col-span-1",
  },
  {
    key: "modern.homepage.products-subtitle",
    label: "Products Subtitle",
    description: "Subtitle for the products section",
    type: "text",
    page: "homepage",
    group: "homepage.products",
    defaultValue: "Curated Selection",
    gridColumn: "col-span-1",
  },
  {
    key: "modern.homepage.about-title",
    label: "About Title",
    description: "Title for the about section",
    type: "text",
    page: "homepage",
    group: "homepage.about",
    gridColumn: "col-span-1",
    defaultValue: "About Us",
  },
  {
    key: "modern.homepage.about-subtitle",
    label: "About Subtitle",
    description: "Subtitle for the about section",
    type: "text",
    page: "homepage",
    group: "homepage.about",
    gridColumn: "col-span-1",
    defaultValue: "Our Story",
  },
  {
    key: "modern.homepage.about-text",
    label: "About Text",
    description: "Text for the about section",
    type: "textarea",
    page: "homepage",
    group: "homepage.about",
  },
  {
    key: "modern.homepage.about-image",
    label: "About Image",
    description: "Image for the about section",
    type: "image",
    page: "homepage",
    group: "homepage.about",
  },
  {
    key: "modern.homepage.about-cta-button-text",
    label: "About CTA Button Text",
    description: "Button text for the about cta section",
    type: "text",
    page: "homepage",
    group: "homepage.about",
    gridColumn: "col-span-1",
    defaultValue: "Learn More",
  },
  {
    key: "modern.homepage.about-cta-button-link",
    label: "About CTA Button Link",
    description: "Button link for the about cta section",
    type: "url",
    page: "homepage",
    group: "homepage.about",
  },
];

const fieldGroups: TemplateFieldGroup[] = [
  {
    id: "homepage.hero",
    title: "Hero Section",
    description: "Main banner area at the top of homepage",
    icon: "🎯",
    columns: 2,
  },

  {
    id: "homepage.features",
    title: "Values Section",
    description: "What sets your business apart?",
    icon: "🎯",
    columns: 2,
  },
  {
    id: "homepage.products",
    title: "Featured Products Section",
    description: "Featured products section after the hero section",
    icon: "🎯",
    columns: 1,
  },

  {
    id: "homepage.services",
    title: "Services Section",
    description: "Services section after the hero section",
    icon: "🎯",
    columns: 1,
  },

  {
    id: "homepage.about",
    title: "About Section",
    description: "About section on the homepage",
    icon: "🎯",
    columns: 2,
  },
  {
    id: "global.contact",
    title: "Contact",
    description:
      "Contact information for your business, displayed throughout the site",
    icon: "🎯",
    columns: 2,
  },
  {
    id: "global.services",
    title: "Services",
    description: "Services for your business, set as 4 services max",
    icon: "🎯",
    columns: 2,
  },
  {
    id: "global.cta",
    title: "Call to Action",
    description:
      "CTA section for your business, displayed at the bottom of the page",
    icon: "🎯",
    columns: 2,
  },

  {
    id: "global.header",
    title: "Header",
    description: "Header displayed on the top of most every page",
    icon: "🎯",
    columns: 2,
  },
  {
    id: "about.main",
    title: "About Us",
    description:
      "About us section for your business, displayed in the about page",
    icon: "🎯",
    columns: 2,
  },
  {
    id: "about.members",
    title: "Team Members",
    description: "Team members for your business, displayed in the about page",
    icon: "🎯",
    columns: 2,
  },
  {
    id: "products.main",
    title: "Services Main",
    description: "Main section for the services page",
    icon: "🎯",
    columns: 2,
  },
  {
    id: "products.faq",
    title: "Services FAQ",
    description: "FAQ section for the services page",
    icon: "🎯",
    columns: 2,
  },
  {
    id: "products.testimonials",
    title: "Services Testimonials",
    description: "Testimonials section for the services page",
    icon: "🎯",
    columns: 2,
  },
  {
    id: "contact.main",
    title: "Contact Main",
    description: "Main section for the contact page",
    icon: "🎯",
    columns: 2,
  },
];

export const modernData = {
  modern: [...globalData, ...aboutPageData, ...contactPageData, ...homepageData],
};

export const modernFieldGroups = {
  modern: fieldGroups,
};
